<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header text-right">
<button type="submit" form="form-backup" data-toggle="tooltip" title="<?php echo $button_backup; ?>" class="btn btn-app"><i class="fa fa-download"></i> <?php echo $button_backup; ?></button>
        <button type="submit" form="form-restore" data-toggle="tooltip" title="<?php echo $button_restore; ?>" class="btn btn-app"><i class="fa fa-upload"></i> <?php echo $button_restore; ?></button>
        </div>
        <div class="box-body">
            <form action="<?php echo $restore; ?>" method="post" enctype="multipart/form-data" id="form-restore" class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-import"><?php echo $entry_restore; ?></label>
                    <div class="col-sm-10">
                        <input type="file" name="import" id="input-import" />
                    </div>
                </div>
            </form>
            <form action="<?php echo $backup; ?>" method="post" enctype="multipart/form-data" id="form-backup" class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label"><?php echo $entry_backup; ?></label>
                    <div class="col-sm-10">
                        <div class="scrollbox">
                            <ul class="list-group">
                            <?php foreach ($tables as $table) { ?>
                                <li class="list-group-item">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="backup[]" value="<?php echo $table; ?>" checked="checked" />
                                        <?php echo $table; ?></label>
                                </div>
                                    </li>
                            <?php } ?>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-link" onclick="$(this).parent().find(':checkbox').prop('checked', true);"><?php echo $text_select_all; ?></button> / <button type="button" class="btn btn-link" onclick="$(this).parent().find(':checkbox').prop('checked', false);"><?php echo $text_unselect_all; ?></button></div>
                </div>
            </form>
        </div>
    </div>
</section>

<?php echo $footer; ?>