<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box">

        <div class="box-header text-right">
  <a href="<?php echo $insert; ?>" data-toggle="tooltip" title="<?php echo $button_insert; ?>" class="btn btn-app"><i class="fa fa-plus text-primary"></i> <?php echo $button_insert; ?></a>
        <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-app" onclick="confirm('<?php echo $text_confirm; ?>') ? $('#form-upload').submit() : false;"><i class="fa fa-trash-o text-danger"></i> <?php echo $button_delete; ?></button>
      </div>
      
        <div class="box-body">
        <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-upload">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                  <td class="text-left"><?php echo $this->language->get('Name'); ?></td>
                  <td class="text-left"><?php echo $this->language->get('Route'); ?></td>
                  <td class="text-left"><?php echo $this->language->get('Status'); ?></td>
                  <td class="text-right"><?php echo $this->language->get('Action'); ?></td>
                </tr>
              </thead>
              <tbody>
                <?php if ($crons) { ?>
                <?php foreach ($crons as $cron) { ?>
                <tr>
                  <td class="text-center"><?php if (in_array($upload['upload_id'], $selected)) { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $upload['upload_id']; ?>" checked="checked" />
                    <?php } else { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $upload['upload_id']; ?>" />
                    <?php } ?></td>
                  <td class="text-left"><?php echo $upload['name']; ?></td>
                  <td class="text-left"><?php echo $upload['filename']; ?></td>
                  <td class="text-right"><?php echo $upload['date_added']; ?></td>
                  <td class="text-right"><a href="<?php echo $upload['download']; ?>" data-toggle="tooltip" title="<?php echo $button_download; ?>" class="btn btn-info"><i class="fa fa-download"></i></a></td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                  <td class="text-center" colspan="5"><?php echo $text_no_results; ?></td>
                </tr>
                <?php } ?>
              </tbody>
              <tfoot>
                  <tr>
                      <td colspan="5"><?php echo $pagination; ?></td>
                  </tr>
              </tfoot>
            </table>
          </div>
        </form>
        
      </div>
    </div>
  </div>
  <script type="text/javascript"><!--
      docReady(function () { 
$('#button-filter').on('click', function() {
	url = 'index.php?p=tool/upload&token=<?php echo $token; ?>';
	
	var filter_name = $('input[name=\'filter_name\']').val();
	
	if (filter_name) {
		url += '&filter_name=' + encodeURIComponent(filter_name);
	}
	
	var filter_filename = $('input[name=\'filter_filename\']').val();
	
	if (filter_filename) {
		url += '&filter_filename=' + encodeURIComponent(filter_filename);
	}
	
	var filter_date_added = $('input[name=\'filter_date_added\']').val();
	
	if (filter_date_added) {
		url += '&filter_date_added=' + encodeURIComponent(filter_date_added);
	}

	location = url;
});
$('.date').datetimepicker({
	pickTime: false
});
});
//--></script></div>
<?php echo $footer; ?>