<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>
<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-list"></i> Custom Seo Urls</h3>
            <div class="box-tools">
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i></button>

            </div>
        </div>


        <div class="box-body">
            <div class="table-responsive" id="seourl_table_div">
         <?php include(__DIR__ . '/seourl_table.phtml'); ?>
            </div>
        </div>

</section>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Custom SEO URL</h4>
            </div>
            <div class="modal-body">
                <div id="addnew" class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Current Query</label>
                        <div class="col-sm-9">
                            <input type="text" name="query" class="form-control" value="" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">SEO URL</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon3"><?php echo HTTP_CATALOG; ?></span>
                                <input type="text" class="form-control" name="keyword" value="" />
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="addit()">Save changes</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function deleteit(id) {
            if (confirm("Confirm Deletion"))
                location.href = "index.php?p=tool/seourl/delete&url_alias_id=" + id + "&token=<?php echo $_GET['token']; ?>";
        }
        function addit() {
            $.post("index.php?p=tool/seourl/add&token=<?php echo $_GET['token']; ?>", $('#addnew input'), function (data) {
                location.reload();
            });
        }

        docReady(function() { 
            $(document).on("click", "#seourl_table_div .pagination a", function(e) { 
                e.preventDefault();
                $('#seourl_table_div').load($(this).attr('href'));
            });
        });

    </script>
    <?php echo $footer; ?>
