<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_form; ?></h3>
            <div class="box-tools pull-right">
                <button type="submit" form="form-todo" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a> 
            </div>
        </div>
        <div class="box-body">

            <div class="col-sm-6">
                <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-todo" class="form-horizontal">
                    <div class="form-group <?php if ($is_description_required) { ?>required<?php } ?>">
                        <label class="col-sm-3 control-label" for="input-description"><span data-toggle="tooltip" title="<?php echo $help_description; ?>"><?php echo $entry_description; ?></span></label>
                        <div class="col-sm-9">
                            <textarea name="description" rows="5" placeholder="<?php echo $entry_description; ?>" id="input-description" class="form-control"><?php echo $description; ?></textarea>
                            <?php if ($error_description) { ?>
                                <div class="text-danger"><?php echo $error_description; ?></div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label"><?php echo $entry_priority; ?></label>
                        <div class="col-sm-9">
                            <label class="radio-inline control-label">
                                <input type="radio" name="priority" value="1" <?php echo $priority == "1" ? 'checked="checked"' : ''; ?>/>
                                <?php echo $text_priority_1; ?>
                            </label>
                            <label class="radio-inline control-label">
                                <input type="radio" name="priority" value="2" <?php echo $priority == "2" ? 'checked="checked"' : ''; ?>/>
                                <?php echo $text_priority_2; ?>
                            </label>
                            <label class="radio-inline control-label">
                                <input type="radio" name="priority" value="3" <?php echo $priority == "3" ? 'checked="checked"' : ''; ?>/>
                                <?php echo $text_priority_3; ?>
                            </label>
                            <label class="radio-inline control-label">
                                <input type="radio" name="priority" value="4" <?php echo $priority == "4" ? 'checked="checked"' : ''; ?>/>
                                <?php echo $text_priority_4; ?>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="input-deadline"><span data-toggle="tooltip" title="<?php echo $help_deadline; ?>"><?php echo $entry_deadline; ?></span></label>
                        <div class="col-sm-9">
                            <div class="input-group date">
                                <input type="text" name="deadline" value="<?php echo $deadline; ?>" data-format="YYYY-MM-DD" placeholder="<?php echo $entry_deadline; ?>" id="input-deadline" class="form-control" />
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button"><i class="fa fa-calendar"></i></button>
                                </span>
                            </div>
                            <?php if ($error_deadline) { ?>
                                <div class="text-danger"><?php echo $error_deadline; ?></div>
                            <?php } ?>
                        </div>
                    </div>
                    <?php if ($is_edit) { ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $entry_action; ?></label>
                            <div class="col-sm-9">
                                <?php foreach ($status_action as $action_status => $action_labels) { ?>
                                    <label class="radio-inline control-label">
                                        <input type="radio" name="status" data-was-checked="0" data-was-clicked="0" value="<?php echo $action_status ?>" <?php echo $status == $action_status ? 'checked="checked"' : ''; ?> />
                                        <span data-toggle="tooltip" title="<?php echo $action_labels['help']; ?>"><?php echo $action_labels['text']; ?></span>
                                    </label>
                                <?php } ?>
                                <?php if ($can_suspend) { ?>
                                    <label class="checkbox-inline control-label" style="margin-left: 8px" id="label-suspended">
                                        <input type="hidden" name="onhold" value="0">
                                        <input type="checkbox" id="input-suspended" name="onhold" value="1" <?php echo empty($onhold) ? '' : 'checked="checked"'; ?>>
                                        <span data-toggle="tooltip" title="<?php echo $help_suspended_form; ?>"><?php echo $entry_suspended_form ?></span>
                                    </label>
                                <?php } ?>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="input-contractor"><span data-toggle="tooltip" title="<?php echo $is_author ? $help_contractor_id_a : $help_contractor_id_c; ?>"><?php echo $entry_contractor_id; ?></span></label>
                        <div class="col-sm-9">
                            <input type="text" name="contractor" value="<?php echo $contractor; ?>" placeholder="<?php echo $entry_contractor_id; ?>" id="input-contractor" class="form-control" />
                            <input type="hidden" name="contractor_id" value="<?php echo $contractor_id; ?>" />
                            <?php if ($error_contractor_id) { ?>
                                <div class="text-danger"><?php echo $error_contractor_id; ?></div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="input-author"><?php echo $entry_author_id; ?></label>
                        <div class="col-sm-<?php echo $is_edit ? 4 : 9; ?>">
                            <input type="text" name="author" value="<?php echo $author; ?>" placeholder="<?php echo $entry_author_id; ?>" id="input-author" class="form-control" disabled="disabled" />
                            <input type="hidden" name="author_id" value="<?php echo $author_id; ?>" />
                            <input type="hidden" name="author" value="<?php echo $author; ?>" />
                        </div>
                        <?php if ($is_edit) { ?>
                            <label class="col-sm-2 control-label" for="input-current-status"><?php echo $entry_queue; ?></label>
                            <div class="col-sm-3">
                                <input type="text" name="current_status" value="<?php echo $queue; ?>" id="input-current-status" class="form-control" disabled="disabled" />
                            </div>
                        <?php } ?>
                    </div>
                </form>
            </div>
            <div class="col-sm-6"><?php
                if ($is_edit) {
                    echo '<h3>' . $text_logview_header . '</h3>';
                    echo $log;
                }
                ?>
            </div>
        </div>
    </div>
</div>
</div>
<script type="text/javascript">
<!--
    docReady(function () {
        $('.date').datetimepicker({
            pickTime: false
        });

        $('input[name=\'status\']').click(function (obj) {
            if ($(this).prop("data-was-checked") && $(this).prop("data-was-clicked")) {
                $(this).prop("data-was-checked", 0);
                $(this).prop("data-was-clicked", 0);
                $(this).prop("checked", false);
            } else {
                $(this).prop("data-was-clicked", 1);
            }
        });

        $('input[name=\'status\']').change(function (obj) {
            $('input[name=\'status\']').prop("data-was-checked", 0);
            $(this).prop("data-was-checked", 1);
        });

// Contractor
        $('input[name=\'contractor\']').autoinput({
            'source': function (request, response) {
                $.ajax({
                    url: 'index.php?p=tool/todo/user_autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request),
                    dataType: 'json',
                    success: function (json) {
                        json.unshift({
                            'user_id': 0,
                            'name': '<?php echo $text_none; ?>'
                        });
                        response($.map(json, function (item) {
                            return {
                                label: item['name'],
                                value: item['user_id']
                            }
                        }));
                    }
                });
            },
            'select': function (item) {
                $('input[name=\'contractor\']').val(item['label']);
                $('input[name=\'contractor_id\']').val(item['value']);
            }
        });
    });
-->
</script>
<?php echo $footer; ?>