<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title><?php echo $text_email_subject;?></title>
</head>
<body style="width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;">
<table cellpadding="0" cellspacing="0" border="0" id="backgroundTable" style="border-collapse:collapse;width:100%">
	<tr>
		<td valign="top"> 
    		<table cellpadding="0" cellspacing="0" border="0" align="center" style="border-collapse:collapse;max-width: 600px">
    			<tr>
    				<td valign="top">
    <p style="font-style:italic;"><?php echo sprintf($text_email_title, $firstname, $lastname); ?></p>
    <p><?php echo sprintf($text_email_content, $url); ?></p>
    <p style="background-color:#DDDDDD;"><?php echo $description; ?></p>
    <p style="font-style:italic;"><?php echo sprintf($text_email_signature,$shopname); ?></p>
    				</td>
    			</tr>
    		</table>
		</td>
	</tr>
</table>  
</body>
</html>