<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>.

<!-- Main content -->
<section class="content">


    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>

            <div class="box-tools pull-right">
                <button type="submit" form="form-google-analytics" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save "></i> </button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i> </a>

            </div>
        </div>

        <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-google-analytics" class="form-horizontal">
                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $text_signup; ?>
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-code"><?php echo $entry_code; ?></label>
                    <div class="col-sm-10">
                        <textarea name="google_analytics_code" rows="5" placeholder="<?php echo $entry_code; ?>" id="input-code" class="form-control"><?php echo $google_analytics_code; ?></textarea>
                        <?php if ($error_code) { ?>
                            <div class="text-danger"><?php echo $error_code; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="google_analytics_status" id="input-status" class="form-control">
                            <?php if ($google_analytics_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?> 