<div class="widget contact-widget">

    <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" class="form-horizontal" id="contact-module-form">
        <fieldset>
            <h3><span><?php echo $text_contact; ?></span></h3>
            <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_name; ?></label>
                <div class="col-sm-10">
                    <input type="text" name="name" value="<?php echo $name; ?>" id="input-name" class="form-control" />

                </div>
            </div>
            <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-email"><?php echo $entry_email; ?></label>
                <div class="col-sm-10">
                    <input type="text" name="email" value="<?php echo $email; ?>" id="input-email" class="form-control" />

                </div>
            </div>
            <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-enquiry"><?php echo $entry_enquiry; ?></label>
                <div class="col-sm-10">
                    <textarea name="enquiry" rows="10" id="input-enquiry" class="form-control"><?php echo $enquiry; ?></textarea>

                </div>
            </div>
            <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-captcha"><?php echo $entry_captcha; ?></label>
                <div class="col-sm-10">
                    <div class="input-group ">
                        <input type="text" name="captcha" id="input-captcha" class="form-control" />
                        <span class="input-group-addon input-captcha" ><img src="index.php?p=common/captcha" alt="" id="captcha" /></span>
                        <span class="input-group-btn" ><button id="img_cap_reload" type="button" class="btn btn-default"><i class="fa fa-refresh"></i></button></span>

                    </div>
                </div>
            </div>

            <?php foreach ($custom_fields as $custom_field) { ?>
                <?php if ($custom_field['location'] == 'contact') { ?>
                    <?php if ($custom_field['type'] == 'select') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <select name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control">
                                    <option value=""><?php echo $text_select; ?></option>
                                    <?php foreach ($custom_field['custom_field_value'] as $custom_field_value) { ?>
                                        <?php if (isset($contact_custom_field[$custom_field['custom_field_id']]) && $custom_field_value['custom_field_value_id'] == $contact_custom_field[$custom_field['custom_field_id']]) { ?>
                                            <option value="<?php echo $custom_field_value['custom_field_value_id']; ?>" selected="selected"><?php echo $custom_field_value['name']; ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $custom_field_value['custom_field_value_id']; ?>"><?php echo $custom_field_value['name']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'radio') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <div>
                                    <?php foreach ($custom_field['custom_field_value'] as $custom_field_value) { ?>
                                        <div class="radio">
                                            <?php if (isset($contact_custom_field[$custom_field['custom_field_id']]) && $custom_field_value['custom_field_value_id'] == $contact_custom_field[$custom_field['custom_field_id']]) { ?>
                                                <label>
                                                    <input type="radio" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" checked="checked" />
                                                    <?php echo $custom_field_value['name']; ?></label>
                                            <?php } else { ?>
                                                <label>
                                                    <input type="radio" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" />
                                                    <?php echo $custom_field_value['name']; ?></label>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'checkbox') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <div>
                                    <?php foreach ($custom_field['custom_field_value'] as $custom_field_value) { ?>
                                        <div class="checkbox">
                                            <?php if (isset($contact_custom_field[$custom_field['custom_field_id']]) && in_array($custom_field_value['custom_field_value_id'], $contact_custom_field[$custom_field['custom_field_id']])) { ?>
                                                <label>
                                                    <input type="checkbox" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>][]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" checked="checked" />
                                                    <?php echo $custom_field_value['name']; ?></label>
                                            <?php } else { ?>
                                                <label>
                                                    <input type="checkbox" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>][]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" />
                                                    <?php echo $custom_field_value['name']; ?></label>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'text') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($contact_custom_field[$custom_field['custom_field_id']]) ? $contact_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />

                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'textarea') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <textarea name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" rows="5" placeholder="<?php echo $custom_field['name']; ?>" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control"><?php echo (isset($contact_custom_field[$custom_field['custom_field_id']]) ? $contact_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?></textarea>

                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'file') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <button type="button" id="button-custom-field<?php echo $custom_field['custom_field_id']; ?>" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-default"><i class="fa fa-upload"></i> <?php echo $button_upload; ?></button>
                                <input type="hidden" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($contact_custom_field[$custom_field['custom_field_id']]) ? $contact_custom_field[$custom_field['custom_field_id']] : ''); ?>" />

                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'date') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <div class="input-group date">
                                    <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($contact_custom_field[$custom_field['custom_field_id']]) ? $contact_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="YYYY-MM-DD" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                    </span></div>

                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'time') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <div class="input-group time">
                                    <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($contact_custom_field[$custom_field['custom_field_id']]) ? $contact_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="HH:mm" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                    </span></div>

                            </div>
                        </div>
                    <?php } ?>
                    <?php if ($custom_field['type'] == 'datetime') { ?>
                        <div class="form-group<?php echo ($custom_field['required'] ? ' required' : ''); ?> custom-field" data-sort="<?php echo $custom_field['sort_order']; ?>">
                            <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                            <div class="col-sm-10">
                                <div class="input-group datetime">
                                    <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($contact_custom_field[$custom_field['custom_field_id']]) ? $contact_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="YYYY-MM-DD HH:mm" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                    </span></div>

                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } ?>

        </fieldset>
        <div class="buttons clearfix">
            <div class="pull-right">
                <input class="btn btn-primary" type="submit" value="<?php echo $button_submit; ?>" />
            </div>
        </div>
    </form>
</div>

<script type="text/javascript"><!--
    docReady(function () {

        $('#contact-module-form').submit(function (form) {
            $('#contact-module-form').find('.text-danger').remove();
            $.post('index.php?p=module/contact/submit', $('#contact-module-form').serialize(), function (res) {
                if (res.error != undefined) {
                    $.each(res.error, function (i, j) {
                        if (i == "custom_field") {
                            $.each(j, function (ii, jj) {
                                console.log($('#input-custom-field-' + ii));
                                $('#input-custom-field' + ii).closest('.form-group > div').append('<span class="text-danger">' + jj + '</span>');
                            });
                        } else {
                            $('[name="' + i + '"]').closest('.form-group > div').append('<span class="text-danger">' + j + '</span>');
                        }

                    });
                }
                if (res.success != undefined) {
                    $('#contact-module-form').slideUp();
                    $('#contact-module-form').after('<div class="alert alert-success">' + res.success + '</div>');
                }
            }, 'json');
            return false;
        });

        function sortOurFields() {
// Sort the custom fields
            $('.form-group[data-sort]').detach().each(function () {
                if ($(this).attr('data-sort') >= 0 && $(this).attr('data-sort') <= $('.form-group').length) {
                    $('.form-group').eq($(this).attr('data-sort')).before(this);
                }

                if ($(this).attr('data-sort') > $('.form-group').length) {
                    $('.form-group:last').after(this);
                }

                if ($(this).attr('data-sort') < -$('.form-group').length) {
                    $('.form-group:first').before(this);
                }
            });
            $('button[id^=\'button-custom-field\']').on('click', function () {
                var node = this;
                $('#form-upload').remove();
                $('body').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="file" /></form>');
                $('#form-upload input[name=\'file\']').trigger('click');
                if (typeof timer != 'undefined') {
                    clearInterval(timer);
                }

                timer = setInterval(function () {
                    if ($('#form-upload input[name=\'file\']').val() != '') {
                        clearInterval(timer);
                        $.ajax({
                            url: 'index.php?p=tool/upload',
                            type: 'post',
                            dataType: 'json',
                            data: new FormData($('#form-upload')[0]),
                            cache: false,
                            contentType: false,
                            processData: false,
                            beforeSend: function () {
                                $(node).button('loading');
                            },
                            complete: function () {
                                $(node).button('reset');
                            },
                            success: function (json) {
                                $(node).parent().find('.text-danger').remove();
                                if (json['error']) {
                                    $(node).parent().find('input').after('<div class="text-danger">' + json['error'] + '</div>');
                                }

                                if (json['success']) {
                                    alert(json['success']);
                                    $(node).parent().find('input').attr('value', json['code']);
                                }
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                            }
                        });
                    }
                }, 500);
            });

            $('.date').datetimepicker({
                pickTime: false
            });
            $('.datetime').datetimepicker({
                pickDate: true,
                pickTime: true
            });
            $('.time').datetimepicker({
                pickDate: false
            });

        }

        sortOurFields();

    });
//--></script>