<div class="widget menu-widget menu-<?php echo $setting['menu_group_id']; ?>" id="module-menu-<?php echo $setting['menu_group_id']; ?>">

    <div class="navmenu navmenu-default" role="navigation">
        <ul class="nav navbar-nav">
            <?php if ($menu_items): ?>
                <?php foreach ($menu_items as $item): ?>
                    <?php if (!empty($item['children'])): ?>
                        <li class="dropdown"><a href="<?php echo $item['link']; ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $item['title']; ?></a>
                            <ul class="dropdown-menu">
                                <?php foreach ($item['children'] as $child): ?>
                                    <?php if (!empty($child['children'])): ?>
                                        <li class="dropdown"><a href="<?php echo $child['link']; ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $child['title']; ?></a>
                                            <ul class="dropdown-menu">
                                                <?php foreach ($child['children'] as $subchild): ?>
                                                    <li><a href="<?php echo $subchild['link']; ?>"><?php echo $subchild['title']; ?></a></li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </li>
                                    <?php else: ?>
                                        <li><a href="<?php echo $child['link']; ?>"><?php echo $child['title']; ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li><a href="<?php echo $item['link']; ?>"><?php echo $item['title']; ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>
</div>