<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
      <div class="box-header">
        <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
         <div class="box-tools pull-right">
               <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-success"><i class="fa fa-plus"></i></a>
        <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger" onclick="confirmDelete('<?php echo $text_confirm; ?>', '', function() { $('#form-order-status').submit(); });""><i class="fa fa-trash-o"></i></button>
            </div>
      </div>
      <div class="box-body">
        <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-order-status">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                  <th class="text-left"><?php if ($sort == 'name') { ?>
                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                    <?php } ?></th>
                  <th class="text-right"><?php echo $column_action; ?></th>
                </tr>
              </thead>
              <tbody>
                <?php if ($order_statuses) { ?>
                <?php foreach ($order_statuses as $order_status) { ?>
                <tr>
                  <td class="text-center"><?php if (in_array($order_status['order_status_id'], $selected)) { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $order_status['order_status_id']; ?>" checked="checked" />
                    <?php } else { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $order_status['order_status_id']; ?>" />
                    <?php } ?></td>
                  <td class="text-left"><?php echo $order_status['name']; ?></td>
                  <td class="text-right"><a href="<?php echo $order_status['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                  <td class="text-center" colspan="3"><?php echo $text_no_results; ?></td>
                </tr>
                <?php } ?>
              </tbody>
              <tfoot>
                  <tr><td colspan="3"><?php echo $pagination; ?></td></tr>
              </tfoot>
            </table>
          </div>
        </form>
      </div>
    </div>
  </section>
<?php echo $footer; ?> 