<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_form; ?></h3>
            <div class="box-tools pull-right">
                <button type="submit" form="form-tax-rate" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-primary"><i class="fa fa-save"></i></button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a></div>

        </div>
        <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-tax-rate" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="name" value="<?php echo $name; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                        <?php if ($error_name) { ?>
                            <div class="text-danger"><?php echo $error_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-rate"><?php echo $entry_rate; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="rate" value="<?php echo $rate; ?>" placeholder="<?php echo $entry_rate; ?>" id="input-rate" class="form-control" />
                        <?php if ($error_rate) { ?>
                            <div class="text-danger"><?php echo $error_rate; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-type"><?php echo $entry_type; ?></label>
                    <div class="col-sm-10">
                        <select name="type" id="input-type" class="form-control">
                            <?php if ($type == 'P') { ?>
                                <option value="P" selected="selected"><?php echo $text_percent; ?></option>
                            <?php } else { ?>
                                <option value="P"><?php echo $text_percent; ?></option>
                            <?php } ?>
                            <?php if ($type == 'F') { ?>
                                <option value="F" selected="selected"><?php echo $text_amount; ?></option>
                            <?php } else { ?>
                                <option value="F"><?php echo $text_amount; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label"><?php echo $entry_customer_group; ?></label>
                    <div class="col-sm-10">
                        <div class="scrollbox">
                            <ul class="list-group">
                        <?php foreach ($customer_groups as $customer_group) { ?>
                                <li class="list-group-item">
                            <div class="checkbox">
                                <label>
                                    <?php if (in_array($customer_group['customer_group_id'], $tax_rate_customer_group)) { ?>
                                        <input type="checkbox" name="tax_rate_customer_group[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />
                                        <?php echo $customer_group['name']; ?>
                                    <?php } else { ?>
                                        <input type="checkbox" name="tax_rate_customer_group[]" value="<?php echo $customer_group['customer_group_id']; ?>" />
                                        <?php echo $customer_group['name']; ?>
                                    <?php } ?>
                                </label>
                            </div>
                                </li>
                        <?php } ?>
                            </ul>
                        </div>
                         <a onclick="$(this).parent().find(':checkbox').prop('checked', 'checked');" class="btn btn-sm">Select All</a> / 
                                    <a class="btn btn-sm" onclick="$(this).parent().find(':checkbox').prop('checked',false);">Unselect All</a>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-geo-zone"><?php echo $entry_geo_zone; ?></label>
                    <div class="col-sm-10">
                        <select name="geo_zone_id" id="input-geo-zone" class="form-control">
                            <?php foreach ($geo_zones as $geo_zone) { ?>
                                <?php if ($geo_zone['geo_zone_id'] == $geo_zone_id) { ?>
                                    <option value="<?php echo $geo_zone['geo_zone_id']; ?>" selected="selected"><?php echo $geo_zone['name']; ?></option>
                                <?php } else { ?>
                                    <option value="<?php echo $geo_zone['geo_zone_id']; ?>"><?php echo $geo_zone['name']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
<?php echo $footer; ?>