<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-success"><i class="fa fa-plus"></i></a>
                <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger" onclick="confirmDelete('<?php echo $text_confirm; ?>', '', function () {
                    $('#form-tax-class').submit();
                });""><i class="fa fa-trash-o"></i></button>
            </div>
        </div>
        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-tax-class">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                                <th class="text-left"><?php if ($sort == 'title') { ?>
                                        <a href="<?php echo $sort_title; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_title; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_title; ?>"><?php echo $column_title; ?></a>
                                    <?php } ?></th>
                                <th class="text-right"><?php echo $column_action; ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($tax_classes) { ?>
                                <?php foreach ($tax_classes as $tax_class) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($tax_class['tax_class_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $tax_class['tax_class_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $tax_class['tax_class_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $tax_class['title']; ?></td>
                                        <td class="text-right"><a href="<?php echo $tax_class['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="3"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr><td colspan="3"><?php echo $pagination; ?></td></tr>
                        </tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>
<?php echo $footer; ?>