<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
      <div class="box-header">
        <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
         <div class="box-tools pull-right">
               <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-success"><i class="fa fa-plus"></i></a>
        <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger" onclick="confirmDelete('<?php echo $text_confirm; ?>', '', function() { $('#form-tax-rate').submit(); });""><i class="fa fa-trash-o"></i></button>
            </div>
      </div>
      <div class="box-body">
          
        <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-tax-rate">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                    <th style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                  <th class="text-left"><?php if ($sort == 'tr.name') { ?>
                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                    <?php } ?></th>
                  <th class="text-right"><?php if ($sort == 'tr.rate') { ?>
                    <a href="<?php echo $sort_rate; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_rate; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_rate; ?>"><?php echo $column_rate; ?></a>
                    <?php } ?></th>
                  <th class="text-left"><?php if ($sort == 'tr.type') { ?>
                    <a href="<?php echo $sort_type; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_type; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_type; ?>"><?php echo $column_type; ?></a>
                    <?php } ?></th>
                  <th class="text-left"><?php if ($sort == 'gz.name') { ?>
                    <a href="<?php echo $sort_geo_zone; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_geo_zone; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_geo_zone; ?>"><?php echo $column_geo_zone; ?></a>
                    <?php } ?></th>
                  <th class="text-left"><?php if ($sort == 'tr.date_added') { ?>
                    <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                    <?php } ?></th>
                  <th class="text-left"><?php if ($sort == 'tr.date_modified') { ?>
                    <a href="<?php echo $sort_date_modified; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_modified; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_date_modified; ?>"><?php echo $column_date_modified; ?></a>
                    <?php } ?></th>
                  <th class="text-right"><?php echo $column_action; ?></th>
                </tr>
              </thead>
              <tbody>
                <?php if ($tax_rates) { ?>
                <?php foreach ($tax_rates as $tax_rate) { ?>
                <tr>
                  <td class="text-center"><?php if (in_array($tax_rate['tax_rate_id'], $selected)) { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $tax_rate['tax_rate_id']; ?>" checked="checked" />
                    <?php } else { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $tax_rate['tax_rate_id']; ?>" />
                    <?php } ?></td>
                  <td class="text-left"><?php echo $tax_rate['name']; ?></td>
                  <td class="text-right"><?php echo $tax_rate['rate']; ?></td>
                  <td class="text-left"><?php echo $tax_rate['type']; ?></td>
                  <td class="text-left"><?php echo $tax_rate['geo_zone']; ?></td>
                  <td class="text-left"><?php echo $tax_rate['date_added']; ?></td>
                  <td class="text-left"><?php echo $tax_rate['date_modified']; ?></td>
                  <td class="text-right"><a href="<?php echo $tax_rate['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                  <td class="text-center" colspan="9"><?php echo $text_no_results; ?></td>
                </tr>
                <?php } ?>
              </tbody>
              <tfoot>
                  <tr><td colspan="9"><?php echo $pagination; ?></td></tr>
              </tfoot>
            </table>
          </div>
        </form>
        
      </div>
    </div>
</section>
<?php echo $footer; ?>