<footer id="footer">
    <div class="container footer">
        <div class="row">

            <div class="col-sm-4">
            </div>

            <div class="col-sm-4">
            </div>

            <div class="col-sm-4">
            </div>

        </div><!-- end row -->
    </div><!-- end container -->

    <div class="copyrights">
        <div class="container">
            <div class="row">

                <div class="col-sm-12">
                    <p class="pull-left"><?php echo DATE("Y"); ?> &copy; All Rights reserved.</p>

                </div>
                <div class="col-sm-12 text-right">
                <small>Powered by <a href="http://omnihost.co.nz">CoreCMS</a></small>
                </div>

            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end copyrights -->
</footer>
<!-- end footer -->

<!--[if lt IE 9]>
<script src="view/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="view/plugins/jquery/jquery-migrate-1.2.1.min.js"></script>
<script src="view/plugins/jquery/jquery.placeholder.js"></script>
<![endif]-->
<!--[if (gte IE 9) | (!IE)]><!-->
<script src="view/plugins/jquery/jquery-2.1.4.min.js"></script>
<!--<![endif]-->
<script src="view/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- Custom JS -->
<!-- THE ABOVE TAG IS REPLACED WITH ANY JS SCRIPTS THAT ARE REQUESTED!!!! -->
<script src="view/plugins/main.js"></script>
<script>
<?php echo $google_analytics; ?>
</script>
</body>
</html>