<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $heading_title; ?></h2>
        <?php if (!empty($breadcrumbs)): ?>
            <ul class="pull-right breadcrumb">
                <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                    <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?>">
                <?php echo $content_top; ?>
                <h3 class="heading"><?php echo $heading_title; ?></h3>
                <?php echo $text_message; ?>
                <div class="buttons">
                    <div class="pull-right"><a href="<?php echo $continue; ?>" class="btn btn-primary"><?php echo $button_continue; ?></a></div>
                </div>
                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>