<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>


<!-- Main content -->
<section class="content">

  <div class="error-page">
            <h2 class="headline text-red"> 401</h2>
            <div class="error-content">
              <h3><i class="fa fa-warning text-red"></i> <?php echo $heading_title; ?></h3>
              <p><?php echo $text_permission; ?> </p>
             
            </div><!-- /.error-content -->
          </div><!-- /.error-page -->


</section><!-- /.content -->

<?php echo $footer; ?>