<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $heading_title; ?></h3>
            <div class="box-tools">
                <button id="button-send" data-loading-text="<?php echo $text_loading; ?>" data-toggle="tooltip" title="<?php echo $button_send; ?>" class="btn btn-success" onclick="startSend();"><i class="fa fa-envelope"></i></button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a>
            </div>
        </div>
        <div class="box-body">
            <form class="form-horizontal" id="newsletter-form">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-to"><?php echo $entry_to; ?></label>
                    <div class="col-sm-10">
                        <select name="to" id="input-to" class="form-control">

                            <option value="customer_all"><?php echo $text_customer_all; ?></option>
                            <option value="customer_group"><?php echo $text_customer_group; ?></option>
                            <option value="customer"><?php echo $text_customer; ?></option>
                        </select>
                    </div>
                </div>
                <div class="form-group" id="not-newsletter">

                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="override_permission" value="1"> <?php echo $text_override_permissions; ?>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group to" id="to-customer-group">
                    <label class="col-sm-2 control-label" for="input-customer-group"><?php echo $entry_customer_group; ?></label>
                    <div class="col-sm-10">
                        <select name="customer_group_id" id="input-customer-group" class="form-control">
                            <?php foreach ($customer_groups as $customer_group) { ?>
                                <option value="<?php echo $customer_group['customer_group_id']; ?>"><?php echo $customer_group['name']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group to" id="to-customer">
                    <label class="col-sm-2 control-label" for="input-customer"><span data-toggle="tooltip" title="<?php echo $help_customer; ?>"><?php echo $entry_customer; ?></span></label>
                    <div class="col-sm-10">
                        <input type="text" name="customers" value="" placeholder="<?php echo $entry_customer; ?>" id="input-customer" class="form-control" />
                        <div id="customer" class="well well-sm" style="height: 150px; overflow: auto;"></div>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-subject"><?php echo $entry_subject; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="subject" value="" placeholder="<?php echo $entry_subject; ?>" id="input-subject" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-preheader"><?php echo $entry_preheader; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="preheader" value="" placeholder="<?php echo $entry_preheader; ?>" id="input-preheader" class="form-control" />
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-message"><?php echo $entry_message; ?></label>
                    <div class="col-sm-10">
                        <?php echo wysiwyg("input_message", "message"); ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript"><!--
    docReady(function () {
        $('select[name=\'to\']').on('change', function () {
            $('.to').hide();

            if (this.value == 'newsletter') {
                $('#not-newsletter').hide();
            } else {
                $('#not-newsletter').show();
            }

            $('#to-' + this.value.replace('_', '-')).show();
        });

        $('select[name=\'to\']').trigger('change');

        $('input[name=\'customers\']').autoinput({
            'source': function (request, response) {
                $.ajax({
                    url: 'index.php?p=sale/customer/autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request),
                    dataType: 'json',
                    success: function (json) {
                        response($.map(json, function (item) {
                            return {
                                label: item['name'],
                                value: item['customer_id']
                            }
                        }));
                    }
                });
            },
            'select': function (item) {
                $('input[name=\'customers\']').val('');

                $('#customer' + item['value']).remove();
                $('#customer').append('<div class="list-group-item" id="customer' + item['value'] + '"><div class="input-group"><span class="input-group-btn"><button class="btn btn-default btn-minus-circle" type="button"><i class="fa fa-minus-circle text-danger"></i></button></span><span class="form-control">' + item['label'] + '</span><input type="hidden" name="customer[]" value="' + item['value'] + '" /></div></div>');
            }
        });
        $('#customer').delegate('.fa-minus-circle,.btn-minus-circle', 'click', function () {
            $(this).closest('.list-group-item').remove();
        });



        /** This is CKEDITOR -- if you change editors this might need updating! ? */
        try {
            CKEDITOR.on('instanceReady', function (ev) {
                /** USeless outlook does not use css for image sizing, so lets put the old fashioned tags in for the silly program **/
                ev.editor.dataProcessor.htmlFilter.addRules(
                        {
                            elements:
                                    {
                                        $: function (element) {
                                            // Output dimensions of images as width and height
                                            if (element.name == 'img') {

                                                var style = element.attributes.style;

                                                if (style) {
                                                    // Get the width from the style.
                                                    var match = /(?:^|\s)width\s*:\s*(\d+)px/i.exec(style),
                                                            width = match && match[1];

                                                    var match = /(?:^|\s)max-width\s*:\s*(\d+)px/i.exec(style),
                                                            mwidth = match && match[1];

                                                    // Get the height from the style.
                                                    match = /(?:^|\s)height\s*:\s*(\d+)px/i.exec(style);
                                                    var height = match && match[1];

                                                    if (width) {
                                                        element.attributes.style = element.attributes.style.replace(/(?:^|\s)width\s*:\s*(\d+)px;?/i, '');
                                                        element.attributes.width = width;
                                                    }

                                                    if (mwidth && (mwidth < width || !width)) {
                                                        element.attributes.style = element.attributes.style.replace(/(?:^|\s)width\s*:\s*(\d+)px;?/i, '');
                                                        element.attributes.width = mwidth;
                                                    }


                                                    if (height) {
                                                        element.attributes.style = element.attributes.style.replace(/(?:^|\s)height\s*:\s*(\d+)px;?/i, '');
                                                        element.attributes.height = height;
                                                    }
                                                }
                                            }



                                            if (!element.attributes.style)
                                                delete element.attributes.style;

                                            return element;
                                        }
                                    }
                        });
            });

            CKEDITOR.on('dialogDefinition', function (event) {
                var editor = event.editor;
                var dialogDefinition = event.data.definition;
                console.log(event.editor);
                var dialogName = event.data.name;

                if (dialogName === 'table') {
                    var infoTab = dialogDefinition.getContents('info');
                    var cellSpacing = infoTab.get('txtCellSpace');
                    cellSpacing['default'] = "0";
                    var cellPadding = infoTab.get('txtCellPad');
                    cellPadding['default'] = "0";
                    var border = infoTab.get('txtBorder');
                    border['default'] = "0";
                }

                var tabCount = dialogDefinition.contents.length;
            });

        } catch (err) {
            //not a ckeditor
        }


    });
    function startSend() {
        send('index.php?p=marketing/contact/send&token=<?php echo $token; ?>');
    }

    function send(url) {
        try {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        } catch (err) {
        }

        $.ajax({
            url: url,
            type: 'post',
            data: $('#newsletter-form').serialize(),
            dataType: 'json',
            beforeSend: function () {
                $('#button-send').button('loading');
            },
            complete: function () {
                $('#button-send').button('reset');
            },
            success: function (json) {
                $('.alert, .text-danger').remove();

                if (json['error']) {
                    if (json['error']['warning']) {
                        $('section.content').prepend('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error']['warning'] + '</div>');
                    }

                    if (json['error']['subject']) {
                        $('input[name=\'subject\']').after('<div class="text-danger">' + json['error']['subject'] + '</div>');
                    }

                    if (json['error']['message']) {
                        $('textarea[name=\'message\']').parent().append('<div class="text-danger">' + json['error']['message'] + '</div>');
                    }
                }


                if (json['success']) {
                    $('section.content').prepend('<div class="alert alert-success"><i class="fa fa-check-circle"></i>  ' + json['success'] + '</div>');
                    if (json['next']) {
                        send(json['next']);
                    }
                }

            }

        });
    }


//--></script>
<?php echo $footer; ?>