<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>
<section class="content">
    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $heading_title; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_insert; ?>"><i class="fa fa-plus"></i></a> 
                <a onclick="confirmDelete('Are you Sure?', '', function () {$('#form').submit();});" class="btn btn-danger" data-toggle="tooltip" title="<?php echo $button_delete; ?>"><i class="fa fa-trash-o"></i></a> 

            </div>
        </div>
        <div class="box-body">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td width="1" style="text-align: center;"><input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></td>
                                <td class="left"><?php echo $column_name; ?></td>
                                <td class="right"><?php echo $column_status; ?></td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($categories) { ?>
                                <?php foreach ($categories as $category) { ?>
                                    <tr>
                                        <td style="text-align: center;"><?php if ($category['selected']) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $category['form_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $category['form_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="left"><a target="_blank" href="<?php echo HTTP_CATALOG ?>index.php?p=marketing/form&form_id=<?php echo $category['form_id'] ?>"><?php echo $category['title']; ?></a></td>
                                        <td class="right"><?php echo $category['status'] ? 'Enabled' : 'Disabled'; ?></td>
                                        <td class="text-right"><?php foreach ($category['action'] as $action) { ?>

                                                <a href="<?php echo $action['href']; ?>" data-toggle="tooltip"  title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a>

                                            <?php } ?></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="4"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>
<!-- TAB SUPPORT -->
<script language="javascript" type="text/javascript">
    function resizeIframe(obj) {
        obj.style.height = obj.contentWindow.document.body.offsetHeight + 'px';
    }
</script>

<script type="text/javascript">
    docReady(function () {
        $('.tab-box').live('click', function () {
            var id = $(this).attr('id');
            $('.tab-box').removeClass('active');
            $(this).addClass('active');
            $('.tab').css('display', 'none');
            $('#t_' + id).fadeIn('fast');
        });
    });
</script>
<style type="text/css">
    iframe{
        width: 99.8%;
        height: 425px;
        border: 1px solid silver;
        border-radius: 0 0 5px 5px;
    }
</style>
<?php echo $footer; ?>