<?php echo $header; ?>
<div id="content">
    <div class="content-header">

        <h1><?php echo $heading_title; ?></h1>
        <ol class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ol>

    </div>
    <div class="container-fluid">
        <div class="container-fluid">

            <?php if ($error_warning) { ?>
                <div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> <?php echo $error_warning; ?>
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            <?php } ?>
            <?php if ($success) { ?>
                <div class="alert alert-success"><i class="fa fa-check-circle"></i> <?php echo $success; ?>
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            <?php } ?>
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $heading_title; ?></h3>
                    <div class="box-tools">
                        <a href="<?php echo $insert; ?>" class="btn btn-primary"><?php echo $button_insert; ?></a>&nbsp;&nbsp;<a onclick="$('#form').submit();" class="btn btn-primary"><?php echo $button_delete; ?></a> &nbsp;&nbsp;

                    </div>
                </div>
                <div class="box-body">
                    <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <td width="1" style="text-align: center;"><input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></td>
                                        <td class="left"><?php echo $column_name; ?></td>
                                        <td class="right"><?php echo $column_sort_order; ?></td>
                                        <td class="right"><?php echo $column_action; ?></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($categories) { ?>
                                        <?php foreach ($categories as $category) { ?>
                                            <tr>
                                                <td style="text-align: center;"><?php if ($category['selected']) { ?>
                                                        <input type="checkbox" name="selected[]" value="<?php echo $category['form_id']; ?>" checked="checked" />
                                                    <?php } else { ?>
                                                        <input type="checkbox" name="selected[]" value="<?php echo $category['form_id']; ?>" />
                                                    <?php } ?></td>
                                                <td class="left"><a target="_blank" href="<?php echo HTTP_CATALOG ?>index.php?p=marketing/form&form_id=<?php echo $category['form_id'] ?>"><?php echo $category['title']; ?></a></td>
                                                <td class="right"><?php echo $category['status'] ? 'Enabled' : 'Disabled'; ?></td>
                                                <td class="right"><?php foreach ($category['action'] as $action) { ?>

                                                        <a href="<?php echo $action['href']; ?>" data-toggle="tooltip"  class="btn btn-primary"><i class="fa fa-pencil"></i></a>

                                                    <?php } ?></td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else { ?>
                                        <tr>
                                            <td class="text-center" colspan="4"><?php echo $text_no_results; ?></td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- TAB SUPPORT -->
<script language="javascript" type="text/javascript">
    function resizeIframe(obj) {
        obj.style.height = obj.contentWindow.document.body.offsetHeight + 'px';
    }
</script>

<script type="text/javascript">
    docReady(function () {
        $('.tab-box').live('click', function () {
            var id = $(this).attr('id');
            $('.tab-box').removeClass('active');
            $(this).addClass('active');
            $('.tab').css('display', 'none');
            $('#t_' + id).fadeIn('fast');
        });
    });
</script>
<style type="text/css">
    iframe{
        width: 99.8%;
        height: 425px;
        border: 1px solid silver;
        border-radius: 0 0 5px 5px;
    }
</style>
<?php echo $footer; ?>