<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-app"><i class="fa fa-plus text-primary"></i> <?php echo $button_add; ?></a>
            <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-app" onclick="confirm('<?php echo $text_confirm; ?>') ? $('#form-marketing').submit() : false;"><i class="fa fa-trash-o text-danger"></i><?php echo $button_delete; ?></button>
        </div>
        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-marketing">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>

                                <th class="text-left"><a href="<?php echo $sort_name; ?>" <?php if ($sort == 'name') : ?>class="<?php echo strtolower($order); ?>"<?php endif; ?>><?php echo $column_name; ?></a></th>
                                <th class="text-left"><a href="<?php echo $sort_subject; ?>" <?php if ($sort == 'subject') : ?>class="<?php echo strtolower($order); ?>"<?php endif; ?>><?php echo $column_subject; ?></a></th>
                                <th class="text-left"><a href="<?php echo $sort_date; ?>" <?php if ($sort == 'create_date') : ?>class="<?php echo strtolower($order); ?>"<?php endif; ?>><?php echo $column_created; ?></a></th>
                                <th class="text-center"><?php echo $column_sent_to; ?></th>
                                <th class="text-center"><?php echo $column_opened_by; ?></th>
                                <th class="text-center"><?php echo $column_unsubscribed; ?></th>
                                <th class="text-center"><?php echo $column_bounced; ?></th>
                                <th class="text-right"><?php echo $column_action; ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($newsletters) { ?>
                                <?php foreach ($newsletters as $newsletter) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($newsletter['newsletter_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $newsletter['newsletter_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $newsletter['newsletter_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $newsletter['name']; ?></td>
                                        <td class="text-left"><?php echo $newsletter['subject']; ?></td>
                                        <td class="text-left"><?php echo $newsletter['create_date']; ?></td>
                                         <td class="text-center"><?php echo $newsletter['sends']; ?></td>
                                         <td class="text-center"><?php echo $newsletter['opens']; ?></td>
                                         <td class="text-center"><?php echo $newsletter['unsubscribes']; ?></td>
                                         <td class="text-center"><?php echo $newsletter['bounces']; ?></td>
                                        <td class="text-right">
                                            <a href="<?php echo $newsletter['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                            <a href="<?php echo $newsletter['send']; ?>" data-toggle="tooltip" title="Send Newsletter" class="btn btn-success"><i class="fa fa-send"></i></a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="5"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot><tr><td colspan=5><?php echo $pagination; ?></td></tr></tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>

<?php echo $footer; ?>