<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-subscriber" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i><?php echo $button_cancel; ?></a></div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-subscriber" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-group_name"><?php echo $entry_campaign_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="campaign_name" value="<?php echo $campaign_name; ?>" placeholder="<?php echo $entry_campaign_name; ?>" id="input-campaign_name" class="form-control" />
                        <?php if ($error_campaign_name) { ?>
                            <div class="text-danger"><?php echo $error_campaign_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                

            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?>