<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-subscriber" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i><?php echo $button_cancel; ?></a></div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-subscriber" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-group_name"><?php echo $entry_campaign_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="campaign_name" value="<?php echo $campaign_name; ?>" placeholder="<?php echo $entry_campaign_name; ?>" id="input-campaign_name" class="form-control" />
                        <?php if ($error_campaign_name) { ?>
                            <div class="text-danger"><?php echo $error_campaign_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <fieldset>
                    <legend>Campaign Newsletters</legend>
                    <div class="table-responsive">
                        <table id="campaign_table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Newsletter</th>
                                    <th>Send When</th>
                                    <th class="text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($campaign_newsletter as $i => $nl): ?>
                                    <tr>
                                        <td><?php echo $nl['name']; ?></td>
                                        <td><?php echo $nl['send_time']; ?> days after join</td>
                                        <td class="text-right"><button type="button" class="btn btn-danger btn-remove"><i class="fa fa-times"></i></button>
                                            <input type="hidden" name="campaign_newsletter[<?php echo $i; ?>][newsletter_id]" value="<?php echo $nl['newsletter_id']; ?>">
                                            <input type="hidden" name="campaign_newsletter[<?php echo $i; ?>][send_time]" value="<?php echo $nl['send_time']; ?>">
                                        </td>
                                    </tr>
                                <?php endforeach; ?>

                            </tbody>
                        </table>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Add Newsletter To Campaign</legend>
                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="input-group_name">Select Newsletter</label>
                        <div class="col-sm-5">
                            <input type="hidden" name="nlidinput" value="" id="nlidinput">
                            <input data-target="nlidinput" data-limit="1" data-url="<?php echo $this->url->link('marketing/newsletter/newsletter/autocomplete', 'token=' . $this->request->get['token']); ?>" type="autocomplete" name="nlidinput_display" id="nlidinput_display" class="form-control"  />
                        </div>
                    </div>
                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="input-group_name">Delay Days</label>
                        <div class="col-sm-3">
                            <input  type="number" min="0" class="form-control" step="1" id="nldelay" value="1" />
                        </div>
                        <div class="col-sm-3 ">
                            <button type="button" id="addnltolist" class="btn btn-primary">Add Newsletter</button>
                        </div>
                    </div>
                </fieldset>



            </form>
        </div>
    </div>
</section>
<script>
    <?php $i = count($campaign_newsletter);
    $i++;
    ?>
        var nlcounter = <?php echo $i; ?>;
    docReady(function () {
        $(document).on("click", "#addnltolist", function () {
            var nlid = $('#nlidinput').val();
            var nlname = $('#nlidinput_display').val();
            var delay = $('#nldelay').val();
            if (nlid != '') {
                var tbl = '<tr><td>' + nlname + '</td><td>' + delay + ' days after join</td><td class="text-right"><button type="button" class="btn btn-danger btn-remove"><i class="fa fa-times"></i></button>';
                tbl += '<input type="hidden" name="campaign_newsletter[' + nlcounter +'][newsletter_id]" value="' + nlid + '">';
                tbl += '<input type="hidden" name="campaign_newsletter[' + nlcounter +'][send_time]" value="' + delay + '">';
                tbl += '</td></tr>';
                $('#campaign_table thead').append(tbl);
                nlcounter++;
            }
        });

        $(document).on("click", "#campaign_table .btn-remove", function () {

            $(this).closest('tr').remove();
            return false;
        });
    });
</script>
<?php echo $footer; ?>