<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-app"><i class="fa fa-plus text-primary"></i> <?php echo $button_add; ?></a>
            <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-app" onclick="confirm('<?php echo $text_confirm; ?>') ? $('#form-marketing').submit() : false;"><i class="fa fa-trash-o text-danger"></i><?php echo $button_delete; ?></button>
        </div>
        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-marketing">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>

                                <td class="text-left"><?php echo $column_group_name; ?></td>
                                
                                <td class="text-left"><?php echo $column_public; ?></td>
                                <td class="text-center"><?php echo $column_group_count; ?></td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($groups) { ?>
                                <?php foreach ($groups as $group) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($group['group_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $group['group_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $group['group_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $group['group_name']; ?></td>
                                        <td class="text-left"><?php echo $group['public']; ?></td>
                                        <td class="text-center"><?php echo $group['member_count']; ?></td>
                                        <td class="text-right"><a href="<?php echo $group['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="5"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot><tr><td colspan=5><?php echo $pagination; ?></td></tr></tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>

<?php echo $footer; ?>