<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-subscriber" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i><?php echo $button_cancel; ?></a></div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-subscriber" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-group_name"><?php echo $entry_group_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="group_name" value="<?php echo $group_name; ?>" placeholder="<?php echo $entry_group_name; ?>" id="input-group_name" class="form-control" />
                        <?php if ($error_group_name) { ?>
                            <div class="text-danger"><?php echo $error_group_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_public; ?></label>
                    <div class="col-sm-10">
                         <select name="public" id="input-status" class="form-control">
                            <?php if ($public) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>


            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?>