<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">

        <div class="box-body">
            <h3>Pending Sends</h3>
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Newsletter</th>
                            <th>Subject</th>
                            <th>Start Send</th>
                            <th>Progress</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($pending_sends): ?>
                            <?php foreach ($pending_sends as $send): ?>
                                <tr>
                                    <td><?php echo $send['name']; ?></td>
                                    <td><?php echo $send['subject']; ?></td>
                                    <td><?php echo $send['start_date']; ?></td>
                                    <td><?php echo $send['progress']; ?></td>
                                    <td><?php if (time() < $send['start_time']): ?>CANCEL<?php endif; ?></td>
                                </tr>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr><td colspan="5" class="text-center"><?php echo $text_no_results; ?></td></tr>
                        <?php endif; ?>
                    </tbody>

                </table>
            </div>
            <hr>
            <h3>Recent Members</h3>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Email Address</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Join Date</th>
                        <th>Number Sent</th>
                        <th>Number Opened</th>
                        <th>Number Bounces</th>
                        <th>Groups</th>
                        <th>Campaigns</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($recent_members): ?>
                        <?php foreach ($recent_members as $member): ?>
                            <tr>
                                <td><?php echo $member['email']; ?></td>
                                <td><?php echo $member['firstname']; ?></td>
                                <td><?php echo $member['lastname']; ?></td>
                                <td><?php echo $member['date_created']; ?></td>
                                <td class="text-center"><?php echo $member['send_count']; ?></td>
                                 <td class="text-center"><?php echo $member['open_count']; ?></td>
                                  <td class="text-center"><?php echo $member['bounce_count']; ?></td>
                                <td><?php foreach($member['group_id'] as $i=> $group): ?><?php echo $i ? ', ':'';?> <?php echo 
                                $group['group_name'];?><?php endforeach; ?></td>
                                <td><?php foreach($member['campaign_id'] as $i=> $cmp): ?><?php echo $i ? ', ':'';?> <?php echo 
                                $cmp['campaign_name'];?><?php endforeach; ?></td>
                         
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr><td colspan="9" class="text-center"><?php echo $text_no_results; ?></td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
            <hr>
            <h3>Recent Sends</h3>
            <table>
                <tr><td colspan="4" class="text-center"><?php echo $text_no_results; ?></td></tr>
            </table>
        </div>
    </div>
</section>

<?php echo $footer; ?>