<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-subscriber" data-toggle="tooltip" title="<?php echo $button_send; ?>" class="btn btn-app"><i class="fa fa-send text-success"></i> <?php echo $button_send; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i><?php echo $button_cancel; ?></a></div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-subscriber" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-4 control-label" for="input-group_name"><?php echo $entry_group_send_to; ?></label>
                    <div class="col-sm-7">
                        <?php foreach ($groups as $group_id => $group): ?>
                            <div class="checkbox">
                                <label>
                                    <?php if (in_array($group_id, $group_ids)): ?>
                                        <input type="checkbox" name="group_ids[]" value="<?php echo $group_id; ?>" selected />
                                    <?php else: ?>
                                        <input type="checkbox" name="group_ids[]" value="<?php echo $group_id; ?>" />

                                    <?php endif; ?>
                                    <?php echo $group; ?>
                                </label>
                            </div>
                        <?php endforeach; ?>
                        <?php if ($error_group_send_to) { ?>
                            <br /><div class="text-danger"><?php echo $error_group_send_to; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label" for="input-status"><?php echo $entry_dont_send_again; ?></label>
                    <div class="col-sm-7">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="dont_send_duplicate" value="1" <?php echo ($dont_send_duplicate) ? 'selected' : ''; ?>>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="input-status"><?php echo $entry_schedule ?></label>
                    <div class="col-sm-7">

                        <input type="text" name="send_later" value="<?php echo $send_later; ?>" class="form-control datetime">

                    </div>
                </div>


            </form>
        </div>
    </div>
</section>
<script>
    docReady(function () {
        $('.datetime').datetimepicker({
            pickTime: true,
            toolbarPlacement: 'top',
            sideBySide: true,
            format: "Do MMM YYYY, h:mm a",
            minDate: moment("<?php echo DATE("Y-m-d h:i a"); ?>"),
            defaultDate: moment("<?php echo (!empty($send_later)) ? DATE("Y-m-d g:i a", strtotime($send_later)) : DATE("Y-m-d g:i a"); ?>")
        });
    });
</script>
<?php echo $footer; ?>