<?php echo $header; ?>
<?php include(__DIR__ . '/../../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-subscriber" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i><?php echo $button_cancel; ?></a></div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-subscriber" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-fname"><?php echo $entry_firstname; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="firstname" value="<?php echo $firstname; ?>" placeholder="<?php echo $entry_firstname; ?>" id="input-fname" class="form-control" />
                        <?php if ($error_firstname) { ?>
                            <div class="text-danger"><?php echo $error_firstname; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-lname"><?php echo $entry_lastname; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="lastname" value="<?php echo $lastname; ?>" placeholder="<?php echo $entry_lastname; ?>" id="input-lname" class="form-control" />
                        <?php if ($error_lastname) { ?>
                            <div class="text-danger"><?php echo $error_lastname; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-email"><?php echo $entry_email; ?></label>
                    <div class="col-sm-10">
                        <input type="email" name="email" value="<?php echo $email; ?>" placeholder="<?php echo $entry_email; ?>" id="input-email" class="form-control" />
                        <?php if ($error_email) { ?>
                            <div class="text-danger"><?php echo $error_email; ?></div>
                        <?php } ?>
                    </div>
                </div>
                
                <div class="row">
                <div class="col-sm-6">
                    <label class="col-xs-12 " for="input-groups"><?php echo $entry_groups; ?></label>
                    <div class="col-xs-12">
                       <?php echo formfield($groups_field); ?>
                                           
                    </div>
                </div>
                <div class="col-sm-6 ">
                    <label class="col-xs-12 " for="input-campaigns"><?php echo $entry_campaigns; ?></label>
                     <div class="col-xs-12">
                       <?php echo formfield($campaigns_field); ?>
                                           
                    </div>
                </div>
                </div>
                
                
            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?>