<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-google-hangouts" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i> <?php echo $button_cancel; ?></a>
        </div>


        <form  action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-google-maps" class="form-horizontal">
            <div class="box-body">

                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="name" value="<?php echo $name; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                        <?php if ($error_name) { ?>
                            <div class="text-danger"><?php echo $error_name; ?></div>
                        <?php } ?>
                    </div>
                </div>

                <div class="form-group required">
                    <label class="col-sm-2 control-label"><?php echo $entry_ids; ?></label>
                    <div class="col-sm-10">
                        <div class="scrollbox">
                            <ul class="list-group">
                                 <?php foreach ($gmaps as $gmap) : ?>
                                <li class="list-group-item">
                               
                                        <?php if (is_array($ids) and in_array($gmap['id'], $ids)) { ?>
                                            <input type="checkbox" name="ids[]" value="<?php echo $gmap['id']; ?>" checked="checked" />
                                            <?php echo $gmap['alias']; ?>
                                        <?php } else { ?>
                                            <input type="checkbox" name="ids[]" value="<?php echo $gmap['id']; ?>" />
                                            <?php echo  $gmap['alias']; ?>
                                        <?php } ?>
                                    
                                </li>
                                <?php endforeach; ?>
                            </ul>
                            </div>
                        <a onclick="$(this).parent().find(':checkbox').prop('checked', true);"><?php echo $text_select_all; ?></a> / <a onclick="$(this).parent().find(':checkbox').prop('checked', false);"><?php echo $text_unselect_all; ?></a>
                        <?php if ($error_ids) { ?>
                            <div class="text-danger"><?php echo $error_ids; ?></div>
                        <?php } ?>
                    </div>
                </div>

                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-width"><?php echo $entry_width; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="width" value="<?php echo $width; ?>" placeholder="<?php echo $placeholder_width; ?>" id="input-width" class="form-control" />
                        <?php if ($error_width) { ?>
                            <div class="text-danger"><?php echo $error_width; ?></div>
                        <?php } ?>
                    </div>
                </div>

                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-height"><?php echo $entry_height; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="height" value="<?php echo $height; ?>" placeholder="<?php echo $placeholder_height; ?>" id="input-height" class="form-control" />
                        <?php if ($error_height) { ?>
                            <div class="text-danger"><?php echo $error_height; ?></div>
                        <?php } ?>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-zoom"><?php echo $entry_zoom; ?></label>
                    <div class="col-sm-10">
                        <select name="zoom" id="input-zoom" class="form-control">
                            <option value="20" <?php if ($zoom == '20') { ?>selected="selected"<?php } ?>>20</option>
                            <option value="19" <?php if ($zoom == '19') { ?>selected="selected"<?php } ?>>19</option>
                            <option value="18" <?php if ($zoom == '18') { ?>selected="selected"<?php } ?>>18</option>
                            <option value="17" <?php if ($zoom == '17') { ?>selected="selected"<?php } ?>>17</option>
                            <option value="16" <?php if ($zoom == '16') { ?>selected="selected"<?php } ?>>16</option>
                            <option value="15" <?php if ($zoom == '15') { ?>selected="selected"<?php } ?>>15</option>
                            <option value="14" <?php if ($zoom == '14') { ?>selected="selected"<?php } ?>>14</option>
                            <option value="13" <?php if ($zoom == '13') { ?>selected="selected"<?php } ?>>13</option>
                            <option value="12" <?php if ($zoom == '12') { ?>selected="selected"<?php } ?>>12</option>
                            <option value="11" <?php if ($zoom == '11') { ?>selected="selected"<?php } ?>>11</option>
                            <option value="10" <?php if ($zoom == '10') { ?>selected="selected"<?php } ?>>10</option>
                            <option value="9" <?php if ($zoom == '9') { ?>selected="selected"<?php } ?>>09</option>
                            <option value="8" <?php if ($zoom == '8') { ?>selected="selected"<?php } ?>>08</option>
                            <option value="7" <?php if ($zoom == '7') { ?>selected="selected"<?php } ?>>07</option>
                            <option value="6" <?php if ($zoom == '6') { ?>selected="selected"<?php } ?>>06</option>
                            <option value="5" <?php if ($zoom == '5') { ?>selected="selected"<?php } ?>>05</option>
                            <option value="4" <?php if ($zoom == '4') { ?>selected="selected"<?php } ?>>04</option>
                            <option value="3" <?php if ($zoom == '3') { ?>selected="selected"<?php } ?>>03</option>
                            <option value="2" <?php if ($zoom == '2') { ?>selected="selected"<?php } ?>>02</option>
                            <option value="1" <?php if ($zoom == '1') { ?>selected="selected"<?php } ?>>01</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-zoom"><?php echo $entry_maptype; ?></label>
                    <div class="col-sm-10">
                        <select name="maptype" id="input-maptype" class="form-control">
                            <option value="ROADMAP" <?php if ($maptype == 'ROADMAP') { ?>selected="selected"<?php } ?>>ROADMAP</option>
                            <option value="SATELLITE" <?php if ($maptype == 'SATELLITE') { ?>selected="selected"<?php } ?>>SATELLITE</option>
                            <option value="HYBRID" <?php if ($maptype == 'HYBRID') { ?>selected="selected"<?php } ?>>HYBRID</option>
                            <option value="TERRAIN" <?php if ($maptype == 'TERRAIN') { ?>selected="selected"<?php } ?>>TERRAIN</option>
                        </select>
                    </div>
                </div>

                <?php $module['maptype'] = 'ROADMAP'; //todo: ?>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-zoom"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="status" class="form-control">
                            <?php if ($status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>


            </div>

        </form>

    </div>

</section>


<?php echo $footer; ?>