
<?php if ($has_comments) { ?>
    <div class="comments">
        <p>
            <a style="cursor:pointer;" data-toggle="collapse" data-target="#commentsarea" class="small"><?php echo $text_comments; ?><small id="comment_number">( <?php echo $comment_count; ?> )</small> / <?php echo $text_write; ?></a></p>
    </div>

    <div id="commentsarea" class="collapse">
        <h5><?php echo $text_comments; ?> <small id="comment_number">( <?php echo $comment_count; ?> )</small></h5>
        <hr />
        <div id="commentbox"></div>
        <?php if ($can_comment) { ?>
            <hr />
            <form id="comment_form" class="form-horizontal">
                <div class="post-comment clearfix">
                    <h6><?php echo $text_write; ?></h6>
                    <div class="form-group required">
                        <label class="control-label col-sm-3" for="input-name"><?php echo $entry_name; ?></label>
                        <div class="col-sm-9">
                            <input type="text" name="name" value="" id="input-name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group required">
                        <label class="control-label col-sm-3" for="input-review"><?php echo $entry_review; ?></label>
                        <div class="col-sm-9">

                            <textarea name="text" rows="5" id="input-review" class="form-control"></textarea>
                            <div class="help-block"><?php echo $text_note; ?></div>
                        </div>
                    </div>
                    <div class="form-group required">
                        <label class="control-label col-sm-3" for="input-captcha"><?php echo $entry_captcha; ?></label>
                        <div class="col-sm-9">

                            <input type="text" name="captcha" value="" id="input-captcha" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3"><img src="index.php?p=common/captcha" alt="" id="captcha" /><br /><a href="#nogo" id="img_cap_reload">Change</a> </div>
                    </div>
                    <div class="buttons">
                        <div class="pull-right">
                            <button type="button" id="button-comment" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary"><?php echo $button_place_comment; ?></button>
                        </div>
                    </div>
                </div>
            </form>
        <?php } else { ?>
            <?php echo $text_login; ?>
        <?php } ?>

    </div>
    <script type="text/javascript">
        docReady(function () {
            var comment_number = <?php echo $comment_count; ?>;

            $('#img_cap_reload').on("click", function () {
                $('#captcha').attr('src', '?p=common/captcha&ts=' + new Date().getTime());
                return false;
            });

            $('#commentbox').delegate('.pagination a', 'click', function (e) {
                e.preventDefault();

                $('#commentbox').hide();

                $('#commentbox').load(this.href);

                $('#commentbox').fadeIn('slow');
            });

            $('#commentbox').load('index.php?p=cms/page/comment&page_id=<?php echo $ams_page_id; ?>');

            $('#button-comment').on('click', function () {
                $.ajax({
                    url: 'index.php?p=cms/page/write&page_id=<?php echo $ams_page_id; ?>',
                    type: 'post',
                    dataType: 'json',
                    data: 'name=' + encodeURIComponent($('input[name=\'name\']').val()) + '&text=' + encodeURIComponent($('textarea[name=\'text\']').val()) + '&rating=' + encodeURIComponent($('input[name=\'rating\']:checked').val() ? $('input[name=\'rating\']:checked').val() : '') + '&captcha=' + encodeURIComponent($('input[name=\'captcha\']').val()),
                    beforeSend: function () {
                        $('#button-comment').button('loading');
                    },
                    complete: function () {
                        $('#button-comment').button('reset');
                        $('#captcha').attr('src', 'index.php?p=common/captcha#' + new Date().getTime());
                        $('input[name=\'captcha\']').val('');
                    },
                    success: function (json) {
                        $('.alert-success, .alert-danger, label.text-danger').remove();

                        if (json['error']) {
                            if (json['error']['captcha']) {
                                $('input[name=\'captcha\']').after('<label class="text-danger">' + json['error']['captcha'] + '</label>');
                                $('input[name=\'captcha\']').focus();
                            }
                            if (json['error']['text']) {
                                $('textarea[name=\'text\']').after('<label class="text-danger">' + json['error']['text'] + '</label>');
                                $('textarea[name=\'text\']').focus();
                            }
                            if (json['error']['name']) {
                                $('input[name=\'name\']').after('<label class="text-danger">' + json['error']['name'] + '</label>');
                                $('input[name=\'name\']').focus();
                            }
                            //    $('#commentbox').after('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error'] + '</div>');
                        }

                        if (json['success']) {
                            $('#commentbox').after('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + '</div>');

                            $('input[name=\'name\']').val('');
                            $('textarea[name=\'text\']').val('');
                            $('input[name=\'rating\']:checked').prop('checked', false);
                            $('input[name=\'captcha\']').val('');

    <?php if ($comment_auto_approve) { ?>
                                $('#commentbox').load('index.php?p=cms/page/comment&page_id=<?php echo $ams_page_id; ?>');
                                comment_number++;
                                $('#comment_number').text(comment_number.toString());
    <?php } ?>
                        }
                    }
                });
            });

        });

    </script>
<?php } ?>
