<!-- Custom CSS -->
<!-- Custom JS -->
<div class="gallery-<?php echo $gallery['banner_id']; ?>">



    <div id="gallery-page">
        <div class="sec-title">
            <h3>Gallery</h3>
            <h2><?php echo $gallery['name']; ?></h2>
        </div>

        [gallery name="<?php echo $gallery['name']; ?>" banner_id="<?php echo $gallery['banner_id']; ?>"][/gallery]



    </div>
</div><!-- end col-sm-12 -->
<script>
    
     
    

</script>
