<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $gallery['name']; ?></h2>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="gallery-<?php echo $gallery['banner_id']; ?>">
                <?php echo $content_top; ?>


                <div id="gallery-page">
                    <div class="sec-title">
                        <h3>Gallery</h3>
                        <h2><?php echo $gallery['name']; ?></h2>
                    </div>

                    [gallery name="<?php echo $gallery['name']; ?>" banner_id="<?php echo $gallery['banner_id']; ?>"][/gallery]



                </div>
                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>

<?php echo $footer; ?>