<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $page['name']; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?>">
                <?php echo $content_top; ?>
         
                <div class="row">
                    <div class="col-md-4 col-sm-8 col-xs-10 col-md-offset-4 col-sm-offset-2 col-xs-offset-1">
                        <h4>Password Required to access this page</h4>
                        <?php if(!empty($page['auth_page_password_error'])): ?>
                        <div class="alert alert-danger"><strong>Sorry,</strong> Incorrect password provided</div>
                        <?php endif; ?>
                        <form method="post" class="form-horizontal">
                            <div class="form-group">
                                <label class="col-sm-12"></label>
                                <div class="col-sm-12">
                                    <input type="password" name="auth_page_password" placeholder="Page Password" class="form-control" />
                                </div>
                            </div>
                            <div class="text-center"><button type="submit" class="btn btn-primary">Access Page</button></div>
                        </form>
                    </div>
                </div>
                
                
                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>