<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $page['name']; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?> ams-page-<?php echo $page['id']; ?> page-<?php echo $page['slug']; ?>">
                <?php echo $content_top; ?>
                <?php echo $page['content']; ?>
                <?php if ($page['downloads']): ?>
                    <h3><?php echo $heading_download; ?></h3>
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td class="text-left"><?php echo $column_name; ?></td>
                                <td class="text-left"><?php echo $column_size; ?></td>
                                <td class="text-left"><?php echo $column_date_added; ?></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($page['downloads'] as $download) { ?>
                                <tr>
                                    <td class="text-left"><?php echo $download['name']; ?></td>
                                    <td class="text-left"><?php echo $download['size']; ?></td>
                                    <td class="text-left"><?php echo DATE("F j, Y", strtotime($download['date_modified'])); ?></td>
                                    <td><a href="<?php echo $download['href']; ?>" data-toggle="tooltip" title="<?php echo $button_download; ?>" class="btn btn-primary"><i class="fa fa-cloud-download"></i></a></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>


                <?php endif; ?>

                <?php if ($page['galleries']): ?>

                    <?php if (count($page['galleries']) == 1): ?>

                        <div id="gallery-page">


                            <?php $gallery = $page['galleries'][0]; ?>
                            <div class="sec-title">
                                <h3><?php echo $gallery['name']; ?></h3>
                            </div>

                            [gallery name="<?php echo $gallery['name']; ?>" banner_id="<?php echo $gallery['banner_id']; ?>"][/gallery]



                        </div>
                    <?php else: ?>
                        <div id="gallery-list" class="row">
                            <?php foreach ($page['galleries'] as $gallery): ?>
                                <div class="col-xs-6 col-sm-4 col-md-3">
                                    <a class="thumbnail inthegallery" href="<?php echo $this->url->link('cms/gallery', 'gallery_id=' . $gallery['banner_id'] . '&ref_id=' . $page['id']); ?>">
                                        <img src="<?php echo $gallery['thumb']; ?>" class="img" />
                                        <div class="caption">
                                            <?php echo $gallery['name']; ?>
                                        </div>
                                    </a>
                                </div>
                            <?php endforeach; ?>

                        </div>
                        <br class="clearfix" />

                        <div style="width:0px;height:0px;overflow:hidden;" id="thegallery">

                        </div>

                    <?php endif; ?>


                <?php endif; ?>

                <?php echo $page['comments']; ?>
                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<script>
    docReady(function () {
        $(document).on("click", ".inthegallery", function (e) {
            e.preventDefault();
            var $this = $(this);
            $this.addClass('loading');
            var href = $(this).attr('href');
            $('#thegallery').load(href, function () {
                $.each(onReadyCallbacks, function (i, callback) {
                    if (callback instanceof Function) {
                        callback();
                    }
                });
                setTimeout(function () {
                    $($('#gallery-page').find('.image-thumb').find('a')[0]).trigger("click");
                    $this.removeClass('loading');
                }, 1000);

            });
        });

    });
</script>

<?php echo $footer; ?>