<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $heading_title; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?>">
                <?php echo $content_top; ?>

                <?php if (!empty($success) && $success) { ?>
                    <div class="alert alert-success"><i class="fa fa-check-circle"></i> <?php echo $success; ?></div>
                <?php } ?>

                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="panel panel-default panel-account">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-edit"></i> <?php echo $text_my_account; ?></h3>
                            </div>
                            <div class="panel-body">
                                <ul class="list-unstyled">
                                    <li><a href="<?php echo $edit; ?>"><i class="fa fa-user"></i> <?php echo $text_edit; ?></a></li>
                                    <li><a href="<?php echo $password; ?>"><i class="fa fa-lock"></i> <?php echo $text_password; ?></a></li>
                                    <li><a href="<?php echo $newsletter; ?>"><i class="fa fa-envelope-o"></i> <?php echo $text_newsletter; ?></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>


               

                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>