<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $heading_title; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section id="login" class="content section-grey" style="background: url(view/img/pixel_weave.png) repeat;">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?>">
                <?php echo $content_top; ?>
                <?php if ($success) { ?>
                    <div class="alert alert-success"><i class="fa fa-check-circle"></i> <?php echo $success; ?></div>
                <?php } ?>
                <?php if ($error_warning) { ?>
                    <div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> <?php echo $error_warning; ?></div>
                <?php } ?>
                <div class="row">
                    <div class="col-sm-6">
                        <?php if($account_register): ?>
                        <div class="well">
                            <h4 class="heading text-center"><?php echo $text_new_customer; ?></h4>
                            <h6><?php echo $text_register; ?></h6>
                            <p><?php echo $text_register_account; ?></p>
                            <a href="<?php echo $register; ?>" class="btn btn-primary"><?php echo $button_continue; ?></a></div>
                            <?php endif; ?>
                    </div>
                    <div class="col-sm-6">
                        <div class="well">
                            <h4 class="heading text-center"><?php echo $text_returning_customer; ?></h4>

                            <h6><?php echo $text_i_am_returning_customer; ?></h6>
                            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
                                <div class="form-group">
                                    <label class="control-label" for="input-email"><?php echo $entry_email; ?></label>
                                    <input type="emaiul" name="email" value="<?php echo $email; ?>" placeholder="<?php echo $entry_email; ?>" id="input-email" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label class="control-label" for="input-password"><?php echo $entry_password; ?></label>
                                    <input type="password" name="password" value="<?php echo $password; ?>" placeholder="<?php echo $entry_password; ?>" id="input-password" class="form-control" />
                                    <a href="<?php echo $forgotten; ?>"><?php echo $text_forgotten; ?></a></div>
                                <input type="submit" value="<?php echo $button_login; ?>" class="btn btn-primary" />
                                <?php if ($redirect) { ?>
                                    <input type="hidden" name="redirect" value="<?php echo $redirect; ?>" />
                                <?php } ?>
                            </form>
                        </div>
                    </div>
                </div>
                <?php echo $content_bottom; ?>
            </div><!-- end col-4 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>

        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>
