<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h3 class="pull-left"><?php echo $heading_title; ?></h3>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?>">
                <?php echo $content_top; ?>

                <?php if ($success) { ?>
                    <div class="alert alert-success"><i class="fa fa-check-circle"></i> <?php echo $success; ?></div>
                <?php } ?>

                <h3 class="heading"><?php echo $heading_title; ?></h3>
                <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" class="form-horizontal">
                    <fieldset>
                        <legend><?php echo $text_password; ?></legend>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="input-password"><?php echo $entry_password; ?></label>
                            <div class="col-sm-10">
                                <input type="password" name="password" value="<?php echo $password; ?>" placeholder="<?php echo $entry_password; ?>" id="input-password" class="form-control" />
                                <?php if ($error_password) { ?>
                                    <div class="text-danger"><?php echo $error_password; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="input-confirm"><?php echo $entry_confirm; ?></label>
                            <div class="col-sm-10">
                                <input type="password" name="confirm" value="<?php echo $confirm; ?>" placeholder="<?php echo $entry_confirm; ?>" id="input-confirm" class="form-control" />
                                <?php if ($error_confirm) { ?>
                                    <div class="text-danger"><?php echo $error_confirm; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                    </fieldset>
                    <div class="buttons clearfix">
                        <div class="pull-left"><a href="<?php echo $back; ?>" class="btn btn-default"><?php echo $button_back; ?></a></div>
                        <div class="pull-right">
                            <input type="submit" value="<?php echo $button_continue; ?>" class="btn btn-primary" />
                        </div>
                    </div>
                </form>

                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>