<div id="empty-box">
<div class="box box-primary">
    <div class="box-header ui-sortable-handle">
        <div class="pull-right box-tools">

            <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
        </div><!-- /. tools -->

        <i class="fa fa-calendar"></i> 
        <h3 class="box-title"><?php echo $heading_title; ?></h3>
    </div>
    <div class="box-body">
Latest news to go here i think!!! ?
    </div>
</div>
</div>