<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $heading_title; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?>">
                <?php echo $content_top; ?>

                <?php if ($posts): ?>
                    <?php foreach ($posts as $post): ?>
                        <div class="row blog-category">
                            <div class="col-sm-4">
                                <?php if ($post['featured_image']): ?>
                                    <img class="img-responsive img-rounded" src="<?php echo $post['featured_image']; ?>" alt="">
                                <?php endif; ?>
                            </div>    
                            <div class="col-sm-8">
                                <h3 class="heading"><?php echo $post['name']; ?></h3>
                                <ul class="list-unstyled list-inline blog-info">
                                    <li><i class="fa fa-calendar"></i> <?php echo DATE("F d,Y", $post['date_created']); ?></li>
                                    <li><i class="fa fa-comments"></i> <a href="<?php echo $post->href; ?>#commentsarea"><?php echo $post['total_comments']; ?> Comments</a></li>
                                    <li><i class="fa fa-tags"></i> <?php foreach ($post['categories'] as $ix => $cat): ?>
                                            <?php echo ($ix) ? ', ' : ''; ?><a href="<?php echo $cat['href']; ?>"><?php echo $cat['name']; ?></a>
                                        <?php endforeach; ?></li>
                                </ul>
                                <p><?php echo substr($post['blurb'], 0, 500); ?></p>
                                <p><a class="btn btn-sm" href="<?php echo $post['href']; ?>"><i class="fa fa-location-arrow"></i> Read More</a></p>
                            </div>    
                        </div>
                    <?php endforeach; ?>
                    <?php echo $pagination->render(); ?>
                <?php else: ?>
                    <div class="row blog-category">
                        Sorry No Posts in this category
                    </div>
                <?php endif; ?>

                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>