<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $page['name']; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?> ">
                <?php echo $content_top; ?>
                <article class="post type-post">
                    <div class="entry post-inner">
                        
                        <?php if ($page['featured_image']): ?>
                            <div class="blogimage">
                                <img class="img-responsive aligncenter" src="img/<?php echo $page['featured_image']; ?>" alt="<?php htmlspecialchars($page['name'], ENT_QUOTES, 'UTF-8'); ?>" title="<?php htmlspecialchars($page['name'], ENT_QUOTES, 'UTF-8'); ?>"/>
                            </div>
                        <?php endif; ?>
                        <ul class="list-inline metadata">
                            <li><i class="fa fa-calendar"></i>  <?php echo DATE("F d,Y", $page['publish_date']); ?></li>
                            <li><i class="fa fa-user"></i> By <a class="content-color-link scrollto" href="javascript:void(0)"><?php echo $page['author']['username']; ?></a></li>
                            <li><i class="fa fa-comments"></i> <a class="content-color-link scrollto"style="cursor:pointer;" data-toggle="collapse" data-target="#commentsarea"><?php echo $comment_count; ?> Comments</a></li>
                            <li><i class="fa fa-tags"></i><?php foreach ($page['categories'] as $ix => $cat): ?>
                                            <?php echo ($ix) ? ', ' : ''; ?><a href="<?php echo $cat['href']; ?>"><?php echo $cat['name']; ?></a>
                                        <?php endforeach; ?></li>
                        </ul>
                        <div class="post-body">
                            <?php echo $page['content']; ?>
                        </div>
                    </div>
                    
                    <ul class="list-inline social-share-buttons">
                        <li><button class="btn btn-link" disabled>Share:</button></li>
                        <li><a rel="tooltip" data-title="Share By Email" class="btn email-icon" href="mailto:?subject=<?php echo htmlspecialchars($page['name']); ?>&body=<?php echo urlencode($this->url->link($this->request->get['p'], $this->request->get)); ?>"><i class="fa fa-at"></i> <span class="social-text hidden-xs">Email</span></a></li>
                        <li><a rel="tooltip" data-title="Share On Facebook" class="btn facebook-icon popup" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($this->url->link($this->request->get['p'], $this->request->get)); ?>" target="_blank"><i class="fa fa-facebook fa-lg"></i> <span class="social-text hidden-xs">Facebook</span></a></li>
                        <li><a rel="tooltip" data-title="Share on Twitter" class="btn twitter-icon popup" href="https://twitter.com/intent/tweet?text=<?php echo htmlspecialchars($page['name']); ?> <?php echo urlencode($this->url->link($this->request->get['p'], $this->request->get)); ?>" target="_blank"><i class="fa fa-twitter fa-lg"></i> <span class="social-text hidden-xs">Twitter</span></a></li>
                        <li><a rel="tooltip" data-title="Share on Google" class="btn googleplus-icon popup" href="https://plus.google.com/share?url=<?php echo urlencode($this->url->link($this->request->get['p'], $this->request->get)); ?>" target="_blank"><i class="fa fa-google-plus fa-lg"></i> <span class="social-text hidden-xs">Google</span></a></li>
                        <li><a rel="tooltip" data-title="Share on LinkedIn" class="btn linkedin-icon popup" href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo urlencode($this->url->link($this->request->get['p'], $this->request->get)); ?>&title=<?php echo htmlspecialchars($page['name']); ?>" target="_blank"><i class="fa fa-linkedin fa-lg"></i>  <span class="social-text hidden-xs">LinkedIn</span></a></li>
                        <li><a rel="tooltip" data-title="Share on Pinterest" class="btn pinterest-icon popup" href="http://pinterest.com/pin/create/button/?url=<?php echo urlencode($this->url->link($this->request->get['p'], $this->request->get)); ?>&description=<?php echo htmlspecialchars($page['name']); ?>&media=<?php echo urlencode(($page['featured_image']) ? $this->config->get('config_ssl') . 'img/' . $page['featured_image'] : 'https://www.smallbusinessamplifier.info/img/uploads/res-nb001-fs8.png'); ?>" target="_blank"><i class="fa fa-pinterest fa-lg"></i>  <span class="social-text hidden-xs">Pinterest</span></a></li>
                    </ul>

                    <?php echo $page['comments']; ?>


                </article>
                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>