<?php echo $header; ?>
<div class="breadcrumbs">
    <div class="container">
        <h2 class="pull-left"><?php echo $heading_title; ?></h2>
        <ul class="pull-right breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php echo $column_top; ?>
<section class="content">
    <div class="container">
        <div class="row">
            <?php if ($column_left): ?>
                <?php echo $column_left; ?>
            <?php endif; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div class="<?php echo $class; ?> ">
                <?php echo $content_top; ?>
                <article class="post type-post">
                    <div class="entry post-inner">
                        <h3 class="posttitle"><?php echo $page['name']; ?></h3>
                        <?php if ($page['featured_image']): ?>
                            <div class="blogimage">
                                <img class="img-responsive aligncenter" src="img/<?php echo $page['featured_image']; ?>" alt="<?php htmlspecialchars($page['name'], ENT_QUOTES, 'UTF-8'); ?>" title="<?php htmlspecialchars($page['name'], ENT_QUOTES, 'UTF-8'); ?>"/>
                            </div>
                        <?php endif; ?>
                        <ul class="list-inline metadata">
                            <li><i class="fa fa-calendar"></i>  <?php echo DATE("F d,Y", $page['publish_date']); ?></li>
                            <li><i class="fa fa-user"></i> By <a class="content-color-link" href="roy-hawker">Roy Hawker</a></li>
                            <li><i class="fa fa-comments"></i> <a class="content-color-link" href="#"><?php echo $comment_count; ?> Comments</a></li>

                        </ul>
                        <div class="post-body">
                            <?php echo $page['content']; ?>
                        </div>
                        <div class="text-center">
<div class="btn-group"><a class="btn btn-xl btn-orange show-download-modal" data-campaign-id="1" href="#">DOWNLOAD ALL 21 GAME CHANGERS NOW </a> <a class="btn btn-xl btn-orange show-download-modal" data-campaign-id="1" href="#"> <i class="fa fa- fa-cloud-download"></i> </a></div>
</div>
                    </div>
                    
                    <?php echo $page['comments']; ?>


                </article>
                <?php echo $content_bottom; ?>
            </div><!-- end col-sm-12 -->
            <?php if ($column_right): ?>
                <?php echo $column_right; ?>
            <?php endif; ?>
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<?php echo $column_bottom; ?>
<?php echo $footer; ?>