<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-setting" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-green"></i> <?php echo $button_save; ?></button>
        </div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-setting" class="form-horizontal">
                <ul id="settings-tabs" class="nav nav-tabs">
                    <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>
                    <li><a href="#tab-option" data-toggle="tab"><?php echo $tab_option; ?></a></li>
                    <li ><a href="#tab-seo" data-toggle="tab"><?php echo $tab_seo; ?></a></li>
                    <?php foreach ($tabs as $tab): ?>
                        <li><a href="#<?php echo $tab['id']; ?>" data-toggle="tab"><?php echo $tab['label']; ?></a></li>
                    <?php endforeach; ?>
                    <li><a href="#tab-mail" data-toggle="tab"><?php echo $tab_mail; ?></a></li>
                    <li><a href="#tab-ftp" data-toggle="tab"><?php echo $tab_ftp; ?></a></li>
                    <li><a href="#tab-server" data-toggle="tab"><?php echo $tab_server; ?></a></li>
                    <li><a href="#tab-google" data-toggle="tab"><?php echo $tab_google; ?></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-general">
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_name; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="config_name" value="<?php echo $config_name; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                                <?php if ($error_name) { ?>
                                    <div class="text-danger"><?php echo $error_name; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="input-email"><?php echo $entry_email; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="config_email" value="<?php echo $config_email; ?>" placeholder="<?php echo $entry_email; ?>" id="input-email" class="form-control" />
                                <?php if ($error_email) { ?>
                                    <div class="text-danger"><?php echo $error_email; ?></div>
                                <?php } ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-template"><?php echo $entry_template; ?></label>
                            <div class="col-sm-9">
                                <select name="config_template" id="input-template" class="form-control">
                                    <?php foreach ($templates as $template) { ?>
                                        <?php if ($template == $config_template) { ?>
                                            <option value="<?php echo $template; ?>" selected="selected"><?php echo $template; ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $template; ?>"><?php echo $template; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                                <br />
                                <img src="" alt="" id="template" class="img-thumbnail" style="max-height:150px;" /></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-layout"><?php echo $entry_layout; ?></label>
                            <div class="col-sm-9">
                                <select name="config_layout_id" id="input-layout" class="form-control">
                                    <?php foreach ($layouts as $layout) { ?>
                                        <?php if ($layout['layout_id'] == $config_layout_id) { ?>
                                            <option value="<?php echo $layout['layout_id']; ?>" selected="selected"><?php echo $layout['name']; ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-terms"><span data-toggle="tooltip" title="<?php echo $help_account; ?>">Site Terms & Conditions</span></label>
                            <div class="col-sm-10">
                                <select name="config_site_terms_id" id="input-terms" class="form-control">
                                    <option value="0"><?php echo $text_none; ?></option>
                                    <?php foreach ($informations as $information) { ?>
                                        <?php if ($information['ams_page_id'] == $config_site_terms_id) { ?>
                                            <option value="<?php echo $information['ams_page_id']; ?>" selected="selected"><?php echo $information['name']; ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $information['ams_page_id']; ?>"><?php echo $information['name']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-privacy"><span data-toggle="tooltip" title="<?php echo $help_account; ?>">Site Privacy Policy</span></label>
                            <div class="col-sm-10">
                                <select name="config_site_privacy_id" id="input-terms" class="form-control">
                                    <option value="0"><?php echo $text_none; ?></option>
                                    <?php foreach ($informations as $information) { ?>
                                        <?php if ($information['ams_page_id'] == $config_site_privacy_id) { ?>
                                            <option value="<?php echo $information['ams_page_id']; ?>" selected="selected"><?php echo $information['name']; ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $information['ams_page_id']; ?>"><?php echo $information['name']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-logo"><?php echo $entry_logo; ?></label>
                            <div class="col-sm-9"><a href="" id="thumb-logo" data-toggle="image" class="img-thumbnail"><img src="<?php echo $logo; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a>
                                <input type="hidden" name="config_logo" value="<?php echo $config_logo; ?>" id="input-logo" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-icon"><?php echo $entry_icon; ?></label>
                            <div class="col-sm-9"><a href="" id="thumb-icon" data-toggle="image" class="img-thumbnail"><img src="<?php echo $icon; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a>
                                <input type="hidden" name="config_icon" value="<?php echo $config_icon; ?>" id="input-icon" />
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab-option">
                        <fieldset>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-country"><?php echo $entry_country; ?></label>
                                <div class="col-sm-10">
                                    <select name="config_country_id" id="input-country" class="form-control">
                                        <?php foreach ($countries as $country) { ?>
                                            <?php if ($country['country_id'] == $config_country_id) { ?>
                                                <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-currency"><span data-toggle="tooltip" title="<?php echo $help_currency; ?>"><?php echo $entry_currency; ?></span></label>
                                <div class="col-sm-10">
                                    <select name="config_currency" id="input-currency" class="form-control">
                                        <?php foreach ($currencies as $currency) { ?>
                                            <?php if ($currency['code'] == $config_currency) { ?>
                                                <option value="<?php echo $currency['code']; ?>" selected="selected"><?php echo $currency['title']; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $currency['code']; ?>"><?php echo $currency['title']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_currency_auto; ?>"><?php echo $entry_currency_auto; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_currency_auto) { ?>
                                            <input type="radio" name="config_currency_auto" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_currency_auto" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_currency_auto) { ?>
                                            <input type="radio" name="config_currency_auto" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_currency_auto" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-catalog-limit"><span data-toggle="tooltip" title="<?php echo $help_product_limit; ?>"><?php echo $entry_product_limit; ?></span></label>
                                <div class="col-sm-10">
                                    <input type="text" name="config_product_limit" value="<?php echo $config_product_limit; ?>" placeholder="<?php echo $entry_product_limit; ?>" id="input-catalog-limit" class="form-control" />
                                    <?php if ($error_product_limit) { ?>
                                        <div class="text-danger"><?php echo $error_product_limit; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-blog-limit"><span data-toggle="tooltip" title="<?php echo $help_blog_limit; ?>"><?php echo $entry_blog_limit; ?></span></label>
                                <div class="col-sm-10">
                                    <input type="text" name="config_blog_limit" value="<?php echo $config_blog_limit; ?>" placeholder="<?php echo $entry_blog_limit; ?>" id="input-catalog-limit" class="form-control" />
                                    <?php if ($error_blog_limit) { ?>
                                        <div class="text-danger"><?php echo $error_blog_limit; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-admin-limit"><span data-toggle="tooltip" title="<?php echo $help_limit_admin; ?>"><?php echo $entry_limit_admin; ?></span></label>
                                <div class="col-sm-10">
                                    <input type="text" name="config_limit_admin" value="<?php echo $config_limit_admin; ?>" placeholder="<?php echo $entry_limit_admin; ?>" id="input-admin-limit" class="form-control" />
                                    <?php if ($error_limit_admin) { ?>
                                        <div class="text-danger"><?php echo $error_limit_admin; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Images</legend>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-image-thumb-width"><?php echo $entry_image_thumb; ?></label>
                                <div class="col-sm-10">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <input type="text" name="config_image_thumb_width" value="<?php echo $config_image_thumb_width; ?>" placeholder="<?php echo $entry_width; ?>" id="input-image-thumb-width" class="form-control" />
                                        </div>
                                        <div class="col-sm-1 text-center"> X </div>
                                        <div class="col-sm-2">
                                            <input type="text" name="config_image_thumb_height" value="<?php echo $config_image_thumb_height; ?>" placeholder="<?php echo $entry_height; ?>" class="form-control" />
                                        </div>
                                    </div>
                                    <?php if ($error_image_thumb) { ?>
                                        <div class="text-danger"><?php echo $error_image_thumb; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-image-popup-width"><?php echo $entry_image_popup; ?></label>
                                <div class="col-sm-10">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <input type="text" name="config_image_popup_width" value="<?php echo $config_image_popup_width; ?>" placeholder="<?php echo $entry_width; ?>" id="input-image-popup-width" class="form-control" />
                                        </div>
                                        <div class="col-sm-1 text-center"> X </div>
                                        <div class="col-sm-2">
                                            <input type="text" name="config_image_popup_height" value="<?php echo $config_image_popup_height; ?>" placeholder="<?php echo $entry_height; ?>" class="form-control" />
                                        </div>
                                    </div>
                                    <?php if ($error_image_popup) { ?>
                                        <div class="text-danger"><?php echo $error_image_popup; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-image-blog-category-width">Blog Category Thumb</label>
                                <div class="col-sm-10">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <input type="text" name="config_image_blogcat_width" value="<?php echo $config_image_blogcat_width; ?>" placeholder="<?php echo $entry_width; ?>" id="input-image-popup-width" class="form-control" />
                                        </div>
                                        <div class="col-sm-1 text-center"> X </div>
                                        <div class="col-sm-2">
                                            <input type="text" name="config_image_blogcat_height" value="<?php echo $config_image_blogcat_height; ?>" placeholder="<?php echo $entry_height; ?>" class="form-control" />
                                        </div>
                                    </div>
                                    <?php if ($error_image_blogcat) { ?>
                                        <div class="text-danger"><?php echo $error_image_blogcat; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_autosave; ?></legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_autosave; ?>"><?php echo $entry_autosave; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_autosave_status) { ?>
                                            <input type="radio" name="config_autosave_status" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_autosave_status" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_autosave_status) { ?>
                                            <input type="radio" name="config_autosave_status" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_autosave_status" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-autosave-time"><span data-toggle="tooltip" title="<?php echo $help_autosave_time; ?>"><?php echo $entry_autosave_time; ?></span></label>
                                <div class="col-sm-2">
                                    <input type="number"  min="0" step="1" name="config_autosave_time" value="<?php echo $config_autosave_time; ?>" placeholder="<?php echo $entry_autosave_time; ?>" id="input-autosave-time" class="form-control" />
                                    <?php if ($error_autosave_time) { ?>
                                        <div class="text-danger"><?php echo $error_autosave_time; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_review; ?></legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_review; ?>"><?php echo $entry_review; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_review_status) { ?>
                                            <input type="radio" name="config_review_status" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_review_status" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_review_status) { ?>
                                            <input type="radio" name="config_review_status" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_review_status" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_review_guest; ?>"><?php echo $entry_review_guest; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_review_guest) { ?>
                                            <input type="radio" name="config_review_guest" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_review_guest" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_review_guest) { ?>
                                            <input type="radio" name="config_review_guest" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_review_guest" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_comment_auto_approve; ?>"><?php echo $entry_comment_auto_approve; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_comment_auto_approve) { ?>
                                            <input type="radio" name="config_comment_auto_approve" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_comment_auto_approve" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_comment_auto_approve) { ?>
                                            <input type="radio" name="config_comment_auto_approve" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_comment_auto_approve" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_review_mail; ?>"><?php echo $entry_review_mail; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_review_mail) { ?>
                                            <input type="radio" name="config_review_mail" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_review_mail" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_review_mail) { ?>
                                            <input type="radio" name="config_review_mail" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_review_mail" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_account; ?></legend>


                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_account_register; ?>"><?php echo $entry_account_register; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_account_register) { ?>
                                            <input type="radio" name="config_account_register" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_account_register" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_account_register) { ?>
                                            <input type="radio" name="config_account_register" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_account_register" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-customer-group"><span data-toggle="tooltip" title="<?php echo $help_customer_group; ?>"><?php echo $entry_customer_group; ?></span></label>
                                <div class="col-sm-10">
                                    <select name="config_customer_group_id" id="input-customer-group" class="form-control">
                                        <?php foreach ($customer_groups as $customer_group) { ?>
                                            <?php if ($customer_group['customer_group_id'] == $config_customer_group_id) { ?>
                                                <option value="<?php echo $customer_group['customer_group_id']; ?>" selected="selected"><?php echo $customer_group['name']; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $customer_group['customer_group_id']; ?>"><?php echo $customer_group['name']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_customer_group_display; ?>"><?php echo $entry_customer_group_display; ?></span></label>
                                <div class="col-sm-10">
                                    <?php foreach ($customer_groups as $customer_group) { ?>
                                        <div class="checkbox">
                                            <label>
                                                <?php if (in_array($customer_group['customer_group_id'], $config_customer_group_display)) { ?>
                                                    <input type="checkbox" name="config_customer_group_display[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />
                                                    <?php echo $customer_group['name']; ?>
                                                <?php } else { ?>
                                                    <input type="checkbox" name="config_customer_group_display[]" value="<?php echo $customer_group['customer_group_id']; ?>" />
                                                    <?php echo $customer_group['name']; ?>
                                                <?php } ?>
                                            </label>
                                        </div>
                                    <?php } ?>
                                    <?php if ($error_customer_group_display) { ?>
                                        <div class="text-danger"><?php echo $error_customer_group_display; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-login-attempts"><span data-toggle="tooltip" title="<?php echo $help_login_attempts; ?>"><?php echo $entry_login_attempts; ?></span></label>
                                <div class="col-sm-10">
                                    <input type="text" name="config_login_attempts" value="<?php echo $config_login_attempts; ?>" placeholder="<?php echo $entry_login_attempts; ?>" id="input-login-attempts" class="form-control" />
                                    <?php if ($error_login_attempts) { ?>
                                        <div class="text-danger"><?php echo $error_login_attempts; ?></div>
                                    <?php } ?>                  
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-account"><span data-toggle="tooltip" title="<?php echo $help_account; ?>"><?php echo $entry_account; ?></span></label>
                                <div class="col-sm-10">
                                    <select name="config_account_id" id="input-account" class="form-control">
                                        <option value="0"><?php echo $text_none; ?></option>
                                        <?php foreach ($informations as $information) { ?>
                                            <?php if ($information['ams_page_id'] == $config_account_id) { ?>
                                                <option value="<?php echo $information['ams_page_id']; ?>" selected="selected"><?php echo $information['name']; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $information['ams_page_id']; ?>"><?php echo $information['name']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_account_mail; ?>"><?php echo $entry_account_mail; ?></span></label>
                                <div class="col-sm-10">
                                    <label class="radio-inline">
                                        <?php if ($config_account_mail) { ?>
                                            <input type="radio" name="config_account_mail" value="1" checked="checked" />
                                            <?php echo $text_yes; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_account_mail" value="1" />
                                            <?php echo $text_yes; ?>
                                        <?php } ?>
                                    </label>
                                    <label class="radio-inline">
                                        <?php if (!$config_account_mail) { ?>
                                            <input type="radio" name="config_account_mail" value="0" checked="checked" />
                                            <?php echo $text_no; ?>
                                        <?php } else { ?>
                                            <input type="radio" name="config_account_mail" value="0" />
                                            <?php echo $text_no; ?>
                                        <?php } ?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-sso"><span data-toggle="tooltip" title="<?php echo $help_sso; ?>"><?php echo $entry_sso; ?></span></label>
                                <div class="col-sm-10">
                                    <select name="config_sso_id" id="input-sso" class="form-control">
                                        <option value="0"><?php echo $text_none; ?></option>
                                        <?php foreach ($sso_users as $sso_user) { ?>
                                            <?php if ($sso_user['api_id'] == $config_sso_id) { ?>
                                                <option value="<?php echo $sso_user['api_id']; ?>" selected="selected"><?php echo $sso_user['username']; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $sso_user['api_id']; ?>"><?php echo $sso_user['username']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>

                        </fieldset>
                    </div>
                    <div class="tab-pane" id="tab-seo">
                        <fieldset>
                            <div class="form-group required">
                                <label class="col-sm-2 control-label" for="input-meta-title"><span data-toggle="tooltip" title="<?php echo $help_meta_title; ?>"><?php echo $entry_meta_title; ?></span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_meta_title" value="<?php echo $config_meta_title; ?>" placeholder="<?php echo $entry_meta_title; ?>" id="input-meta-title" class="form-control" />
                                    <?php if ($error_meta_title) { ?>
                                        <div class="text-danger"><?php echo $error_meta_title; ?></div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-meta-description"><?php echo $entry_meta_description; ?></label>
                                <div class="col-sm-9">
                                    <textarea name="config_meta_description" rows="5" placeholder="<?php echo $entry_meta_description; ?>" id="input-meta-description" class="form-control"><?php echo $config_meta_description; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-meta-keyword"><?php echo $entry_meta_keyword; ?></label>
                                <div class="col-sm-9">
                                    <textarea name="config_meta_keyword" rows="5" placeholder="<?php echo $entry_meta_keyword; ?>" id="input-meta-keyword" class="form-control"><?php echo $config_meta_keyword; ?></textarea>
                                </div>
                            </div>

                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_facebook_defaults; ?></legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-facebook_appid"><?php echo $entry_facebook_appid; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_facebook_appid" value="<?php echo $config_facebook_appid; ?>" placeholder="<?php echo $entry_facebook_appid; ?>" id="input-facebook_appid" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-facebook_ogsitename"><?php echo $entry_facebook_sitename; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_facebook_ogsitename" value="<?php echo $config_facebook_ogsitename; ?>" placeholder="<?php echo $entry_facebook_sitename; ?>" id="input-facebook_ogsitename" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-facebook_ogtitle"><?php echo $entry_facebook_title; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_facebook_ogtitle" value="<?php echo $config_facebook_ogtitle; ?>" placeholder="<?php echo $entry_facebook_title; ?>" id="input-facebook_ogtitle" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-facebook_ogdescription"><?php echo $entry_facebook_description; ?></label>
                                <div class="col-sm-9">
                                    <textarea name="config_facebook_ogdescription" rows="5" placeholder="<?php echo $entry_facebook_description; ?>" id="input-facebook_ogdescription" class="form-control"><?php echo $config_facebook_ogdescription; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-facebook_ogimage"><?php echo $entry_facebook_image; ?></label>
                                <div class="col-sm-9">
                                    <a href="#" id="thumb-fbimage" data-toggle="image" class="img-thumbnail"><img src="<?php echo $config_facebook_ogimage; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a>
                                    <input type="hidden" name="config_facebook_ogimage" value="<?php echo @$config_facebook_ogimag; ?>" id="input-facebook_ogimag" />
                                    <span><?php echo $entry_meta_ogimage_help; ?></span>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_twitter_defaults; ?></legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-twitter_card_site"><?php echo $this->language->get("Twitter @username of website"); ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_twitter_card_site" value="<?php echo @$config_twitter_card_site; ?>" placeholder="<?php echo $this->language->get("Twitter @username of website"); ?>" id="input-twitter_card_site" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-twitter_card_creator"><?php echo $this->language->get("Twitter @username of author"); ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_twitter_card_creator" value="<?php echo @$config_twitter_card_creator; ?>" placeholder="<?php echo $this->language->get("Twitter @username of author"); ?>" id="input-twitter_card_creator" class="form-control" />
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_google_defaults; ?></legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-meta-publisher"><span data-toggle="tooltip" title="<?php echo $help_meta_publisher; ?>"><?php echo $entry_meta_publisher; ?></span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_meta_publisher" value="<?php echo $config_meta_publisher; ?>" placeholder="<?php echo $entry_meta_publisher; ?>" id="input-meta-publisher" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-meta-author"><span data-toggle="tooltip" title="<?php echo $help_meta_author; ?>"><?php echo $entry_meta_author; ?></span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_meta_author" value="<?php echo $config_meta_author; ?>" placeholder="<?php echo $entry_meta_author; ?>" id="input-meta-publisher" class="form-control" />
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <?php foreach ($tabs as $tab): ?>
                        <div class="tab-pane" id="<?php echo $tab['id']; ?>">
                            <?php echo $tab['content']; ?>
                        </div>
                    <?php endforeach; ?>
                    <div class="tab-pane" id="tab-mail">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-mail-protocol"><span data-toggle="tooltip" title="<?php echo $help_mail_protocol; ?>"><?php echo $entry_mail_protocol; ?></span></label>
                            <div class="col-sm-9">
                                <select name="config_mail_protocol" id="input-mail-protocol" class="form-control">
                                    <?php if ($config_mail_protocol == 'mail') { ?>
                                        <option value="mail" selected="selected"><?php echo $text_mail; ?></option>
                                    <?php } else { ?>
                                        <option value="mail"><?php echo $text_mail; ?></option>
                                    <?php } ?>
                                    <?php if ($config_mail_protocol == 'smtp') { ?>
                                        <option value="smtp" selected="selected"><?php echo $text_smtp; ?></option>
                                    <?php } else { ?>
                                        <option value="smtp"><?php echo $text_smtp; ?></option>
                                    <?php } ?>
                                    <?php if ($config_mail_protocol == 'sendgrid') { ?>
                                        <option value="sendgrid" selected="selected">SendGrid</option>
                                    <?php } else { ?>
                                        <option value="sendgrid">SendGrid</option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-alert-email"><span data-toggle="tooltip" title="<?php echo $help_mail_alert; ?>"><?php echo $entry_mail_alert; ?></span></label>
                            <div class="col-sm-9">
                                <textarea name="config_mail_alert" rows="5" placeholder="<?php echo $entry_mail_alert; ?>" id="input-alert-email" class="form-control"><?php echo $config_mail_alert; ?></textarea>
                            </div>
                        </div>
                        <fieldset>
                            <legend><?php echo $entry_mail_parameter; ?></legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-mail-parameter"><span data-toggle="tooltip" title="<?php echo $help_mail_parameter; ?>"><?php echo $entry_mail_parameter; ?></span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_mail_parameter" value="<?php echo $config_mail_parameter; ?>" placeholder="<?php echo $entry_mail_parameter; ?>" id="input-mail-parameter" class="form-control" />
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>SendGrid Parameters</legend>
                            <div class="alert alert-info"><?php echo $help_sendgrid_key; ?></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-sendgrid-key"><?php echo $entry_sendgrid_key; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_sendgrid_key" value="<?php echo $config_sendgrid_key; ?>" placeholder="<?php echo $entry_sendgrid_key; ?>" id="input-sendgrid-key" class="form-control" />
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>SMTP Parameters</legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-mail-smtp-hostname"><span data-toggle="tooltip" title="<?php echo $help_mail_smtp_hostname; ?>"><?php echo $entry_mail_smtp_hostname; ?></span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_mail_smtp_hostname" value="<?php echo $config_mail_smtp_hostname; ?>" placeholder="<?php echo $entry_mail_smtp_hostname; ?>" id="input-mail-smtp-hostname" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-mail-smtp-username"><?php echo $entry_mail_smtp_username; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_mail_smtp_username" value="<?php echo $config_mail_smtp_username; ?>" placeholder="<?php echo $entry_mail_smtp_username; ?>" id="input-mail-smtp-username" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-mail-smtp-password"><?php echo $entry_mail_smtp_password; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_mail_smtp_password" value="<?php echo $config_mail_smtp_password; ?>" placeholder="<?php echo $entry_mail_smtp_password; ?>" id="input-mail-smtp-password" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-mail-smtp-port"><?php echo $entry_mail_smtp_port; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_mail_smtp_port" value="<?php echo $config_mail_smtp_port; ?>" placeholder="<?php echo $entry_mail_smtp_port; ?>" id="input-mail-smtp-port" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-mail-smtp-timeout"><?php echo $entry_mail_smtp_timeout; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_mail_smtp_timeout" value="<?php echo $config_mail_smtp_timeout; ?>" placeholder="<?php echo $entry_mail_smtp_timeout; ?>" id="input-mail-smtp-timeout" class="form-control" />
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Bounce Handling</legend>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-bounce-email"><span data-toggle="tooltip" title="where bounce emails will get sent. create a new email account for this if possible.">Bounce Email</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_bounce_email" value="<?php echo $config_bounce_email; ?>" placeholder="Bounce Email" id="input-bounce-email" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-bounce-username"><span data-toggle="tooltip" title="pop3 username to access this bounce account.">Bounce Username</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_bounce_username" value="<?php echo $config_bounce_username; ?>" placeholder="Bounce Email" id="input-bounce-username" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-bounce-password"><span data-toggle="tooltip" title="pop3 password to access this bounce account.">Bounce Password</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_bounce_password" value="<?php echo $config_bounce_password; ?>" placeholder="Bounce Password" id="input-bounce-password" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-bounce-host"><span data-toggle="tooltip" title=" pop3 incoming server address to access this bounce account (eg: mail.yourwebsite.com)">Bounce Host</span></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_bounce_host" value="<?php echo $config_bounce_host; ?>" placeholder="Bounce Host" id="input-bounce-host" class="form-control" />
                                </div>
                            </div>

                        </fieldset>

                    </div>
                    <div class="tab-pane" id="tab-ftp">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-ftp-host"><?php echo $entry_ftp_hostname; ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="config_ftp_hostname" value="<?php echo $config_ftp_hostname; ?>" placeholder="<?php echo $entry_ftp_hostname; ?>" id="input-ftp-host" class="form-control" />
                                <?php if ($error_ftp_hostname) { ?>
                                    <div class="text-danger"><?php echo $error_ftp_hostname; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-ftp-port"><?php echo $entry_ftp_port; ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="config_ftp_port" value="<?php echo $config_ftp_port; ?>" placeholder="<?php echo $entry_ftp_port; ?>" id="input-ftp-port" class="form-control" />
                                <?php if ($error_ftp_port) { ?>
                                    <div class="text-danger"><?php echo $error_ftp_port; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-ftp-username"><?php echo $entry_ftp_username; ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="config_ftp_username" value="<?php echo $config_ftp_username; ?>" placeholder="<?php echo $entry_ftp_username; ?>" id="input-ftp-username" class="form-control" />
                                <?php if ($error_ftp_username) { ?>
                                    <div class="text-danger"><?php echo $error_ftp_username; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-ftp-password"><?php echo $entry_ftp_password; ?></label>
                            <div class="col-sm-10">
                                <input type="text" name="config_ftp_password" value="<?php echo $config_ftp_password; ?>" placeholder="<?php echo $entry_ftp_password; ?>" id="input-ftp-password" class="form-control" />
                                <?php if ($error_ftp_password) { ?>
                                    <div class="text-danger"><?php echo $error_ftp_password; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-ftp-root"><span data-toggle="tooltip" data-html="true" title="<?php echo htmlspecialchars($help_ftp_root); ?>"><?php echo $entry_ftp_root; ?></span></label>
                            <div class="col-sm-10">
                                <input type="text" name="config_ftp_root" value="<?php echo $config_ftp_root; ?>" placeholder="<?php echo $entry_ftp_root; ?>" id="input-ftp-root" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $entry_ftp_status; ?></label>
                            <div class="col-sm-10">
                                <label class="radio-inline">
                                    <?php if ($config_ftp_status) { ?>
                                        <input type="radio" name="config_ftp_status" value="1" checked="checked" />
                                        <?php echo $text_yes; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_ftp_status" value="1" />
                                        <?php echo $text_yes; ?>
                                    <?php } ?>
                                </label>
                                <label class="radio-inline">
                                    <?php if (!$config_ftp_status) { ?>
                                        <input type="radio" name="config_ftp_status" value="0" checked="checked" />
                                        <?php echo $text_no; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_ftp_status" value="0" />
                                        <?php echo $text_no; ?>
                                    <?php } ?>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab-server">
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_secure; ?>"><?php echo $entry_secure; ?></span></label>
                            <div class="col-sm-9">
                                <label class="radio-inline">
                                    <?php if ($config_secure) { ?>
                                        <input type="radio" name="config_secure" value="1" checked="checked" />
                                        <?php echo $text_yes; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_secure" value="1" />
                                        <?php echo $text_yes; ?>
                                    <?php } ?>
                                </label>
                                <label class="radio-inline">
                                    <?php if (!$config_secure) { ?>
                                        <input type="radio" name="config_secure" value="0" checked="checked" />
                                        <?php echo $text_no; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_secure" value="0" />
                                        <?php echo $text_no; ?>
                                    <?php } ?>
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_maintenance; ?>"><?php echo $entry_maintenance; ?></span></label>
                            <div class="col-sm-9">
                                <label class="radio-inline">
                                    <?php if ($config_maintenance) { ?>
                                        <input type="radio" name="config_maintenance" value="1" checked="checked" />
                                        <?php echo $text_yes; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_maintenance" value="1" />
                                        <?php echo $text_yes; ?>
                                    <?php } ?>
                                </label>
                                <label class="radio-inline">
                                    <?php if (!$config_maintenance) { ?>
                                        <input type="radio" name="config_maintenance" value="0" checked="checked" />
                                        <?php echo $text_no; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_maintenance" value="0" />
                                        <?php echo $text_no; ?>
                                    <?php } ?>
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-robots"><?php echo $entry_robots; ?></label>
                            <div class="col-sm-9">
                                <textarea name="config_robots" rows="5" placeholder="<?php echo $entry_robots; ?>" id="input-meta-keyword" class="form-control"><?php echo $config_robots; ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-file-max-size"><span data-toggle="tooltip" title="<?php echo $help_file_max_size; ?>"><?php echo $entry_file_max_size; ?></span></label>
                            <div class="col-sm-10">
                                <input type="text" name="config_file_max_size" value="<?php echo $config_file_max_size; ?>" placeholder="<?php echo $entry_file_max_size; ?>" id="input-file-max-size" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-file-ext-allowed"><span data-toggle="tooltip" title="<?php echo $help_file_ext_allowed; ?>"><?php echo $entry_file_ext_allowed; ?></span></label>
                            <div class="col-sm-10">
                                <textarea name="config_file_ext_allowed" rows="5" placeholder="<?php echo $entry_file_ext_allowed; ?>" id="input-file-ext-allowed" class="form-control"><?php echo $config_file_ext_allowed; ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-file-mime-allowed"><span data-toggle="tooltip" title="<?php echo $help_file_mime_allowed; ?>"><?php echo $entry_file_mime_allowed; ?></span></label>
                            <div class="col-sm-10">
                                <textarea name="config_file_mime_allowed" cols="60" rows="5" placeholder="<?php echo $entry_file_mime_allowed; ?>" id="input-file-mime-allowed" class="form-control"><?php echo $config_file_mime_allowed; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-encryption"><span data-toggle="tooltip" title="<?php echo $help_encryption; ?>"><?php echo $entry_encryption; ?></span></label>
                            <div class="col-sm-9">
                                <input type="text" name="config_encryption" value="<?php echo $config_encryption; ?>" placeholder="<?php echo $entry_encryption; ?>" id="input-encryption" class="form-control" />
                                <?php if ($error_encryption) { ?>
                                    <div class="text-danger"><?php echo $error_encryption; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input-compression"><span data-toggle="tooltip" title="<?php echo $help_compression; ?>"><?php echo $entry_compression; ?></span></label>
                            <div class="col-sm-9">
                                <input type="text" name="config_compression" value="<?php echo $config_compression; ?>" placeholder="<?php echo $entry_compression; ?>" id="input-compression" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $entry_error_display; ?></label>
                            <div class="col-sm-9">
                                <label class="radio-inline">
                                    <?php if ($config_error_display) { ?>
                                        <input type="radio" name="config_error_display" value="1" checked="checked" />
                                        <?php echo $text_yes; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_error_display" value="1" />
                                        <?php echo $text_yes; ?>
                                    <?php } ?>
                                </label>
                                <label class="radio-inline">
                                    <?php if (!$config_error_display) { ?>
                                        <input type="radio" name="config_error_display" value="0" checked="checked" />
                                        <?php echo $text_no; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_error_display" value="0" />
                                        <?php echo $text_no; ?>
                                    <?php } ?>
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $entry_error_log; ?></label>
                            <div class="col-sm-9">
                                <label class="radio-inline">
                                    <?php if ($config_error_log) { ?>
                                        <input type="radio" name="config_error_log" value="1" checked="checked" />
                                        <?php echo $text_yes; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_error_log" value="1" />
                                        <?php echo $text_yes; ?>
                                    <?php } ?>
                                </label>
                                <label class="radio-inline">
                                    <?php if (!$config_error_log) { ?>
                                        <input type="radio" name="config_error_log" value="0" checked="checked" />
                                        <?php echo $text_no; ?>
                                    <?php } else { ?>
                                        <input type="radio" name="config_error_log" value="0" />
                                        <?php echo $text_no; ?>
                                    <?php } ?>
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab-google">
                        <fieldset>
                            <legend><?php echo $text_google_analytics; ?></legend>
                            <div class="alert alert-info"><?php echo $help_google_analytics; ?></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-google-analytics"><?php echo $entry_google_analytics; ?></label>
                                <div class="col-sm-9">
                                    <textarea name="config_google_analytics" rows="5" placeholder="<?php echo $entry_google_analytics; ?>" id="input-google-analytics" class="form-control"><?php echo $config_google_analytics; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-google-analytics-status"><?php echo $entry_status; ?></label>
                                <div class="col-sm-9">
                                    <select name="config_google_analytics_status" id="input-google-analytics-status" class="form-control">
                                        <?php if ($config_google_analytics_status) { ?>
                                            <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                            <option value="0"><?php echo $text_disabled; ?></option>
                                        <?php } else { ?>
                                            <option value="1"><?php echo $text_enabled; ?></option>
                                            <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_google_captcha; ?></legend>
                            <div class="alert alert-info"><?php echo $help_google_captcha; ?></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-google-captcha-public"><?php echo $entry_google_captcha_public; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_google_captcha_public" value="<?php echo $config_google_captcha_public; ?>" placeholder="<?php echo $entry_google_captcha_public; ?>" id="input-google-captcha-public" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-google-captcha-secret"><?php echo $entry_google_captcha_secret; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_google_captcha_secret" value="<?php echo $config_google_captcha_secret; ?>" placeholder="<?php echo $entry_google_captcha_secret; ?>" id="input-google-captcha-secret" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-google-captcha-status"><?php echo $entry_status; ?></label>
                                <div class="col-sm-9">
                                    <select name="config_google_captcha_status" id="input-google-captcha-status" class="form-control">
                                        <?php if ($config_google_captcha_status) { ?>
                                            <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                            <option value="0"><?php echo $text_disabled; ?></option>
                                        <?php } else { ?>
                                            <option value="1"><?php echo $text_enabled; ?></option>
                                            <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend><?php echo $text_google_api; ?></legend>
                            <div class="alert alert-info"><?php echo $help_google_api; ?></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-google-api"><?php echo $entry_google_api; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="config_google_api_key" value="<?php echo $config_google_api_key; ?>" placeholder="<?php echo $entry_google_api; ?>" id="input-google-api" class="form-control" />
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <!-- End Tabs -->
                </div>
            </form>
        </div>
    </div>
</section>

<script type="text/javascript"><!--
    docReady(function () {
        $('select[name=\'config_template\']').on('change', function () {
            $.ajax({
                url: 'index.php?p=setting/setting/template&token=<?php echo $token; ?>&template=' + encodeURIComponent(this.value),
                dataType: 'html',
                beforeSend: function () {
                    $('select[name=\'country_id\']').after(' <i class="fa fa-circle-o-notch fa-spin"></i>');
                },
                complete: function () {
                    $('.fa-spin').remove();
                },
                success: function (html) {
                    $('#template').attr('src', html);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });

        $('select[name=\'config_template\']').trigger('change');

    });
//--></script></div>
<?php echo $footer; ?>