<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-blog_latest" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i> <?php echo $button_cancel; ?></a> </div>


        <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-blog_latest" class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-count"><?php echo $entry_post_count; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="blog_latest_post_count" value="<?php echo $blog_latest_post_count; ?>" placeholder="<?php echo $entry_post_count; ?>" id="input-name" class="form-control" />
                        <?php if ($error_post_count) { ?>
                            <div class="text-danger"><?php echo $error_post_count; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-title"><?php echo $entry_title; ?></label>
                    <div class="col-sm-9">
                        <input type="text" name="blog_latest_title" placeholder="<?php echo $entry_title; ?>" id="input-heading" value="<?php echo isset($blog_latest_title) ? $blog_latest_title : ''; ?>" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="blog_latest_status" id="input-status" class="form-control">
                            <?php if ($blog_latest_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>
<?php echo $footer; ?>