<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-pencil"></i> <?php echo $text_edit; ?></h3>
            <div class="box-tools pull-right">
                <button type="submit" form="form-contact" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a> 
            </div>
        </div>
        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-contact" class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-contact_class_suffix"><span data-toggle="tooltip" title="" data-original-title="<?php echo $help_class_suffix; ?>"><?php echo $entry_class_suffix; ?></span></label>
                    <div class="col-sm-9">
                        <input type="text" name="contact_class_suffix" placeholder="<?php echo $entry_class_suffix; ?>" id="input-contact_class_suffix" value="<?php echo isset($contact_class_suffix) ? $contact_class_suffix : ''; ?>" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-9">
                        <select name="contact_status" id="input-status" class="form-control">
                            <?php if ($contact_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>

</section>
<?php echo $footer; ?>