<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    
    
    <div class="box box-theme">
        <div class="box-header with-border">
             <h3 class="box-title"><i class="fa fa-pencil"></i> <?php echo $text_edit; ?></h3>
             <div class="box-tools pull-right">
            <button type="submit" form="form-gallery" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a>
             </div>
        </div>
            <div class="box-body">

                <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-gallery" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_name; ?></label>
                        <div class="col-sm-10">
                            <input type="text" name="name" value="<?php echo $name; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                            <?php if ($error_name) { ?>
                                <div class="text-danger"><?php echo $error_name; ?></div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label"><span data-toggle="tooltip" title="<?php echo $help_title; ?>"><?php echo $entry_title; ?></span></label>
                        <div class="col-sm-10">
                            <input type="text" name="module_description" value="<?php echo $module_description; ?>" placeholder="<?php echo $entry_title; ?>" class="form-control" />

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-banner"><?php echo $entry_banner; ?></label>
                        <div class="col-sm-10">
                            <select name="filter_banner_id" id="input-banner" class="form-control">
                                <?php foreach ($banners as $banner) { ?>
                                    <?php if ($banner['banner_id'] == $filter_banner_id) { ?>
                                        <option value="<?php echo $banner['banner_id']; ?>" selected="selected"><?php echo $banner['name']; ?></option>
                                    <?php } else { ?>
                                        <option value="<?php echo $banner['banner_id']; ?>"><?php echo $banner['name']; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                            <?php if ($error_banner) { ?>
                                <div class="text-danger"><?php echo $error_banner; ?></div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-status"><span data-toggle="tooltip" title="<?php echo $help_resize; ?>"><?php echo $entry_resize; ?></span></label>
                        <div class="col-sm-10">
                            <select name="resize" id="input-status" class="form-control">
                                <?php if ($resize) { ?>
                                    <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                    <option value="0"><?php echo $text_no; ?></option>
                                <?php } else { ?>
                                    <option value="1"><?php echo $text_yes; ?></option>
                                    <option value="0" selected="selected"><?php echo $text_no; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                     <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-class_suffix"><span data-toggle="tooltip" title="" data-original-title="<?php echo $help_class_suffix; ?>"><?php echo $entry_class_suffix; ?></span></label>
                    <div class="col-sm-9">
                        <input type="text" name="class_suffix" placeholder="<?php echo $entry_class_suffix; ?>" id="input-class_suffix" value="<?php echo isset($class_suffix) ? $class_suffix : ''; ?>" class="form-control" />
                    </div>
                </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                        <div class="col-sm-10">
                            <select name="status" id="input-status" class="form-control">
                                <?php if ($status) { ?>
                                    <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                    <option value="0"><?php echo $text_disabled; ?></option>
                                <?php } else { ?>
                                    <option value="1"><?php echo $text_enabled; ?></option>
                                    <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<?php echo $footer; ?>