<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $testimonials; ?>" class="btn btn-app"><i class="fa fa-list text-info"></i><?php echo $button_testimonials; ?></a>
            <button type="submit" form="form-testimonials" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i> <?php echo $button_cancel; ?></a> </div>


        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-testimonials" class="form-horizontal">

                <div class="form-group">
                    <label class="col-sm-2 control-label"><?php echo $entry_excerpt_module; ?></label>
                    <div class="col-sm-10">
                        <select name="account_status" id="input-status" class="form-control">
                            <?php if ($testimonial_excerpt_module) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>



                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_module_photo"><?php echo $entry_module_photo; ?></label>
                    <div class="col-sm-10">
                        <select name="testimonial_module_photo" id="testimonial_module_photo" class="form-control">
                            <?php if ($testimonial_module_photo) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_module_rating"><?php echo $entry_module_rating; ?></label>
                    <div class="col-sm-10">
                        <select name="testimonial_module_rating" id="testimonial_module_rating" class="form-control">
                            <?php if ($testimonial_module_rating) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_pagination_limit"><?php echo $entry_pagination_limit; ?></label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" name="testimonial_pagination_limit" value="<?php echo $testimonial_pagination_limit; ?>" size="2" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_excerpt_page"><?php echo $entry_excerpt_page; ?></label>
                    <div class="col-sm-10">
                        <select name="testimonial_excerpt_page" id="testimonial_excerpt_page" class="form-control">
                            <?php if ($testimonial_excerpt_page) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_words"><?php echo $entry_excerpt_words; ?></label>
                    <div class="col-sm-2"><input type="text" class="form-control" name="testimonial_words" value="<?php echo $testimonial_words; ?>" size="2" /></div>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_display_photo"><?php echo $entry_display_photo; ?></label>
                    <div class="col-sm-10">
                        <select name="testimonial_display_photo" id="testimonial_display_photo" class="form-control">
                            <?php if ($testimonial_display_photo) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_photo_size"><?php echo $entry_photo_size; ?></label>
                    <div class="col-sm-2"><input class="form-control" type="text" name="testimonial_photo_size" value="<?php echo $testimonial_photo_size; ?>" size="2" /></div><div class="col-sm-8"><?php echo $text_pixels; ?></div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_display_rating"><?php echo $entry_display_rating; ?></label>
                    <div class="col-sm-10">
                        <select name="testimonial_display_rating" id="testimonial_display_rating" class="form-control">
                            <?php if ($testimonial_display_rating) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="testimonial_auto_approve"><?php echo $entry_auto_approve; ?></label>
                    <div class="col-sm-10">
                        <select name="testimonial_auto_approve" id="testimonial_auto_approve" class="form-control">
                            <?php if ($testimonial_auto_approve) { ?>
                                <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                <option value="0"><?php echo $text_no; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_yes; ?></option>
                                <option value="0" selected="selected"><?php echo $text_no; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-guest_status"><?php echo $entry_guest_status; ?></label>
                    <div class="col-sm-10">
                        <select name=testimonail_guest_status" id="input-guest_status" class="form-control">
                            <?php if ($testimonail_guest_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>






            </form>
        </div>
    </div>

</section>
<?php echo $footer; ?>