<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>
            <div class="box-tools pull-right">
                <button type="submit" form="form-filter" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a> 
            </div>
        </div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-google-hangouts" class="form-horizontal">

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="module_todo_status" id="input-status" class="form-control">
                            <?php if ($module_todo_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label"><span data-toggle="tooltip" data-html="true" data-trigger="click" title="<?php echo htmlspecialchars($help_autofilter); ?>"><?php echo $entry_autofilter; ?></span></label>
                    <div class="col-sm-10">
                        <label class="radio-inline control-label">
                            <input type="radio" name="module_todo_autofilter" value="0" <?php echo $module_todo_autofilter == "0" ? 'checked="checked"' : ''; ?>/>
                            <?php echo $text_no; ?>
                        </label>
                        <label class="radio-inline control-label">
                            <input type="radio" name="module_todo_autofilter" value="1" <?php echo $module_todo_autofilter == "1" ? 'checked="checked"' : ''; ?>/>
                            <?php echo $text_yes; ?>
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label"><span data-toggle="tooltip" data-html="true" data-trigger="click" title="<?php echo htmlspecialchars($help_log_direction); ?>"><?php echo $entry_log_direction; ?></span></label>
                    <div class="col-sm-10">
                        <label class="radio-inline control-label">
                            <input type="radio" name="module_todo_log_direction" value="asc" <?php echo $module_todo_log_direction == "asc" ? 'checked="checked"' : ''; ?>/>
                            <?php echo $text_asc; ?>
                        </label>
                        <label class="radio-inline control-label">
                            <input type="radio" name="module_todo_log_direction" value="desc" <?php echo $module_todo_log_direction == "desc" ? 'checked="checked"' : ''; ?>/>
                            <?php echo $text_desc; ?>
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label"><span data-toggle="tooltip" data-html="true" data-trigger="click" title="<?php echo htmlspecialchars($help_email_notification); ?>"><?php echo $entry_email_notification; ?></span></label>
                    <div class="col-sm-10">
                        <label class="radio-inline control-label">
                            <input type="radio" name="module_todo_email_notification" value="0" <?php echo $module_todo_email_notification == "0" ? 'checked="checked"' : ''; ?>/>
                            <?php echo $text_no; ?>
                        </label>
                        <label class="radio-inline control-label">
                            <input type="radio" name="module_todo_email_notification" value="1" <?php echo $module_todo_email_notification == "1" ? 'checked="checked"' : ''; ?>/>
                            <?php echo $text_yes; ?>
                        </label>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
<?php echo $footer; ?>