<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">

            <a href="<?php echo $insert; ?>" class="btn btn-app"><i class="fa fa-plus text-green"></i> <?php echo $button_insert; ?></a>
            <button class="btn btn-app" onclick="$('#form').submit();">
                <i class="fa fa-times text-red"></i> <?php echo $button_delete; ?>
            </button>
        </div>
        <div class="box-body table-responsive">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <td width="1" style="text-align: center;"><input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></td>
                            <td class="left"><?php if ($sort == 'name') { ?>
                                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                <?php } ?></td>
                            <td class="text-right"><?php echo $column_action; ?></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($layouts) { ?>
                            <?php foreach ($layouts as $layout) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($layout['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $layout['layout_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $layout['layout_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $layout['name']; ?></td>
                                    <td class="text-right"><?php foreach ($layout['action'] as $action) { ?>
                                            <a class="btn btn-xs btn-primary" href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a>
                                        <?php } ?></td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="3"><?php echo $text_no_results; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </form>

        </div>
        <div clas="box-footer">
            <div class="pagination-container row">
                <?php echo $pagination; ?>
            </div>
        </div>
    </div>
</section>


<?php echo $footer; ?>