<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">

            <button onclick="$('#form').submit();" class="btn btn-app"><i class="fa fa-check text-green"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" class="btn btn-app"><i class="fa fa-backward"></i>  <?php echo $button_cancel; ?></a>


        </div>

        <div class="box-body table-responsive">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form">
                <div class="form-group">
                    <label for="nameInput" class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                    <div class="col-sm-9">
                        <input type="text" name="name" value="<?php echo $name; ?>" class="form-control required" id="nameInput" />
                        <?php if ($error_name) { ?>
                            <span class="error text-danger"><?php echo $error_name; ?></span>
                        <?php } ?>
                    </div>
                </div>
                <br />
                <hr />
                <table id="route" class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>

                            <th class="left"><?php echo $entry_route; ?></th>
                            <th></th>
                        </tr>
                    </thead>
                    <?php $route_row = 0; ?>
                    <?php foreach ($layout_routes as $layout_route) { ?>
                        <tbody id="route-row<?php echo $route_row; ?>">
                            <tr>

                                <td class="left"><input class="form-control" type="text" name="layout_route[<?php echo $route_row; ?>][route]" value="<?php echo $layout_route['route']; ?>" /></td>
                                <td class="text-right"><a onclick="$('#route-row<?php echo $route_row; ?>').remove();" class="btn btn-danger"><i class="fa fa-minus-circle"></i></a></td>
                            </tr>
                        </tbody>
                        <?php $route_row++; ?>
                    <?php } ?>
                    <tfoot>
                        <tr>
                            <td colspan=""></td>
                            <td class="text-right"><a onclick="addRoute();" class="btn btn-primary"><i class="fa fa-plus-circle"></i></a></td>
                        </tr>
                    </tfoot>
                </table>
                <hr />
                <table id="module" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <td class="text-left"><?php echo $entry_module; ?></td>
                            <td class="text-left"><?php echo $entry_position; ?></td>
                            <td class="text-right"><?php echo $entry_sort_order; ?></td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $module_row = 0; ?>
                        <?php foreach ($layout_modules as $layout_module) { ?>
                            <tr id="module-row<?php echo $module_row; ?>">
                                <td class="text-left"><select name="layout_module[<?php echo $module_row; ?>][code]" class="form-control">
                                        <?php foreach ($extensions as $extension) { ?>
                                            <?php if (!$extension['module']) { ?>
                                                <?php if ($extension['code'] == $layout_module['code']) { ?>
                                                    <option value="<?php echo $extension['code']; ?>" selected="selected"><?php echo $extension['name']; ?></option>
                                                <?php } else { ?>
                                                    <option value="<?php echo $extension['code']; ?>"><?php echo $extension['name']; ?></option>
                                                <?php } ?>
                                            <?php } else { ?>
                                                <optgroup label="<?php echo $extension['name']; ?>">
                                                    <?php foreach ($extension['module'] as $module) { ?>
                                                        <?php if ($module['code'] == $layout_module['code']) { ?>
                                                            <option value="<?php echo $module['code']; ?>" selected="selected"><?php echo $module['name']; ?></option>
                                                        <?php } else { ?>
                                                            <option value="<?php echo $module['code']; ?>"><?php echo $module['name']; ?></option>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </optgroup>
                                            <?php } ?>
                                        <?php } ?>
                                    </select></td>
                                <td class="text-left"><select name="layout_module[<?php echo $module_row; ?>][position]" class="form-control">

                                        <?php if ($layout_module['position'] == 'content_top') { ?>
                                            <option value="content_top" selected="selected"><?php echo $text_content_top; ?></option>
                                        <?php } else { ?>
                                            <option value="content_top"><?php echo $text_content_top; ?></option>
                                        <?php } ?>
                                        <?php if ($layout_module['position'] == 'content_bottom') { ?>
                                            <option value="content_bottom" selected="selected"><?php echo $text_content_bottom; ?></option>
                                        <?php } else { ?>
                                            <option value="content_bottom"><?php echo $text_content_bottom; ?></option>
                                        <?php } ?>
                                        <?php if ($layout_module['position'] == 'column_top') { ?>
                                            <option value="column_top" selected="selected"><?php echo $text_column_top; ?></option>
                                        <?php } else { ?>
                                            <option value="column_top"><?php echo $text_column_top; ?></option>
                                        <?php } ?>
                                        <?php if ($layout_module['position'] == 'column_bottom') { ?>
                                            <option value="column_bottom" selected="selected"><?php echo $text_column_bottom; ?></option>
                                        <?php } else { ?>
                                            <option value="column_bottom"><?php echo $text_column_bottom; ?></option>
                                        <?php } ?>
                                        <?php if ($layout_module['position'] == 'column_left') { ?>
                                            <option value="column_left" selected="selected"><?php echo $text_column_left; ?></option>
                                        <?php } else { ?>
                                            <option value="column_left"><?php echo $text_column_left; ?></option>
                                        <?php } ?>
                                        <?php if ($layout_module['position'] == 'column_right') { ?>
                                            <option value="column_right" selected="selected"><?php echo $text_column_right; ?></option>
                                        <?php } else { ?>
                                            <option value="column_right"><?php echo $text_column_right; ?></option>
                                        <?php } ?>
                                        <?php foreach ($template_positions as $template_position): ?>
                                            <?php if ($layout_module['position'] == $template_position) { ?>
                                                <option value="<?php echo $template_position; ?>" selected="selected"><?php echo $template_position; ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $template_position; ?>"><?php echo $template_position; ?></option>
                                            <?php } ?>
                                        <?php endforeach; ?>
                                    </select></td>
                                <td class="text-right"><input type="text" name="layout_module[<?php echo $module_row; ?>][sort_order]" value="<?php echo $layout_module['sort_order']; ?>" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>
                                <td class="text-left"><button type="button" onclick="$('#module-row<?php echo $module_row; ?>').remove();" data-toggle="tooltip" title="<?php echo $button_remove; ?>" class="btn btn-danger"><i class="fa fa-minus-circle"></i></button></td>
                            </tr>
                            <?php $module_row++; ?>
                        <?php } ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3"></td>
                            <td class="text-right"><button type="button" onclick="addModule();" data-toggle="tooltip" title="<?php echo $button_module_add; ?>" class="btn btn-primary"><i class="fa fa-plus-circle"></i></button></td>
                        </tr>
                    </tfoot>
                </table>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"><!--
var route_row = <?php echo $route_row; ?>;

    function addRoute() {
        html = '<tbody id="route-row' + route_row + '">';
        html += '  <tr>';

        html += '    <td class="left"><input class="form-control" type="text" name="layout_route[' + route_row + '][route]" value="" /></td>';
        html += '    <td class="text-right"><a onclick="$(\'#route-row' + route_row + '\').remove();" class="btn btn-danger"><i class="fa fa-minus-circle"></i></a></td>';
        html += '  </tr>';
        html += '</tbody>';

        $('#route > tfoot').before(html);

        route_row++;
    }

    var module_row = <?php echo $module_row; ?>;

    function addModule() {
        html = '<tr id="module-row' + module_row + '">';
        html += '  <td class="text-left"><select name="layout_module[' + module_row + '][code]" class="form-control">';
<?php foreach ($extensions as $extension) { ?>
    <?php if (!$extension['module']) { ?>
                html += '    <option value="<?php echo $extension['code']; ?>"><?php echo addslashes($extension['name']); ?></option>';
    <?php } else { ?>
                html += '    <optgroup label="<?php echo addslashes($extension['name']); ?>">';
        <?php foreach ($extension['module'] as $module) { ?>
                    html += '      <option value="<?php echo $module['code']; ?>"><?php echo addslashes($module['name']); ?></option>';
        <?php } ?>
                html += '    </optgroup>';
    <?php } ?>
<?php } ?>
        html += '  </select></td>';
        html += '  <td class="text-left"><select name="layout_module[' + module_row + '][position]" class="form-control">';
        html += '    <option value="content_top"><?php echo $text_content_top; ?></option>';
        html += '    <option value="content_bottom"><?php echo $text_content_bottom; ?></option>';
        html += '    <option value="column_top"><?php echo $text_column_top; ?></option>';
        html += '    <option value="column_bottom"><?php echo $text_column_bottom; ?></option>';
        html += '    <option value="column_left"><?php echo $text_column_left; ?></option>';
        html += '    <option value="column_right"><?php echo $text_column_right; ?></option>';
<?php foreach ($template_positions as $template_position): ?>
            html += '    <option value="<?php echo $template_position; ?>"><?php echo $template_position; ?></option>';
<?php endforeach; ?>
        html += '  </select></td>';
        html += '  <td class="text-left"><input type="text" name="layout_module[' + module_row + '][sort_order]" value="" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>';
        html += '  <td class="text-left"><button type="button" onclick="$(\'#module-row' + module_row + '\').remove();" data-toggle="tooltip" title="<?php echo $button_remove; ?>" class="btn btn-danger"><i class="fa fa-minus-circle"></i></button></td>';
        html += '</tr>';

        $('#module tbody').append(html);

        module_row++;
    }
//--></script> 
<?php echo $footer; ?>