<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header ">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>
             <div class="box-tools pull-right">
            <button type="submit" form="form" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
        </div>
       

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form" class="form-horizontal">
                <div class="form-group">
                    <label for="nameInput" class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                    <div class="col-sm-9">
                        <input type="text" name="name" value="<?php echo $name; ?>" class="form-control required" id="nameInput" />
                        <?php if ($error_name) { ?>
                            <span class="error text-danger"><?php echo $error_name; ?></span>
                        <?php } ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-header"><?php echo $entry_header; ?></label>
                    <div class="col-sm-9">
                        <select name="header" id="input-header" class="form-control">
                            <?php if ($isheader) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-footer"><?php echo $entry_footer; ?></label>
                    <div class="col-sm-9">
                        <select name="footer" id="input-footer" class="form-control">
                            <?php if ($isfooter) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-footer"><?php echo $entry_structure; ?></label>
                    <div class="col-sm-9">


                        <div class="dd" id="nestable">
                            <ol class="dd-list">
                                <?php echo buildMenuTree($items); ?>

                            </ol>
                        </div>
                        <input type="hidden" id="menu_items_input" name="items" value="" />
                        
                    </div>

            
        </div>
                <div class="form-group">
                   
                    <div class="col-sm-12 text-right">

                        <button class="btn btn-primary" type="button" id="add_menu_item"><i class="fa fa-plus"></i> Add Menu Item</button>
                    </div>

            
        </div>
</form>
    </div>
</div>

<div id="menu-item-modal" class="modal fade" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body form-horizontal">
                <input type="hidden" id="item_id" value="0" />
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <?php echo $this->language->get("General"); ?>
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label required"><?php echo $entry_title; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text"  value="" class="form-control required" id="titleInput" />

                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-3 control-label required"><?php echo $entry_link; ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" value="" class="form-control required" id="linkLabelInput" />
                                        <input type="hidden" id="amsPageIdInput" value="0" />
                                        <input type="hidden"  value="" id="linkInput" />

                                        <span class="help-text"><?php echo $help_link; ?></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="accessInput" class="control-label col-sm-3"><?php echo $this->language->get('Target'); ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" value="" class="form-control" id="targetInput" />
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>


                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingThree">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    <?php echo $this->language->get("Permissions"); ?>
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="accessInput" class="col-sm-3"><?php echo $entry_allowed_groups; ?></label>
                                    <div class="col-sm-9">

                                        <ul class="list-group">
                                            <?php $class = 'odd'; ?>
                                            <?php foreach ($customer_groups as $customer_group) : ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <input type="checkbox" class="allowed_groups" value="<?php echo $customer_group['customer_group_id']; ?>" />
                                                    <?php echo $customer_group['name']; ?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="accessInput" class="col-sm-3"><?php echo $entry_denied_groups; ?></label>
                                    <div class="col-sm-9">

                                        <ul class="list-group">
                                            <?php $class = 'odd'; ?>
                                            <?php foreach ($customer_groups as $customer_group) : ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <input type="checkbox" class="denied_groups" value="<?php echo $customer_group['customer_group_id']; ?>" />
                                                    <?php echo $customer_group['name']; ?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingTwo">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    <?php echo $this->language->get("Advanced"); ?>
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label required"><?php echo $this->language->get('route'); ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" id="routeInput" class="form-control" value="" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="accessInput" class="col-sm-3 control-label"><?php echo $this->language->get('Params'); ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" value="" class="form-control" id="paramsInput" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="accessInput" class="col-sm-3 control-label"><?php echo $this->language->get('SSL'); ?></label>
                                    <div class="col-sm-9">
                                        <select class="form-control" id="sslInput">
                                            <option value="0">No</option>
                                            <option value="1">Yes</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>




            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="save_menu_item" type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

</div><!-- /.modal -->



<?php

function buildMenuTree($mi, &$_id = 0) {
    /* <li class="dd-item" data-id="3" 
     * data-title="item label" 
     * data-ams_page_id="0" data-link="asldfkjasdlk" data-allowed="-1" data-denied=""><div class="dd-handle"></div><div class="dd-content"><span class="text">item label</span><div class="tools"><i class="fa fa-edit"></i><i class="fa fa-trash-o"></i></div></div></li> */

    $xhtml = '';
    foreach ($mi as $m) {


        $xhtml .= '<li class="dd-item" data-id="' . $_id++ . '" '
                . 'data-route="' . $m['route'] . '" '
                . 'data-params="' . $m['params'] . '" '
                . 'data-ams-page-id="' . htmlentities($m['ams_page_id']) . '" '
                . 'data-target="' . htmlentities($m['target']) . '" '
                . 'data-title="' . htmlentities($m['title']) . '" '
                . 'data-ssl="' . (int) $m['ssl'] . '" '
                . 'data-link="' . $m['link'] . '" '
                . 'data-linklabel="' . $m['linklabel'] . '" '
                . 'data-allowed_groups="' . $m['allowed_groups'] . '" '
                . 'data-denied_groups="' . $m['denied_groups'] . '">';
        $xhtml .= '<div class="dd-handle"></div>';
        $xhtml .= '<div class="dd-content">';
        $xhtml .= ' <span class="text">' . $m['title'] . '</span>
                                        <div class="tools">
                                            <i class="fa fa-edit"></i>
                                            <i class="fa fa-trash-o"></i>
                                        </div>';
        $xhtml .= '</div>';
        if (!empty($m['children'])) {
            $xhtml .= '<ol class="dd-list">';
            $xhtml .= buildMenuTree($m['children'], $_id);
            $xhtml .= '</ol>';
        }
        $xhtml .= '</li>';
    }

    return $xhtml;
}
?>


<script type="text/javascript"><!--
    function htmlEntities(str) {
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos');
    }

    var $item_id = 0;

    var $item_action;

    docReady(function () {
        $('#nestable').nestable();
        $('#menu_items_input').val(JSON.stringify($('#nestable').nestable('serialize')));
        $('#nestable').on('change', function () {
            $('#menu_items_input').val(JSON.stringify($('#nestable').nestable('serialize')));

            /* on change event */
        });

        $('#linkLabelInput').on("keyup", function () {
            $('#amsPageIdInput').val('0');
            $('#linkInput').val($(this).val());
            $('#routeInput').val('');
            $('#paramsInput').val('');
        });

        var item_ids = $('#nestable [data-id]').map(function () {
            return parseInt($(this).attr('data-id'), 10);
        }
        ).get();
        $item_id = Math.max.apply(Math, item_ids);

        // $('#add_menu_item').on("click", function () {
        $(document).on("click", '#add_menu_item', function () {
            $item_action = 'add';
            $item_id++;
            $('#item_id').val($item_id);
            $('#titleInput').val('');
            $('#amsPageIdInput').val('');
            $('#linkInput').val('');
            $('#linkLabelInput').val('');
            $('#targetInput').val('');

            $('#routeInput').val('');
            $('#paramsInput').val('');
            $('#sslInput').val(0);
            $('#menu-item-modal .modal-title').text('Add Menu Item');

            $('.denied_groups').prop("checked", false);
            $('.allowed_groups').prop("checked", false);
            $('.allowed_groups[value="-1"]').prop("checked", "checked");


            $('#menu-item-modal').modal('show');
            if ($($('a[href="#collapseOne"]')).hasClass('collapsed')) {
                $('a[href="#collapseOne"]').trigger("click");
            }
        });

        $(document).on("click", '#nestable .fa-edit', function () {
            //  $('#nestable .fa-edit').on("click", function () {
            var theLi = $(this).closest('li');
            $item_action = 'edit';

            $('#item_id').val(theLi.attr('data-id'));
            $('#titleInput').val(theLi.attr('data-title'));
            $('#amsPageIdInput').val(theLi.attr('data-ams-page-id'));
            $('#linkInput').val(theLi.attr('data-link'));
            $('#linkLabelInput').val(theLi.attr('data-linklabel'));
            $('#targetInput').val(theLi.attr('data-target'));

            $('#routeInput').val(theLi.attr('data-route'));
            $('#paramsInput').val(theLi.attr('data-params'));
            $('#sslInput').val(theLi.attr('data-ssl'));

            //routeInput
            //paramsInput
            //sslInput

            $('#menu-item-modal .modal-title').text('Edit Menu Item');

            $('.denied_groups').prop("checked", false);
            $('.allowed_groups').prop("checked", false);
            try {
                var all = theLi.attr('data-allowed_groups').split(",");
                $.each(all, function (i, j) {
                    $('.allowed_groups[value="' + j + '"]').prop("checked", "checked");
                });
            } catch (err) {

            }
            try {
                var den = theLi.attr('data-denied_groups').split(",");
                $.each(den, function (i, j) {
                    $('.denied_groups[value="' + j + '"]').prop("checked", "checked");
                });
            } catch (err) {
            }


            //$('.allowed_groups[value="-1"]').prop("checked", "checked");

            $('#menu-item-modal').modal('show');
            if ($($('a[href="#collapseOne"]')).hasClass('collapsed')) {
                $('a[href="#collapseOne"]').trigger("click");
            }
        });


        $('#linkLabelInput').autocomplete({
            'source': function (request, response) {
                $.ajax({
                    url: '<?php echo $catalog_uri; ?>?p=cms/page/autocomplete&token=<?php echo $token; ?>&filter_page=' + encodeURIComponent(request.term),
                    dataType: 'json',
                    success: function (json) {
                        $('.ui-autocomplete').css('z-index', '999999999');
                        response($.map(json, function (item) {
                            return {
                                label: decodeEntities(item['name']),
                                ams_page: item['ams_page_id'],
                                link: item['link'],
                                ssl: item['ssl'],
                                params: item['params'],
                                route: item['route']
                            }
                        }));
                    }
                });
            },
            'select': function (ev, ui) {
                //  console.log(ui.item);
                $('#linkInput').val(ui.item.link);
                $('#linkLabelInput').val(ui.item.label);
                $('#amsPageIdInput').val(ui.item.ams_page);
                $('#routeInput').val(ui.item.route);
                $('#paramsInput').val(ui.item.params);
                $('#sslInput').val((ui.item.ssl) ? '1' : '0');
                return false;

                // $('input[name=\'filter_name\']').val(item['label']);
            }
        });


        $(document).on("click", '#save_menu_item', function () {
            //$('#save_menu_item').on("click", function () {
            var theTitle = $('#titleInput').val();
            var theLink = $('#linkInput').val();
            var theLabel = $('#linkLabelInput').val();
            var thePage = $('#amsPageIdInput').val();
            var theId = $('#item_id').val();
            var theTarget = $('#targetInput').val();
            var theDenied = new Array();
            var theAllowed = new Array();
            $('.denied_groups:checked').each(function () {
                theDenied.push($(this).val());
            });
            $('.allowed_groups:checked').each(function () {
                theAllowed.push($(this).val());
            });

            var theRoute = $('#routeInput').val();
            var theParams = $('#paramsInput').val();
            var theSSL = $('#sslInput').val();

            /*  if (theLink == '') {
             //  theLink = theLabel;
             }*/
            if (theLink == theLabel) {
                theLink = '';
            }

            if ($item_action == 'add') {
                var newitem = $('<li />')
                        .addClass("dd-item")
                        .attr('data-id', theId)
                        .attr('data-route', theRoute)
                        .attr('data-params', theParams)
                        .attr('data-title', htmlEntities(theTitle))
                        .attr('data-ams-page-id', thePage)
                        .attr('data-target', theTarget)
                        .attr('data-link', theLink)
                        .attr('data-ssl', theSSL)
                        .attr('data-linklabel', htmlEntities(theLabel))
                        .attr('data-allowed_groups', theAllowed.join())
                        .attr('data-denied_groups', theDenied.join())
                        .prop('data-allowed_groups', theAllowed.join())
                        .prop('data-denied_groups', theDenied.join())
                        .append('<div class="dd-handle"></div>');
                var ddcontent = $('<div />').addClass('dd-content');
                ddcontent.append('<span class="text">' + theTitle + '</span>');
                ddcontent.append('<div class="tools"><i class="fa fa-edit"></i><i class="fa fa-trash-o"></i></div>');
                newitem.append(ddcontent);
                $('#nestable > ol').append(newitem);


            } else {
                $('li[data-id=' + theId + ']').attr('data-ams_page_id', thePage)
                         .attr('data-route', theRoute)
                        .attr('data-params', theParams)
                        .attr('data-title', htmlEntities(theTitle))
                        .attr('data-ams-page-id', thePage)
                        .attr('data-target', theTarget)
                        .attr('data-link', theLink)
                        .attr('data-ssl', theSSL)
                        .attr('data-linklabel', htmlEntities(theLabel))
                        .attr('data-allowed_groups', theAllowed.join())
                        .attr('data-denied_groups', theDenied.join())
                        .prop('data-allowed_groups', theAllowed.join())
                        .prop('data-denied_groups', theDenied.join());
                $('li[data-id=' + theId + '] > .dd-content .text').html(theTitle);
            }
            $('#menu_items_input').val(JSON.stringify($('#nestable').nestable('serialize')));
            $('#menu-item-modal').modal('hide');
        });

        $(document).on("click", '#nestable .fa-trash-o', function () {
            //   $('#nestable .fa-trash-o').on("click", function () {
            if (confirm('<?php echo $text_confirm; ?>')) {
                $(this).closest('li').remove();
                $('#menu_items_input').val(JSON.stringify($('#nestable').nestable('serialize')));
            }
        });
        /*
         * var denied = new Array();
         $('.denied_groups:checked').each(function() { 
         denied.push($(this).val());
         });
         */
    });
//--></script> 
<?php echo $footer; ?>