<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-bars"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" data-toggle="tooltip" title="<?php echo $button_insert; ?>" class="btn btn-success"><i class="fa fa-plus"></i></a>
                <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                        $('#form').submit();
                    });"><i class="fa fa-trash-o"></i> </button>  </div>
        </div>

        <div class="box-body table-responsive">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <td width="1" style="text-align: center;"><input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></td>
                            <td class="left"><?php echo $column_name; ?></td>
                            <td class="text-right"><?php echo $column_action; ?></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($menus) { ?>
                            <?php foreach ($menus as $menu) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($menu['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $menu['menu_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $menu['menu_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $menu['name']; ?> <?php echo $menu['header'] . $menu['footer'];?></td>
                                    <td class="text-right"><?php foreach ($menu['action'] as $action) { ?>
                                            <a target="<?php echo (!empty($action['target'])) ? $action['target'] : '_self'; ?>" class="btn btn-sm btn-<?php echo $action['class']; ?>" href="<?php echo $action['href']; ?>" data-toggle="tooltip" title="<?php echo $action['text']; ?>"><i class="<?php echo $action['icon']; ?>"></i></a>
                                <?php } ?></td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="3"><?php echo $text_no_results; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </form>

       
        </div>
    </div>
</section>


<?php echo $footer; ?>