<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>.

<!-- Main content -->
<section class="content">


    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>

            <div class="box-tools pull-right">
                <button type="submit" form="form-google-captcha" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save "></i> </button>
                <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i> </a>

            </div>
        </div>

        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-google-captcha" class="form-horizontal">
                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $text_signup; ?>
                    <button type="button" class="close" data-dismiss="alert">&times;</button></div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-key"><?php echo $entry_key; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="google_captcha_key" value="<?php echo $google_captcha_key; ?>" placeholder="<?php echo $entry_key; ?>" id="input-key" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-secret"><?php echo $entry_secret; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="google_captcha_secret" value="<?php echo $google_captcha_secret; ?>" placeholder="<?php echo $entry_secret; ?>" id="input-secret" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="google_captcha_status" id="input-status" class="form-control">
                            <?php if ($google_captcha_status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?>
