</div><!-- /.content-wrapper -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
</footer>


</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->
<script src="view/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<script src="view/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>


<!-- Custom JS -->
    <script src="view/plugins/fastclick/fastclick.min.js"></script>
<script src="view/js/app.min.js" type="text/javascript"></script>
<script src="view/js/admin.js" type="text/javascript"></script>




</body>
</html>