</div><!-- /.content-wrapper -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
</footer>


</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->
<?php if(strpos($this->request->get['p'], 'module/revslide') === false): ?>
<script src="view/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<?php endif; ?>

<script src="view/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="view/plugins/sweetalert/sweetalert.min.js"></script>

<!-- Custom JS -->
<script src="view/plugins/fastclick/fastclick.min.js"></script>
<script src="view/js/app.min.js" type="text/javascript"></script>
<script src="view/js/admin.js" type="text/javascript"></script>

<script>
 

    function EditorOn(id) {
        CKEDITOR.replace(id);

    }
    
</script>


</body>
</html>