<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $title; ?></title>
        <base href="<?php echo $base; ?>" />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- Bootstrap 3.3.4 -->
        <link href="view/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- Font Awesome Icons -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="view/css/AdminLTE.min.css,css/skins.min.css" rel="stylesheet" type="text/css" />


        <!-- Custom CSS -->

        <?php foreach ($links as $link) { ?>
            <link href="<?php echo $link['href']; ?>" rel="<?php echo $link['rel']; ?>" />
        <?php } ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script type="text/javascript">
            /** Hack to make sure that inline code can reference $.ready style functionality **/
            var onReadyCallbacks = [];
            var docReady = function (callback) {
                onReadyCallbacks.push(callback);
            }

        </script>
    </head>
    <!--
    BODY TAG OPTIONS:
    =================
    Apply one or more of the following classes to get the
    desired effect
    |---------------------------------------------------------|
    | SKINS         | skin-blue                               |
    |               | skin-black                              |
    |               | skin-purple                             |
    |               | skin-yellow                             |
    |               | skin-red                                |
    |               | skin-green                              |
    |---------------------------------------------------------|
    |LAYOUT OPTIONS | fixed                                   |
    |               | layout-boxed                            |
    |               | layout-top-nav                          |
    |               | sidebar-collapse                        |
    |               | sidebar-mini                            |
    |---------------------------------------------------------|
    -->
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">

            <!-- Main Header -->
            <header class="main-header">

                <!-- Logo -->
                <a href="<?php echo $home; ?>" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini">CMS</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Core</b>CMS</span>
                </a>

                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only"><?php echo $text_toggle_navigation; ?></span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <?php foreach ($header_navs as $hnav): ?>
                                <li class="dropdown notifications-menu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="<?php echo $hnav['icon']; ?>"></i>
                                        <span class="label label-<?php echo $hnav['class']; ?>"><?php echo $hnav['total']; ?></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <?php if ($hnav['title']): ?>
                                            <li class="header"><?php echo $hnav['title']; ?></li>
                                        <?php endif; ?>
                                        <li>
                                            <!-- inner menu: contains the actual data -->
                                            <ul class="menu">
                                                <?php foreach ($hnav['items'] as $hitem): ?>
                                                    <li>
                                                        <a href="<?php echo $hitem['href']; ?>">
                                                            <span class="label label-<?php echo $hitem['class']; ?>"><?php echo $hitem['total']; ?></span>
                                                            <?php echo $hitem['text']; ?>
                                                        </a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            <?php endforeach; ?>

                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="<?php echo $profile_img; ?>" class="user-image" alt="User Image"/>
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs"><?php echo $this->user->getFullName(); ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img src="<?php echo $profile_img; ?>" class="img-circle" alt="User Image" />
                                        <p>
                                            <?php echo $this->user->getFullName(); ?>
                                            <small>Member since <?php echo $member_since; ?></small>
                                        </p>
                                    </li>
                                    <!-- Menu Body -->

                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="<?php echo $member_profile; ?>" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?php echo $logout; ?>" class="btn btn-default btn-flat"><?php echo $text_logout; ?></a>
                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">

                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="<?php echo $profile_img; ?>" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p><?php echo $this->user->getFullName(); ?></p>
                            <!-- Status -->
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>

                    <!-- search form (Optional) -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->

                    <!-- Sidebar Menu -->
                    <ul class="sidebar-menu">
                        <li class="header">Navigation</li>
                        <!-- Optionally, you can add icons to the links -->
                        <li><a href="<?php echo $home; ?>"><i class="fa fa-dashboard"></i>  <span><?php echo $menu_dashboard; ?></span></a></li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-file-text-o"></i>
                                <span><?php echo $menu_content; ?></span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $pages; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_pages; ?></a></li>
                                <li><a href="<?php echo $posts; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_posts; ?></a></li>
                                <li><a href="<?php echo $blog_category; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_blog_category; ?></a></li>
                                <li><a href="<?php echo $banner; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_banners; ?></a></li>
                                <li><a href="<?php echo $comments; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_comments; ?><?php if ($total_comments): ?> <span class="badge bg-red pull-right"><?php echo $total_comments; ?></span><?php endif; ?></a></li>
                                <li><a href="<?php echo $download; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_download; ?></a></li>
                                <li><a href="<?php echo $menu; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_menu; ?></a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-envelope-o"></i>
                                <span><?php echo $menu_communication; ?></span>
                                <i class="fa fa-angle-left pull-right"></i>
                                <ul class="treeview-menu">
                                    <li><a href="<?php echo $contact_us;?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_contact_us; ?><?php if ($total_contact_us): ?> <span class="badge bg-red pull-right"><?php echo $total_contact_us; ?></span><?php endif; ?></a></li>
                                    <li><a href="<?php echo $marketing;?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_marketing; ?></a></li>
                                    <li><a href="<?php echo $newsletter; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_newsletters; ?></a></li>
                                     <li><a href="<?php echo $subscriber; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_subscriber; ?></a></li>
                                </ul>
                            </a>

                        </li>
                        
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-user"></i>
                                <span><?php echo $menu_user; ?></span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li class="treeview">
                                    <a href="#">
                                        <i class="fa fa-user"></i>
                                        <span><?php echo $menu_user_admin; ?></span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li><a href="<?php echo $user; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_user; ?></a></li>
                                        <li><a href="<?php echo $user_group; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_user_group; ?></a></li>
                                    </ul>
                                </li>  
                                <li class="treeview">
                                    <a href="#">
                                        <i class="fa fa-user"></i>
                                        <span><?php echo $menu_user_public; ?></span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li><a href="<?php echo $user_front; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_user; ?></a></li>
                                        <li><a href="<?php echo $user_group_front; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_user_group; ?></a></li>
                                        <li><a href="<?php echo $user_group_ban; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_user_ip_ban; ?></a></li>
                                    </ul>
                                </li>   
                                <li><a href="<?php echo $api_user; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_api_user; ?></a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="top">
                                <i class="fa fa-bar-chart"></i> <Span><?php echo $menu_reports; ?></span><i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $report_user_activity; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_report_user_activity; ?></a></li>
                                <li><a href="<?php echo $report_user_online; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_report_user_online; ?></a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-puzzle-piece"></i>
                                <span><?php echo $menu_extension; ?></span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $modules; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_modules; ?></a></li>
                                <li><a href="<?php echo $modifications; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_modifications; ?></a></li>
                                <li><a href="<?php echo $installer; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_install; ?></a></li>
                                <li><a href="<?php echo $feeds; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_feeds; ?></a></li>
                            </ul>
                        </li>
                        <li><a class="top">
                                <i class="fa fa-cogs"></i> <Span><?php echo $menu_system; ?></span><i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $setting; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_setting; ?></a></li>
                                <li><a href="<?php echo $layout; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_layout; ?></a></li>
                                <li class="treeview">
                                    <a href="#">
                                        <i class="fa fa-globe"></i>
                                        <span><?php echo $menu_localisation; ?> </span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li><a href="<?php echo $country; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_country; ?></a></li>
                                        <li><a href="<?php echo $zone; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_zone; ?></a></li>
                                        <li><a href="<?php echo $currency; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_currency; ?></a></li>
                                        <li><a href="<?php echo $language; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_language; ?></a></li>
                                    </ul>
                                </li>
                                <li><a href="<?php echo $custom_field; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_custom_field; ?></a></li>
                                <li><a href="<?php echo $upload; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_upload; ?></a></li>
                                <li><a href="<?php echo $backup; ?>"><i class="fa fa-angle-double-right"></i> <?php echo $menu_backup; ?></a></li>
                            </ul>
                        </li>



                        <li><a href="<?php echo $logout; ?>"><i class="fa fa-lock"></i> <span><?php echo $menu_logout; ?></span></a></li>

                    </ul><!-- /.sidebar-menu -->
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">



