<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $title; ?></title>
        <base href="<?php echo $base; ?>" />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- Bootstrap 3.3.4 -->
        <link href="view/bootstrap/css/bootstrap.min.css,css/admin.css,css/skins.min.css,plugins/sweetalert/sweetalert.css" rel="stylesheet" type="text/css" />

        <!-- Font Awesome Icons -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->

        <!-- Custom CSS -->

        <?php foreach ($links as $link) { ?>
            <link href="<?php echo $link['href']; ?>" rel="<?php echo $link['rel']; ?>" />
        <?php } ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script type="text/javascript">
            /** Hack to make sure that inline code can reference $.ready style functionality **/
            var onReadyCallbacks = [];
            var docReady = function (callback) {
                onReadyCallbacks.push(callback);
            }

        </script>
    </head>
    <!--
    BODY TAG OPTIONS:
    =================
    Apply one or more of the following classes to get the
    desired effect
    |---------------------------------------------------------|
    | SKINS         | skin-blue                               |
    |               | skin-black                              |
    |               | skin-purple                             |
    |               | skin-yellow                             |
    |               | skin-red                                |
    |               | skin-green                              |
    |---------------------------------------------------------|
    |LAYOUT OPTIONS | fixed                                   |
    |               | layout-boxed                            |
    |               | layout-top-nav                          |
    |               | sidebar-collapse                        |
    |               | sidebar-mini                            |
    |---------------------------------------------------------|
    -->
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">

            <!-- Main Header -->
            <header class="main-header">

                <!-- Logo -->
                <a href="<?php echo $home; ?>" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini">CMS</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Core</b>CMS</span>
                </a>

                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only"><?php echo $text_toggle_navigation; ?></span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">

                            <?php foreach ($header_navs as $hnav): ?>
                                <?php if (empty($hnav['href'])): ?>


                                    <li class="dropdown notifications-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="<?php echo $hnav['icon']; ?>"></i>
                                            <?php if (isset($hnav['total'])): ?>
                                                <span class="label label-<?php echo $hnav['class']; ?>"><?php echo $hnav['total']; ?></span>
                                            <?php endif; ?>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php if ($hnav['title']): ?>
                                                <li class="header"><?php echo $hnav['title']; ?></li>
                                            <?php endif; ?>
                                            <li>
                                                <!-- inner menu: contains the actual data -->
                                                <ul class="menu">
                                                    <?php foreach ($hnav['items'] as $hitem): ?>
                                                        <li>
                                                            <a href="<?php echo $hitem['href']; ?>">
                                                                <?php if (isset($hitem['total'])): ?>
                                                                    <span class="label label-<?php echo $hitem['class']; ?>"><?php echo $hitem['total']; ?></span>
                                                                <?php endif; ?>
                                                                <?php echo $hitem['text']; ?>
                                                            </a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                <?php else: ?>
                                    <li class="dropdown notifications-menu">
                                        <a href="<?php echo $hnav['href']; ?>">
                                            <i class="<?php echo $hnav['icon']; ?>"></i>
                                            <?php if (isset($hnav['total'])): ?>
                                                <span class="label label-<?php echo $hnav['class']; ?>"><?php echo $hnav['total']; ?></span>
                                            <?php endif; ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>

                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="<?php echo $profile_img; ?>" class="user-image" alt="User Image"/>
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs"><?php echo $this->user->getFullName(); ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img src="<?php echo $profile_img; ?>" class="img-circle" alt="User Image" />
                                        <p>
                                            <?php echo $this->user->getFullName(); ?>
                                            <small>Member since <?php echo $member_since; ?></small>
                                        </p>
                                    </li>
                                    <!-- Menu Body -->

                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="<?php echo $member_profile; ?>" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?php echo $logout; ?>" class="btn btn-default btn-flat"><?php echo $text_logout; ?></a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>

                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">

                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">



                    <!-- Sidebar Menu -->
                    <ul class="sidebar-menu">
                        <li class="header">Navigation</li>
                        <!-- Optionally, you can add icons to the links -->

                        <?php

                        function menuTree($menu) {
                            if (empty($menu['icon'])) {
                                $menu['icon'] = 'fa-angle-double-right';
                            }

                            $menu['badge'] = empty($menu['badge']) ? '' : $menu['badge'];

                            if (!empty($menu['route'])) {
                                if (!registry('user')->hasPermission('access', $menu['route'])) {
                                    return;
                                }
                            } else {
                                if (!empty($menu['children'])) {

                                    $access = false;
                                    foreach ($menu['children'] as $rt) {
                                        if (empty($rt['route']) || registry('user')->hasPermission('access', $rt['route'])) {
                                            $access = true;
                                            break;
                                        }
                                    }
                                    if (!$access) {
                                        return;
                                    }
                                }
                            }

                            if (empty($menu['children'])) {
                                echo '<li><a href="' . $menu['href'] . '"><i class="fa ' . $menu['icon'] . '"></i> <span>' . $menu['label'] . '</span>' . $menu['badge'] . '</a></li>';
                            } else {
                                echo '<li class="treeview">
                                        <a href="#">
                                            <i class="fa ' . $menu['icon'] . '"></i>
                                            <span>' . $menu['label'] . '</span>
                                            <i class="fa fa-angle-left pull-right"></i>' . $menu['badge'] . '
                                        </a>
                                        <ul class="treeview-menu">';
                                foreach ($menu['children'] as $mchild) {
                                    menuTree($mchild);
                                }
                                echo '</ul></li>';
                            }
                        }
                        ?>

                        <?php if ($module_menu): ?>
                            <?php foreach ($module_menu as $mmenu): ?>
                                <?php menuTree($mmenu); ?>
                            <?php endforeach; ?>

                        <?php endif; ?>











                    </ul><!-- /.sidebar-menu -->
                </section>
                <!-- /.sidebar -->
            </aside>

            <aside class="control-sidebar control-sidebar-light">
                <!-- Create the tabs -->
                <ul class="nav nav-tabs nav-justified control-sidebar-tabs">

                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <!-- Home tab content -->
                    <div class="tab-pane" id="control-sidebar-home-tab">
                        <h3 class="control-sidebar-heading">Recent Activity</h3>
                        <ul class="control-sidebar-menu">
                            <li>
                                <a href="javascript:void(0)">
                                    <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                                        <p>Will be 23 on April 24th</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    <i class="menu-icon fa fa-user bg-yellow"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                                        <p>New phone +1(800)555-1234</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                                        <p>nora@example.com</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    <i class="menu-icon fa fa-file-code-o bg-green"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                                        <p>Execution time 5 seconds</p>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <!-- /.control-sidebar-menu -->

                        <h3 class="control-sidebar-heading">Tasks Progress</h3>
                        <ul class="control-sidebar-menu">
                            <li>
                                <a href="javascript:void(0)">
                                    <h4 class="control-sidebar-subheading">
                                        Custom Template Design
                                        <span class="label label-danger pull-right">70%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    <h4 class="control-sidebar-subheading">
                                        Update Resume
                                        <span class="label label-success pull-right">95%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    <h4 class="control-sidebar-subheading">
                                        Laravel Integration
                                        <span class="label label-warning pull-right">50%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    <h4 class="control-sidebar-subheading">
                                        Back End Framework
                                        <span class="label label-primary pull-right">68%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <!-- /.control-sidebar-menu -->

                    </div>
                    <!-- /.tab-pane -->

                </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">



