<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><?php echo $heading_title; ?>
        <?php if (!empty($subheading)): ?>
            <small><?php echo $subheading; ?></small>
        <?php endif; ?>
    </h1>
    <?php if (!empty($breadcrumbs)): ?>
        <ol class="breadcrumb">
            <?php foreach ($breadcrumbs as $_crumb): ?>
                <li><a href="<?php echo $_crumb['href']; ?>"><?php if (!empty($_crumb['separator']) && $_crumb['separator']): ?><i class="<?php echo $_crumb['separator']; ?>"></i><?php endif; ?> <?php echo $_crumb['text']; ?></a></li>

            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</section>
<?php if (isset($error_warning) && $error_warning) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $error_warning; ?>
    </div>
<?php } ?>
<?php if (isset($success) && $success) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $success; ?>
    </div>
<?php } ?>