<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">
      <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_insert; ?>">
                    <i class="fa fa-plus"></i>
                </a>
                <button class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                            $('#form').submit();
                        });" data-toggle="tooltip" title="<?php echo $button_delete; ?>">
                    <i class="fa fa-trash"></i>
                </button>
            </div>
        </div>
          
        <div class="box-body table-responsive">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                 <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                  <td class="text-left"><?php if ($sort == 'name') { ?>
                    <a href="<?php echo $sort_username; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_username; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_username; ?>"><?php echo $column_username; ?></a>
                    <?php } ?></td>
                  <td class="text-left"><?php if ($sort == 'status') { ?>
                    <a href="<?php echo $sort_status; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_status; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_status; ?>"><?php echo $column_status; ?></a>
                    <?php } ?></td>
                  <td class="text-left"><?php if ($sort == 'date_added') { ?>
                    <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                    <?php } else { ?>
                    <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                    <?php } ?></td>
                  <td class="text-right"><?php echo $column_action; ?></td>
                </tr>
              </thead>
              <tbody>
                <?php if ($apis) { ?>
                <?php foreach ($apis as $api) { ?>
                <tr>
                  <td class="text-center"><?php if (in_array($api['api_id'], $selected)) { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $api['api_id']; ?>" checked="checked" />
                    <?php } else { ?>
                    <input type="checkbox" name="selected[]" value="<?php echo $api['api_id']; ?>" />
                    <?php } ?></td>
                  <td class="text-left"><?php echo $api['username']; ?></td>
                  <td class="text-left"><?php echo $api['status']; ?></td>
                  <td class="text-left"><?php echo $api['date_added']; ?></td>
                  <td class="text-right"><a href="<?php echo $api['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                  <td class="text-center" colspan="5"><?php echo $text_no_results; ?></td>
                </tr>
                <?php } ?>
              </tbody>
              <tfoot>
                  <tr><td colspan="5"><?php echo $pagination; ?></td></tr>
              </tfoot>
                </table>

            </form>
        </div>
        <div clas="box-footer">
               
        </div>
    </div>
</section><!-- /.content -->

<?php echo $footer; ?>