<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>


<!-- Main content -->
<section class="content">


    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>

            <div class="box-tools pull-right">
                <button  type="submit" form="form-api" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_save; ?>">
                    <i class="fa fa-save"></i>
                </button>

                <a href="<?php echo $cancel; ?>" class="btn btn-default" title="<?php echo $button_cancel; ?>"  data-toggle="tooltip">
                    <i class="fa fa-reply"></i> 
                </a>
            </div>
        </div>

        <div class="box-body">



            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-api" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-username"><?php echo $entry_username; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="username" value="<?php echo $username; ?>" placeholder="<?php echo $entry_username; ?>" id="input-username" class="form-control" />
                        <?php if ($error_username) { ?>
                            <div class="text-danger"><?php echo $error_username; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-password"><?php echo $entry_password; ?></label>
                    <div class="col-sm-10">
                        <textarea name="password" placeholder="<?php echo $entry_password; ?>" rows="5" id="input-password" class="form-control"><?php echo $password; ?></textarea>
                        <br />
                        <button type="button" id="button-generate" class="btn btn-primary"><i class="fa fa-refresh"></i> <?php echo $button_generate; ?></button>
                        <?php if ($error_password) { ?>
                            <div class="text-danger"><?php echo $error_password; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="status" id="input-status" class="form-control">
                            <?php if ($status) { ?>
                                <option value="0"><?php echo $text_disabled; ?></option>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                            <?php } else { ?>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                <option value="1"><?php echo $text_enabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>

        </div>
    </div>
</section><!-- /.content -->
<script type="text/javascript"><!--
    docReady(function () {
        $('#button-generate').on('click', function () {
            rand = '';

            string = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

            for (i = 0; i < 256; i++) {
                rand += string[Math.floor(Math.random() * (string.length - 1))];
            }

            $('#input-password').val(rand);
        });
    });
//-->
</script>


<?php echo $footer; ?>