<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title><?php echo $title; ?></title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <base href="<?php echo $base; ?>" />
        <!-- bootstrap 3.0.2 -->
        <link href="view/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

        <!-- Theme style -->
        <link href="view/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <link href="view/css/pages/loginreg.css" rel="stylesheet" type="text/css" />

        <style>
            html{
                background: url(view/img/8.jpg) no-repeat center center fixed;
                background-size: 100% 100%;
            }
            body.bg-black {
                background-color: transparent !important; }
            </style>
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
              <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
            <![endif]-->
        </head>
        <body class="bg-black">

        <div class="form-box" id="login-box">
            <div class="header"><?php echo $heading_title; ?></div>

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="forgotten">

                <div class="body bg-gray">

                    <?php if ($error_warning) { ?>
                        <div class="alert alert-danger"><?php echo $error_warning; ?></div>
                    <?php } ?>
                    <p><?php echo $text_email; ?></p>
                    <div class="form-group">
                        <input type="email" name="email" value="<?php echo $email; ?>" class="form-control" placeholder="<?php echo $entry_email; ?>" />
                    </div>         

                </div>

                <div class="footer clearfix">                                                               
                    <button type="submit" class="btn btn-primary col-md-6"><?php echo $button_reset; ?></button>
                    <a href="<?php echo $cancel; ?>" class="btn btn-default col-md-6"><?php echo $button_cancel; ?></a>
                </div>

            </form>
        </div>

        <script src="view/plugins/jQuery/jQuery-2.1.3.min.js"></script>
        <!-- Bootstrap -->
        <script src="view/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>


    </body>
</html>