<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title><?php echo $title; ?></title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <base href="<?php echo $base; ?>" />
        <!-- bootstrap 3.0.2 -->
        <link href="view/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

        <!-- Theme style -->
        <link href="view/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <link href="view/css/pages/loginreg.css" rel="stylesheet" type="text/css" />

        <style>
            html{
                background: url(view/img/8.jpg) no-repeat center center fixed;
                background-size: 100% 100%;
            }
            body.bg-black {
                background-color: transparent !important; }
            </style>
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
              <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
            <![endif]-->
        </head>
        <body class="bg-black">

        <div class="form-box" id="login-box">
            <div class="header"><?php echo $text_login; ?></div>
            <form action="<?php echo $action; ?>" method="post">
                <?php if($redirect):?>
                <input type="hidden" name="redirect" value="<?php echo $redirect; ?>" />
                <?php endif; ?>
                <div class="body bg-gray">
                    <?php if ($error_warning): ?>
                        <div class="alert alert-danger">
                            <?php echo $error_warning; ?>
                        </div>
                    <?php endif; ?>

                    <?php if ($success): ?>
                        <div class="alert alert-success">
                            <?php echo $success; ?>
                        </div>
                    <?php endif; ?>
                    <div class="form-group has-feedback">
                        <input type="text" name="username" class="form-control" placeholder="<?php echo $entry_username; ?>"/>
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" name="password" class="form-control" placeholder="<?php echo $entry_password; ?>"/>
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>       
                </div>
                <div class="footer clearfix">  
                    <a href="<?php echo $forgotten; ?>" class=" btn btn-default col-md-6"><?php echo $text_forgotten; ?></a>
                    <button type="submit" class="btn btn-primary col-md-6"><?php echo $button_login; ?></button>  
                </div>
            </form>


        </div>

        <script src="view/plugins/jQuery/jQuery-2.1.3.min.js"></script>
        <!-- Bootstrap -->
        <script src="view/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>


    </body>
</html>