<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>



<!-- Main content -->
<section class="content">

    <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">
         <div class="box box-theme">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>

                <div class="box-tools pull-right">
                    <button class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_save; ?>">
                        <i class="fa fa-save"></i>
                    </button>
                 
                    <a href="<?php echo $cancel; ?>" class="btn btn-default" title="<?php echo $button_cancel; ?>"  data-toggle="tooltip">
                        <i class="fa fa-reply"></i> 
                    </a>
                </div>
            </div>
            <div class="box-body">
                <div class="form-group">
                    <label for="nameInput" class="col-sm-2 control-label required"><?php echo $entry_name; ?></label>
                    <div class="col-sm-9">
                        <input type="text" name="name" value="<?php echo $name; ?>" class="form-control required" id="nameInput" />
                        <?php if ($error_name) { ?>
                            <span class="error text-danger"><?php echo $error_name; ?></span>
                        <?php } ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <label for="accessInput" class="col-sm-12"><?php echo $entry_access; ?></label>
                        <div class="col-sm-12">
                            <div class="scrollbox">
                                <ul class="list-group">
                                    <?php $class = 'odd'; ?>
                                    <?php foreach ($permissions as $permission => $ptitle) : ?>
                                        <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                        <li class="list-group-item <?php echo $class; ?>">
                                            <?php if (in_array($permission, $access)) { ?>
                                                <input type="checkbox" name="permission[access][]" value="<?php echo $permission; ?>" checked="checked" />
                                                <?php echo $ptitle; ?>
                                            <?php } else { ?>
                                                <input type="checkbox" name="permission[access][]" value="<?php echo $permission; ?>" />
                                                <?php echo $ptitle; ?>
                                            <?php } ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <a onclick="$(this).parent().find(':checkbox').prop('checked', 'checked');" class="btn btn-sm"><?php echo $text_select_all; ?></a> / <a class="btn btn-sm" onclick="$(this).parent().find(':checkbox').prop('checked',false);"><?php echo $text_unselect_all; ?></a>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <label for="modifyInput" class="col-sm-12"><?php echo $entry_modify; ?></label>
                        <div class="col-sm-12">
                            <div class="scrollbox">
                                <ul class="list-group">
                                    <?php $class = 'odd'; ?>
                                    <?php foreach ($permissions as $permission => $ptitle) : ?>
                                        <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                        <li class="list-group-item <?php echo $class; ?>">
                                            <?php if (in_array($permission, $modify)) { ?>
                                                <input type="checkbox" name="permission[modify][]" value="<?php echo $permission; ?>" checked="checked" />
                                                <?php echo $ptitle; ?>
                                            <?php } else { ?>
                                                <input type="checkbox" name="permission[modify][]" value="<?php echo $permission; ?>" />
                                                <?php echo $ptitle; ?>
                                            <?php } ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <a onclick="$(this).parent().find(':checkbox').prop('checked', 'checked');" class="btn btn-sm"><?php echo $text_select_all; ?></a> / <a class="btn btn-sm" onclick="$(this).parent().find(':checkbox').prop('checked',false);"><?php echo $text_unselect_all; ?></a>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </form>

</section><!-- /.content -->

<?php echo $footer; ?>