<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $insert; ?>" class="btn btn-app">
        <i class="fa fa-plus text-green"></i> <?php echo $button_insert; ?>
    </a>
    <button class="btn btn-app" onclick="$('#form').submit();">
        <i class="fa fa-times text-red"></i> <?php echo $button_delete; ?>
    </button>
        </div>
        <div class="box-body table-responsive">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                            <th class="left"><?php if ($sort == 'username') { ?>
                                    <a href="<?php echo $sort_username; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_username; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_username; ?>"><?php echo $column_username; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'status') { ?>
                                    <a href="<?php echo $sort_status; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_status; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_status; ?>"><?php echo $column_status; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'date_added') { ?>
                                    <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                                <?php } ?></th>
                            <th class="text-right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($users) { ?>
                            <?php foreach ($users as $user) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($user['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user['user_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user['user_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $user['username']; ?></td>
                                    <td class="left"><?php echo $user['status']; ?></td>
                                    <td class="left"><?php echo $user['date_added']; ?></td>
                                    <td class="text-right"><?php foreach ($user['action'] as $action) { ?>
                                            <a class="btn btn-xs btn-primary" href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a>
                                        <?php } ?></td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="5"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

            </form>
        </div>
        <div clas="box-footer">
                <div class="pagination-container row">
                    <?php echo $pagination; ?>
                </div>
        </div>
    </div>
</section><!-- /.content -->

<?php echo $footer; ?>