<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">
    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_insert; ?>">
                    <i class="fa fa-plus"></i>
                </a>
                <button class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                            $('#form').submit();
                        });" data-toggle="tooltip" title="<?php echo $button_delete; ?>">
                    <i class="fa fa-trash"></i>
                </button>
            </div>
        </div>

        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                            <th class="left"><?php if ($sort == 'name') { ?>
                                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
<?php } ?></th>
                            <th class="text-right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
<?php if ($user_groups) { ?>
    <?php foreach ($user_groups as $user_group) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($user_group['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user_group['user_group_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user_group['user_group_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $user_group['name']; ?></td>
                                    <td class="text-right">
                                        <?php foreach ($user_group['action'] as $action) { ?>
                                            <a target="<?php echo (!empty($action['target'])) ? $action['target'] : '_self'; ?>" class="btn btn-sm btn-<?php echo $action['class']; ?>" href="<?php echo $action['href']; ?>" data-toggle="tooltip" title="<?php echo $action['text']; ?>"><i class="<?php echo $action['icon']; ?>"></i></a>
        <?php } ?>

                                    </td>
                                </tr>
    <?php } ?>
<?php } else { ?>
                            <tr>
                                <td class="center" colspan="3"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
<?php } ?>
                    </tbody>
                    <tfoot><tr>
                                <td class="center" colspan="3"><?php echo $pagination; ?></td>
                            </tr></tfoot>
                </table>
            </form>
        </div>
    </div>

</section><!-- /.content -->

<?php echo $footer; ?>