<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $insert; ?>" class="btn btn-app">
                <i class="fa fa-plus text-green"></i> <?php echo $button_insert; ?>
            </a>
            <button class="btn btn-app" onclick="$('#form').submit();">
                <i class="fa fa-times text-red"></i> <?php echo $button_delete; ?>
            </button>
        </div>
        <div class="box-body">
            
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                            <th class="left"><?php if ($sort == 'name') { ?>
                                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                <?php } ?></th>
                            <th class="text-right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($user_groups) { ?>
                            <?php foreach ($user_groups as $user_group) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($user_group['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user_group['user_group_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user_group['user_group_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $user_group['name']; ?></td>
                                    <td class="text-right"><?php foreach ($user_group['action'] as $action) { ?>
                                            <a class="btn btn-xs btn-primary" href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a>
                                        <?php } ?></td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="3"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </form>
        </div>
       <div clas="box-footer">
                <div class="pagination-container row">
                    <?php echo $pagination; ?>
                </div>
        </div>
    </div>

</section><!-- /.content -->

<?php echo $footer; ?>