<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $heading_title; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_insert; ?>">
                    <i class="fa fa-plus"></i>
                </a>
                <button class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                            $('#form').submit();
                        });" data-toggle="tooltip" title="<?php echo $button_delete; ?>">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body table-responsive">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                            <th class="left"><?php if ($sort == 'username') { ?>
                                    <a href="<?php echo $sort_username; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_username; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_username; ?>"><?php echo $column_username; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'status') { ?>
                                    <a href="<?php echo $sort_status; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_status; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_status; ?>"><?php echo $column_status; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'date_added') { ?>
                                    <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                                <?php } ?></th>
                            <th class="text-right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($users) { ?>
                            <?php foreach ($users as $user) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($user['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user['user_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $user['user_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $user['username']; ?></td>
                                    <td class="left"><?php echo $user['status']; ?></td>
                                    <td class="left"><?php echo $user['date_added']; ?></td>
                                    <td class="text-right"><?php foreach ($user['action'] as $action) { ?>

                                                <a href="<?php echo $action['href']; ?>" data-toggle="tooltip"  title="<?php echo $action['text']; ?>" class="btn btn-<?php echo $action['class']; ?>"><i class="<?php echo $action['icon']; ?>"></i></a>

                                            <?php } ?>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="5"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                    <tfoot>
                        <tr><td colspan="5"><?php echo $pagination; ?></td></tr>
                    </tfoot>
                </table>

            </form>
        </div>

    </div>
</section><!-- /.content -->

<?php echo $footer; ?>