<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header">

            <h3 class="box-title"><i class="fa fa-bars"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right"> 
                <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-success"><i class="fa fa-plus"></i></a>
                <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                            $('#form-module').submit();
                        });"><i class="fa fa-trash-o"></i></button>
            </div>
        </div>
        <div class="box-body">
            <div class="well">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label" for="input-name"><?php echo $entry_name; ?></label>
                            <input type="text" name="filter_name" value="<?php echo $filter_name; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label" for="input-date-added"><?php echo $entry_date_added; ?></label>
                            <div class="input-group date">
                                <input type="text" name="filter_date_added" value="<?php echo $filter_date_added; ?>" placeholder="<?php echo $entry_date_added; ?>" data-date-format="YYYY-MM-DD" class="form-control" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                </span></div>
                        </div>
                        <button type="button" id="button-filter" class="btn btn-primary pull-right"><i class="fa fa-search"></i> <?php echo $button_filter; ?></button>


                    </div>
                </div>
            </div>



            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-module" class="form-horizontal">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr>
                                <td width="1" style="text-align: center;"><input type="checkbox" onclick="$('input[name*=\'selected\']').attr('checked', this.checked);" /></td>
                                <td class="text-left"><?php echo $text_title; ?></td>
                                <td class="text-left"><?php echo $text_date; ?></td>
                                <td class="text-right"><?php echo $text_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($all_faq) { ?>
                                <?php foreach ($all_faq as $faq) { ?>
                                    <tr>
                                        <td width="1" style="text-align: center;"><input type="checkbox" name="selected[]" value="<?php echo $faq['faq_id']; ?>" /></td>
                                        <td class="text-left"><?php echo $faq['question']; ?></td>
                                        <td class="text-left"><?php echo $faq['date_added']; ?></td>
                                        <td class="text-right"><a href="<?php echo $faq['edit']; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td colspan="5" class="text-center"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr><td colspan="5"><?php echo $pagination; ?></td></tr>
                        </tfoot>
                    </table>
                </div>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript"><!--
    docReady(function () {
        $('#button-filter').on('click', function () {
            url = 'index.php?route=extension/faq&token=<?php echo $token; ?>';

            var filter_name = $('input[name=\'filter_name\']').val();

            if (filter_name) {
                url += '&filter_name=' + encodeURIComponent(filter_name);
            }


            var filter_date_added = $('input[name=\'filter_date_added\']').val();

            if (filter_date_added) {
                url += '&filter_date_added=' + encodeURIComponent(filter_date_added);
            }

            location = url;
        });


        $('.date').datetimepicker({
            pickTime: false
        });
    });
//--></script>

<?php echo $footer; ?>
