<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header">

            <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $text_layout; ?>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        </div>
        <div class="box-body table-responsive">
                <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-module" class="form-horizontal">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <td class="text-left"><?php echo $column_name; ?></td>
                                    <td class="text-right"><?php echo $column_action; ?></td>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($extensions) { ?>
                                    <?php foreach ($extensions as $extension) { ?>
                                        <tr>
                                            <td><?php echo $extension['name']; ?></td>
                                            <td class="text-right"><?php if (!$extension['installed']) { ?>
                                                    <a href="<?php echo $extension['install']; ?>" data-toggle="tooltip" title="<?php echo $button_install; ?>" class="btn btn-success"><i class="fa fa-plus-circle"></i></a>
                                                <?php } else { ?>
                                                    <a onclick="confirm('<?php echo $text_confirm; ?>') ? location.href = '<?php echo $extension['uninstall']; ?>' : false;" data-toggle="tooltip" title="<?php echo $button_uninstall; ?>" class="btn btn-danger"><i class="fa fa-minus-circle"></i></a>
                                                <?php } ?>
                                                <?php if ($extension['installed']) { ?>
                                                    <a href="<?php echo $extension['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                                                <?php } else { ?>
                                                    <button type="button" class="btn btn-primary" disabled="disabled"><i class="fa fa-pencil"></i></button>
                                                <?php } ?></td>
                                        </tr>
                                        <?php foreach ($extension['module'] as $module) { ?>
                                            <tr>
                                                <td class="text-left"><?php echo $module['name']; ?></td>
                                                <td class="text-right"><a href="<?php echo $module['copy']; ?>" data-toggle="tooltip" title="<?php echo $button_copy; ?>" class="btn btn-default"><i class="fa fa-copy"></i></a> <a onclick="confirm('<?php echo $text_confirm; ?>') ? location.href = '<?php echo $module['delete']; ?>' : false;" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger"><i class="fa fa-trash-o"></i></a> <a href="<?php echo $module['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                <?php } else { ?>
                                    <tr>
                                        <td class="text-center" colspan="2"><?php echo $text_no_results; ?></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </form>
        </div>
    </div>
</section>

<?php echo $footer; ?>
