<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="not-ie no-js">
    <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
        <title><?php echo $title; ?></title>

        <meta name="author" content="OmniHostNZ">
        <base href="<?php echo $base; ?>" />
        <!-- Custom META -->

        <link rel="stylesheet" href="view/plugins/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="view/plugins/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="view/plugins/animate/animate.css" media="screen"/>
        <link rel="stylesheet" href="view/template/default/assets/css/style.css" media="screen"/>
        <!-- Custom CSS -->
        <link rel="stylesheet" href="view/template/default/assets/css/custom-skin.css" media="screen"/>



        <script type="text/javascript">
            /** Hack to make sure that inline code can reference $.ready style functionality **/
            var onReadyCallbacks = [];
            var docReady = function (callback) {
                onReadyCallbacks.push(callback);
            }

        </script>
    </head>
    <body>

        <div class="body-wrapper">
            <div class="frame">


                <div id="layout" class="fullwidth">
                    <section id="login" class="content section-grey" style="background: url(view/img/pixel_weave.png) repeat;">
                        <div class="container">
                            <div class="row">

                                <div class="col-sm-12">
                                    <?php if ($success) { ?>
                                        <div class="alert alert-success"><i class="fa fa-check-circle"></i> <?php echo $success; ?></div>
                                    <?php } ?>
                                    <?php if ($error_warning) { ?>
                                        <div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> <?php echo $error_warning; ?></div>
                                    <?php } ?>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <?php if ($account_register): ?>
                                                <div class="well">
                                                    <h4 class="heading text-center"><?php echo $text_new_customer; ?></h4>
                                                    <h6><?php echo $text_register; ?></h6>
                                                    <p><?php echo $text_register_account; ?></p>
                                                    <a target="_parent" href="<?php echo $register; ?>" class="btn btn-primary"><?php echo $button_continue; ?></a></div>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="well">
                                                <h4 class="heading text-center"><?php echo $text_returning_customer; ?></h4>

                                                <h6><?php echo $text_i_am_returning_customer; ?></h6>
                                                <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
                                                    <div class="form-group">
                                                        <label class="control-label" for="input-email"><?php echo $entry_email; ?></label>
                                                        <input type="emaiul" name="email" value="<?php echo $email; ?>" placeholder="<?php echo $entry_email; ?>" id="input-email" class="form-control" />
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="control-label" for="input-password"><?php echo $entry_password; ?></label>
                                                        <input type="password" name="password" value="<?php echo $password; ?>" placeholder="<?php echo $entry_password; ?>" id="input-password" class="form-control" />
                                                        <a target="_parent" href="<?php echo $forgotten; ?>"><?php echo $text_forgotten; ?></a></div>
                                                    <?php if ($remember_me): ?>
                                                        <div class="form-group">
                                                            <label for="input-remember">
                                                                <input type="checkbox" name="remember_me" id="input-remember" value="remember_checked" /> <?php echo $text_remember_me; ?>
                                                            </label>
                                                        </div>
                                                    <?php endif; ?>
                                                    <input type="submit" value="<?php echo $button_login; ?>" class="btn btn-primary" />
                                                    <?php if ($redirect) { ?>
                                                        <input type="hidden" name="redirect" value="<?php echo $redirect; ?>" />
                                                    <?php } ?>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                </div><!-- end col-4 -->


                            </div><!-- end row -->
                        </div><!-- end container -->
                    </section>
                </div>
            </div>
        </div>
        <!--[if lt IE 9]>
<script src="view/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="view/plugins/jquery/jquery-migrate-1.2.1.min.js"></script>
<script src="view/plugins/jquery/jquery.placeholder.js"></script>
<![endif]-->
        <!--[if (gte IE 9) | (!IE)]><!-->
        <script src="view/plugins/jquery/jquery-2.1.4.min.js"></script>
        <!--<![endif]-->
        <script src="view/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="view/plugins/main.js"></script>
        <!-- Custom JS -->
        <!-- THE ABOVE TAG IS REPLACED WITH ANY JS SCRIPTS THAT ARE REQUESTED!!!! -->

        <script type="text/javascript" src="view/template/default/assets/js/site.js"></script>

    </body>
</html>