<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">
    
    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>
            <div class="box-tools pull-right">
                
                  <button type="submit" form="form-banner" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      
                
                
            </div>
            <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-banner" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="name" value="<?php echo $name; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                        <?php if ($error_name) { ?>
                            <div class="text-danger"><?php echo $error_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-name"><?php echo $entry_description; ?></label>
                    <div class="col-sm-10">
                        <textarea name="description" placeholder="<?php echo $entry_description; ?>" id="input-description" class="form-control" rows="5"><?php echo $description; ?></textarea>
                        <?php if ($error_name) { ?>
                            <div class="text-danger"><?php echo $error_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="status" id="input-status" class="form-control">
                            <?php if ($status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="table-responsive">
                <table id="images" class="table table-striped table-bordered table-hover table-vert-middle">
                    <thead>
                        <tr>
                            <td class="text-left"><?php echo $entry_title; ?></td>
                            <td class="text-left"><?php echo $entry_description; ?></td>
                            <td class="text-left"><?php echo $entry_link; ?></td>
                            <td class="text-center"><?php echo $entry_image; ?></td>
                            <td class="text-right"><?php echo $entry_sort_order; ?></td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $image_row = 0; ?>
                        <?php foreach ($banner_images as $banner_image) { ?>
                            <tr id="image-row<?php echo $image_row; ?>">
                                <td class="text-left">
                                    <input type="text" name="banner_image[<?php echo $image_row; ?>][title]" value="<?php echo $banner_image['title']; ?>" placeholder="<?php echo $entry_title; ?>" class="form-control" />

                                    <?php if (isset($error_banner_image[$image_row]['title'])) { ?>
                                        <div class="text-danger"><?php echo $error_banner_image[$image_row]['title']; ?></div>

                                    <?php } ?></td>
                                <td class="text-left"><textarea name="banner_image[<?php echo $image_row; ?>][description]" placeholder="<?php echo $entry_description; ?>" class="form-control" rows="3"><?php echo $banner_image['description']; ?></textarea></td>
                                <td class="text-left"><input type="text" name="banner_image[<?php echo $image_row; ?>][link]" value="<?php echo $banner_image['link']; ?>" placeholder="<?php echo $entry_link; ?>" class="form-control" /></td>
                                <td class="text-center"><a href="" id="thumb-image<?php echo $image_row; ?>" data-toggle="image" class="img-thumbnail"><img src="<?php echo $banner_image['thumb']; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a>
                                    <input type="hidden" name="banner_image[<?php echo $image_row; ?>][image]" value="<?php echo $banner_image['image']; ?>" id="input-image<?php echo $image_row; ?>" /></td>
                                <td class="text-right"><input size="1" type="text" name="banner_image[<?php echo $image_row; ?>][sort_order]" value="<?php echo $banner_image['sort_order']; ?>" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>
                                <td class="text-left"><button type="button" onclick="$('#image-row<?php echo $image_row; ?>').remove();" data-toggle="tooltip" title="<?php echo $button_remove; ?>" class="btn btn-danger"><i class="fa fa-minus-circle"></i></button></td>
                            </tr>
                            <?php $image_row++; ?>
                        <?php } ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5"></td>
                            <td class="text-left">
                                <button type="button" onclick="addImage();" data-toggle="tooltip" title="<?php echo $button_banner_add; ?>" class="btn btn-primary"><i class="fa fa-plus-circle"></i></button>
                                
                            </td>
                        </tr>
                    </tfoot>
                </table>
                    </div>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript"><!--
var image_row = <?php echo $image_row; ?>;

    function addImage() {
        html = '<tr id="image-row' + image_row + '">';
        html += '  <td class="text-left">';
            html += ' <input type="text" name="banner_image[' + image_row + '][title]" value="" placeholder="<?php echo $entry_title; ?>" class="form-control" />';
   
        html += '  </td>';
        html += '  <td class="text-left">';
            html += ' <textarea name="banner_image[' + image_row + '][description]" placeholder="<?php echo $entry_description; ?>" class="form-control" rows="3"></textarea>';
   
        html += '  </td>';
        html += '  <td class="text-left"><input type="text" name="banner_image[' + image_row + '][link]" value="" placeholder="<?php echo $entry_link; ?>" class="form-control" /></td>';
        html += '  <td class="text-center"><a href="" id="thumb-image' + image_row + '" data-toggle="image" class="img-thumbnail"><img src="<?php echo $placeholder; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a><input type="hidden" name="banner_image[' + image_row + '][image]" value="" id="input-image' + image_row + '" /></td>';
        html += '  <td class="text-right"><input size="1" type="text" name="banner_image[' + image_row + '][sort_order]" value="" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>';
        html += '  <td class="text-left"><button type="button" onclick="$(\'#image-row' + image_row + '\').remove();" data-toggle="tooltip" title="<?php echo $button_remove; ?>" class="btn btn-danger"><i class="fa fa-minus-circle"></i></button></td>';
        html += '</tr>';

        $('#images tbody').append(html);

        image_row++;
    }
//--></script></div>
<?php echo $footer; ?>