<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" data-toggle="tooltip" title="<?php echo $button_insert; ?>" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_insert; ?>"><i class="fa fa-plus"></i></a>
                <button id="upload-g-folder" data-toggle="tooltip" title="<?php echo $button_insert_folder; ?>" class="btn btn-success"><i class="fa fa-folder-open"></i></button>
                   
            <button class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                            $('#form-banner').submit();
                        });" data-toggle="tooltip" title="<?php echo $button_delete; ?>">
                <i class="fa fa-trash"></i>
            </button>
        </div>
            </div>

        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-banner">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                                <td class="text-left"><?php if ($sort == 'name') { ?>
                                        <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                    <?php } ?></td>
                                <td class="text-left"><?php if ($sort == 'status') { ?>
                                        <a href="<?php echo $sort_status; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_status; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_status; ?>"><?php echo $column_status; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($banners) { ?>
                                <?php foreach ($banners as $banner) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($banner['banner_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $banner['banner_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $banner['banner_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $banner['name']; ?></td>
                                        <td class="text-left"><?php echo $banner['status']; ?></td>
                                        <td class="text-right"><a href="<?php echo $banner['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="4"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="4"><?php echo $pagination; ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>
<div id="upload-progress" class="hide" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; background-color: rgba(100, 100, 100, .8); z-index: 99999;">
    <table style="width: 80%; height: 100%; margin: auto;">
        <tr>
            <td style="vertical-align: middle;">
                <div class="progress">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">0%</div>
                </div>
            </td>
        </tr>
    </table>
</div>

<script>

    var $folderName;
    var $galleryName;

    docReady(function () {



        $(document).on("click", '#button-upload', function () {
            $('#form-upload').remove();

            $('.content-wrapper').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="file[]" multiple="multiple" /></form>');

            $('#form-upload input[name=\'file[]\']').trigger('click');

            timer = setInterval(function () {
                if ($('#form-upload input[name=\'file[]\']').val() != '') {
                    clearInterval(timer);

                    $.ajax({
                        url: 'index.php?p=common/filemanager/upload&token=<?php echo $this->session->data['token']; ?>&directory=' + $folderName,
                        type: 'post',
                        dataType: 'json',
                        data: new FormData($('#form-upload')[0]),
                        cache: false,
                        contentType: false,
                        processData: false,
                        beforeSend: function () {
                            //     $('#button-upload i').replaceWith('<i class="fa fa-circle-o-notch fa-spin"></i>');
                            //     $('#button-upload').prop('disabled', true);
                            $('#upload-progress').removeClass('hide');
                        },
                        complete: function () {
                            //     $('#button-upload i').replaceWith('<i class="fa fa-upload"></i>');
                            //     $('#button-upload').prop('disabled', false);
                            $('#upload-progress').addClass('hide');
                        },
                        success: function (json) {
                            if (json['error']) {
                                alert(json['error']);
                            }

                            if (json['success']) {
                                //alert(json['success']);

                                // $('#button-refresh').trigger('click');
                                var pdata = {
                                    name: $galleryName,
                                    status: '1',
                                    banner_image: {}
                                };
                                var bidx = 0;
                                console.log(json);
                                $(json.files).each(function (i, j) {
                                    console.log(j);
                                    pdata.banner_image[bidx] = {
                                        title: $galleryName,
                                        description: '',
                                        link: '',
                                        sort_order: bidx++,
                                        image: 'uploads/' + $folderName + '/' + j
                                    };
                                });
                                //console.log(pdata);
                                $.redirect('index.php?p=cms/banner/add&json=1&token=<?php echo $this->session->data['token']; ?>', pdata);
                                //    $.post('index.php?p=cms/banner/add&json=1&token=<?php echo $this->session->data['token']; ?>',pdata,function(res) { 
                                //         $(document).html(res);
                                //      });
                            }
                        },
                        xhr: function () {
                            var xhr = new window.XMLHttpRequest();

                            xhr.upload.addEventListener("progress", function (evt) {
                                if (evt.lengthComputable) {
                                    var percentComplete = evt.loaded / evt.total;
                                    percentComplete = parseInt(percentComplete * 100);
                                    console.log(percentComplete);
                                    $('.progress-bar').html(percentComplete + '%').attr('aria-valuenow', percentComplete).css('width', percentComplete + '%');
                                }
                            }, false);

                            return xhr;
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                        }
                    });
                }
            }, 500);
        });

        $(document).on("click", "#upload-g-folder", function () {
            swal({
                title: "Add Gallery",
                text: "Enter Gallery Name for the New Gallery",
                type: "input",
                showCancelButton: true,
                closeOnConfirm: false,
                animation: "slide-from-top",
                inputPlaceholder: "folder Name"
            }, function (inputValue) {
                if (inputValue === false)
                    return false;
                if (inputValue === "") {
                    swal.showInputError("You need to name the gallery!");
                    return false
                }

                $galleryName = inputValue;
                $folderName = slugify(inputValue);
                //swal("Nice!", "You wrote: " + inputValue, "success");
                $.ajax({
                    url: 'index.php?p=common/filemanager/folder&token=<?php echo $this->session->data['token']; ?>',
                    type: 'post',
                    dataType: 'json',
                    data: 'name=' + $folderName,
                    success: function (json) {
                        if (json['error']) {
                            alert(json['error']);
                        }

                        if (json['success']) {

                            swal({showConfirmButton: false, title: "Folder Created!", text: '<button id="button-upload" class="btn btn-primary btn-lg">Add Images</button>', html: true});




                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                    }
                });
            });
        });
    });

</script>

<?php echo $footer; ?>

