<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>
<!-- Main content -->
<section class="content">

    <div class="box box-theme">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>
             <div class="box-tools pull-right">
            <button type="submit" form="form-review" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a>
             </div>
        </div>
        <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-review" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-author"><?php echo $entry_author; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="author" value="<?php echo $author; ?>" placeholder="<?php echo $entry_author; ?>" id="input-author" class="form-control" />
                        <?php if ($error_author) { ?>
                            <div class="text-danger"><?php echo $error_author; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-page"><span data-toggle="tooltip" title="<?php echo $help_page; ?>"><?php echo $entry_page; ?></span></label>
                    <div class="col-sm-10">
                        <input type="text" name="ams_page" value="<?php echo $ams_page; ?>" placeholder="<?php echo $entry_page; ?>" id="input-page" class="form-control" />
                        <input type="hidden" name="ams_page_id" value="<?php echo $ams_page_id; ?>" />
                        <?php if ($error_page) { ?>
                            <div class="text-danger"><?php echo $error_page; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-text"><?php echo $entry_text; ?></label>
                    <div class="col-sm-10">
                        <textarea name="text" cols="60" rows="8" placeholder="<?php echo $entry_text; ?>" id="input-text" class="form-control"><?php echo $text; ?></textarea>
                        <?php if ($error_text) { ?>
                            <dspan class="text-danger">
                                <?php echo $error_text; ?></span>
                            <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                    <div class="col-sm-10">
                        <select name="status" id="input-status" class="form-control">
                            <?php if ($status) { ?>
                                <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <option value="0"><?php echo $text_disabled; ?></option>
                            <?php } else { ?>
                                <option value="1"><?php echo $text_enabled; ?></option>
                                <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript"><!--
    docReady(function () {
$('input[name=\'ams_page\']').autocomplete({
        'source': function (request, response) {
            $.ajax({
                url: 'index.php?p=cms/page/autocomplete&token=<?php echo $token; ?>&filter_name=' + encodeURIComponent(request.term),
                dataType: 'json',
                success: function (json) {
                    console.log(json);
                    response($.map(json, function (item) {
                        return {
                            label: item['name'],
                            value: item['ams_page_id']
                        }
                    }));
                }
            });
        },
        'select': function (ev,ui) {
            $('input[name=\'ams_page\']').val(ui.item.label);
            $('input[name=\'ams_page_id\']').val(ui.item.value);
            return false;
        }
    });
    });
    //--></script>
<?php echo $footer; ?>