<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>
<?php /* look at http://www.plupload.com/ */ ?>
<!-- Main content -->
<section class="content">

    <div class="box theme">
        <div class="box-header ">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_edit; ?></h3>
             <div class="box-tools pull-right">
            <button type="submit" form="form-download" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-success"><i class="fa fa-save"></i></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
        </div>
        <div class="box-body">
            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-download" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label"><?php echo $entry_name; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="name" value="<?php echo $name; ?>" placeholder="<?php echo $entry_name; ?>" class="form-control" />

                        <?php if ($error_name) { ?>
                            <div class="text-danger"><?php echo $error_name; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-filename"><span data-toggle="tooltip" title="<?php echo $help_filename; ?>"><?php echo $entry_filename; ?></span></label>
                    <div class="col-sm-10">
                        <div class="input-group">
                            <input type="text" name="filename" value="<?php echo $filename; ?>" placeholder="<?php echo $entry_filename; ?>" id="input-filename" class="form-control" />
                            <span class="input-group-btn">
                                <button type="button" id="button-upload" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary"><i class="fa fa-upload"></i> <?php echo $button_upload; ?></button>
                            </span> </div>
                        <?php if ($error_filename) { ?>
                            <div class="text-danger"><?php echo $error_filename; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-mask"><span data-toggle="tooltip" title="<?php echo $help_mask; ?>"><?php echo $entry_mask; ?></span></label>
                    <div class="col-sm-10">
                        <input type="text" name="mask" value="<?php echo $mask; ?>" placeholder="<?php echo $entry_mask; ?>" id="input-mask" class="form-control" />
                        <?php if ($error_mask) { ?>
                            <div class="text-danger"><?php echo $error_mask; ?></div>
                        <?php } ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript"><!--
    docReady(function () {
        $('#button-upload').on('click', function () {
            $('#form-upload').remove();

            $('body').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="file" /></form>');

            $('#form-upload input[name=\'file\']').trigger('click');

            if (typeof timer != 'undefined') {
                clearInterval(timer);
            }

            timer = setInterval(function () {
                if ($('#form-upload input[name=\'file\']').val() != '') {
                    clearInterval(timer);

                    $.ajax({
                        url: 'index.php?p=cms/download/upload&token=<?php echo $token; ?>',
                        type: 'post',
                        dataType: 'json',
                        data: new FormData($('#form-upload')[0]),
                        cache: false,
                        contentType: false,
                        processData: false,
                        beforeSend: function () {
                            $('#button-upload').button('loading');
                        },
                        complete: function () {
                            $('#button-upload').button('reset');
                        },
                        success: function (json) {
                            if (json['error']) {
                                alert(json['error']);
                            }

                            if (json['success']) {
                                alert(json['success']);

                                $('input[name=\'filename\']').attr('value', json['filename']);
                                $('input[name=\'mask\']').attr('value', json['mask']);
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                        }
                    });
                }
            }, 500);
        });
    });
//--></script>
</div>
<?php echo $footer; ?>