<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box box-theme">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-bars"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-success"><i class="fa fa-plus"></i></a>
                <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                        $('#form-download').submit();
                    });"><i class="fa fa-trash-o"></i> </button>  </div>
        </div>
        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-download">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                                <td class="text-left"><?php if ($sort == 'dd.name') { ?>
                                        <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php if ($sort == 'd.date_added') { ?>
                                        <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                                    <?php } ?></td>
                                <td class="text-left">Direct Link</td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($downloads) { ?>
                                <?php foreach ($downloads as $download) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($download['download_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $download['download_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $download['download_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $download['name']; ?></td>
                                        <td class="text-right"><?php echo $download['date_added']; ?></td>
                                        <td class="text-left"><?php echo $download['link']; ?></td>
                                        <td class="text-right">
                                            <a href="<?php echo $download['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="5"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5"><?php echo $pagination; ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>
<?php echo $footer; ?>