<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $insert; ?>" class="btn btn-app">
                <i class="fa fa-plus text-green"></i> <?php echo $button_insert; ?>
            </a>
            <button class="btn btn-app" onclick="$('#form').submit();">
                <i class="fa fa-times text-red"></i> <?php echo $button_delete; ?>
            </button>
        </div>
        <div class="box-body table-responsive">
            <div class="well">
                <div class="row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="input-name"><?php echo $entry_name; ?></label>
                            <input type="text" name="filter_name" value="<?php echo!empty($filters['name']) ? $filters['name'] : ''; ?>" placeholder="<?php echo $entry_name; ?>" id="input-name" class="form-control" />
                        </div>

                    </div>
                    <div class="col-sm-4">

                        <div class="form-group">
                            <label class="control-label" for="input-status"><?php echo $entry_status; ?></label>
                            <select name="filter_status" id="input-status" class="form-control">
                                <option value="*"></option>
                                <?php if (!empty($filters['status']) && $filter['status']) { ?>
                                    <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                <?php } else { ?>
                                    <option value="1"><?php echo $text_enabled; ?></option>
                                <?php } ?>
                                <?php if (!empty($filters['status']) && !$filter['status']) { ?>
                                    <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                <?php } else { ?>
                                    <option value="0"><?php echo $text_disabled; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="input-date-added"><?php echo $column_date_added; ?></label>
                            <div class="input-group date">
                                <input type="text" name="filter_date_added" value="<?php echo (!empty($filters['date_added'])) ? $filters['date_added'] : ''; ?>" placeholder="<?php echo $entry_date_added; ?>" data-format="YYYY-MM-DD" id="input-date-added" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                </span></div>
                        </div>
                        <button type="button" id="button-filter" class="btn btn-primary pull-right"><i class="fa fa-search"></i> Filter</button>
                    </div>
                </div>
            </div>
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form">
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input class="selectall" type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></th>
                            <th class="left">PageID</th>
                            <th class="left"><?php if ($sort == 'name') { ?>
                                    <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                <?php } ?></th>
                            <th class="left">Slug</th>
                            <th class="left"><?php if ($sort == 'status') { ?>
                                    <a href="<?php echo $sort_status; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_status; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_status; ?>"><?php echo $column_status; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'date_added') { ?>
                                    <a href="<?php echo $sort_date_added; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_added; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_date_added; ?>"><?php echo $column_date_added; ?></a>
                                <?php } ?></th>
                            <th class="left"><?php if ($sort == 'date_modified') { ?>
                                    <a href="<?php echo $sort_date_modified; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_date_modified; ?></a>
                                <?php } else { ?>
                                    <a href="<?php echo $sort_date_modified; ?>"><?php echo $column_date_modified; ?></a>
                                <?php } ?></th>
                            <th class="text-right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($pages) { ?>
                            <?php foreach ($pages as $page) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php if ($page['selected']) { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $page['ams_page_id']; ?>" checked="checked" />
                                        <?php } else { ?>
                                            <input type="checkbox" name="selected[]" value="<?php echo $page['ams_page_id']; ?>" />
                                        <?php } ?></td>
                                    <td class="left"><?php echo $page['ams_page_id']; ?></td>
                                    <td class="left"><?php echo $page['name']; ?></td>
                                    <td class="left"><?php echo $page['slug']; ?></td>
                                    <td class="left"><?php echo $page['status']; ?></td>
                                    <td class="left"><?php echo $page['date_created']; ?></td>
                                    <td class="left"><?php echo $page['date_modified']; ?></td>
                                    <td class="text-right">
                                        <?php foreach ($page['action'] as $action) { ?>
                                            <a class="btn btn-xs btn-<?php echo $action['class']; ?>" href="<?php echo $action['href']; ?>"><?php echo $action['text']; ?></a>
                                        <?php } ?>
                                        <?php if ($page['public']): ?>
                                            <a class="btn btn-xs btn-default" target="_blank" href="<?php echo $this->config->get('config_catalog') . $page['slug']; ?>">View Page</a></td>
                                    <?php endif; ?>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="8"><div class="alert alert-info"><?php echo $text_no_results; ?></div></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

            </form>
        </div>
        <div clas="box-footer">
            <div class="pagination-container row">
                <?php echo $pagination; ?>
            </div>
        </div>
    </div>
</section><!-- /.content -->

<script type="text/javascript"><!--
    docReady(function () {
        $('#button-filter').on('click', function () {
            url = url = 'index.php?p=<?php echo $filter; ?>&token=<?php echo $token; ?>';

            var filter_name = $('input[name=\'filter_name\']').val();

            if (filter_name) {
                url += '&filter[name]=' + encodeURIComponent(filter_name);
            }



            var filter_status = $('select[name=\'filter_status\']').val();

            if (filter_status != '*') {
                url += '&filter[status]=' + encodeURIComponent(filter_status);
            }



            var filter_date_added = $('input[name=\'filter_date_added\']').val();

            if (filter_date_added) {
                url += '&filter[date_added]=' + encodeURIComponent(filter_date_added);
            }

            location = url;
        });

        $('.date').datetimepicker({
            pickTime: false
        });
    });
//--></script>

<?php echo $footer; ?>