<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>
<!-- Main content -->
<section class="content">

    <form action="<?php echo $action; ?>" class="form-horizontal form-validate" method="post" enctype="multipart/form-data" id="form">
        <div class="box">
            <div class="box-header text-right">
                <?php if ($autosave_enabled): ?>
                    <div id="autosave" style="float:left;">
                        <a href="#" id="autosave-on" class="fa fa-check-circle-o text-green" title="<?php echo $text_autosaving_on; ?>" /></a>
                        <a href="#" style="display:none;" id="autosave-off" class="fa fa-times-circle-o text-red" title="<?php echo $text_autosaving_off; ?>" /></a>
                        <?php echo $text_last_saved; ?> <span class="autosave-timer">0</span> <?php echo $text_seconds_ago; ?>. <span id="autosave-error"></span>
                    </div>
                <?php else: ?>
                    <div id="autosave" style="float:left;">
                        <a href="#" style="display:none;" id="autosave-on" class="fa fa-check-circle-o text-green" title="<?php echo $text_autosaving_on; ?>" /></a>
                        <a href="#"  id="autosave-off" class="fa fa-times-circle-o text-red" title="<?php echo $text_autosaving_off; ?>" /></a>
                        <?php echo $text_last_saved; ?> <span class="autosave-timer">0</span> <?php echo $text_seconds_ago; ?>. <span id="autosave-error"></span>
                    </div>
                <?php endif; ?>
                <button class="btn btn-app">
                    <i class="fa fa-save text-green"></i> <?php echo $button_save; ?>
                </button>
                <a href="<?php echo $cancel; ?>" class="btn btn-app" onclick="$('#form').submit();">
                    <i class="fa fa-reply"></i> <?php echo $button_cancel; ?>
                </a>
            </div>
            <div class="box-body">

                <ul class="nav nav-tabs" style='margin-bottom:15px;'>

                    <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>
                    <li class=""><a href="#tab-meta" data-toggle="tab"><?php echo $tab_meta; ?></a></li>
                    <?php foreach ($tabs as $tabid => $tab): ?>
                        <?php if ($tabid != 'permission' && $tabid != 'general' && $tabid != 'meta' && $tabid != 'general_details'): ?>
                            <li class=""><a href="#tab-<?php echo slug($tabid); ?>" data-toggle="tab"><?php echo ucfirst($tabid); ?></a></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <li><a href="#tab-permission" data-toggle="tab"><?php echo $tab_permission; ?></a></li>
                    <li><a href="#tab-revisions" data-toggle="tab"><?php echo $tab_revision; ?></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-general">
                        <div class="row">
                            <div class="col-lg-10 col-md-8 col-sm-12">
                                <div class="form-group">
                                    <label for="nameInput" class="col-sm-3 col-md-2 control-label required"><?php echo $entry_name; ?></label>
                                    <div class="col-sm-9 col-md-10">
                                        <input type="text" name="name" value="<?php echo $name; ?>" class="form-control required" id="nameInput" />
                                        <?php if ($error_name) { ?>
                                            <span class="error text-danger"><?php echo $error_name; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="slugInput" class="col-sm-3 col-md-2 control-label required"><?php echo $entry_seo_url; ?></label>
                                    <div class="col-sm-9 col-md-10">
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <?php echo $site_url; ?>
                                            </div>
                                            <input disabled="disabled" type="text" value="<?php echo $slug; ?>" class="form-control required " id="slugInput" />

                                            <input type="hidden" name="slug" value="<?php echo $slug; ?>" id="slugInputValue" />
                                        </div>
                                        <?php if ($error_slug) { ?>
                                            <span class="error text-danger"><?php echo $error_slug; ?></span>
                                        <?php } ?>
                                    </div>
                                </div>
                                <?php foreach ($tabs['general'] as $el => $formfield): ?>
                                    <div class="form-group">
                                        <label for="<?php echo $el; ?>Input" class="col-sm-3 col-md-2 control-label <?php echo $formfield['required'] ? 'required' : ''; ?>"><?php echo $formfield['label']; ?></label>
                                        <div class="col-sm-9 col-md-10">
                                            <?php echo formfield($formfield); ?>
                                            <?php if (!empty($formfield['error'])) { ?>
                                                <span class="error text-danger"><?php echo $formfield['error']; ?></span>
                                            <?php } ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <div class="col-lg-2 col-md-4 col-sm-12">
                                <div class="box box-default box-solid collapsed-box">
                                    <div class="box-header with-border">
                                        <h3 class="box-title"><?php echo $heading_page_details; ?></h3>
                                        <div class="box-tools pull-right">
                                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                    <div class="box-body">

                                        <label for="designInput" class="control-label required text-left"><?php echo $entry_layout; ?></label>
                                        <div class="">
                                            <select name="layout_id" id="designInput" class="form-control">
                                                <?php foreach ($layouts as $layout): ?>
                                                    <?php if ($layout_id == $layout['layout_id']): ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>" selected><?php echo $layout['name']; ?></option>
                                                    <?php else: ?>
                                                        <option value="<?php echo $layout['layout_id']; ?>"><?php echo $layout['name']; ?></option>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                        <div class="">
                                            <label for="parentInput" class="control-label required"><?php echo $entry_parent; ?></label>
                                            <div class="">
                                                <select name="parent_id" id="parentInput" class="form-control">
                                                    <option value="0"><?php echo $text_none; ?></option>
                                                    <?php echo render_select($parents, $parent_id); ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="">
                                            <label for="statusInput" class="control-label required"><?php echo $entry_status; ?></label>
                                            <div class="">
                                                <select name="status" id="statusInput" class="form-control">
                                                    <option value="0"><?php echo $text_disabled; ?></option>
                                                    <option value="1" <?php echo ($status) ? 'selected' : ''; ?>><?php echo $text_enabled; ?></option>

                                                </select>
                                            </div>
                                        </div>
                                        <?php if ($ams_commentable): ?>
                                            <div class="">
                                                <label for="commentsInput" class="control-label required"><?php echo $entry_comments; ?></label>
                                                <div class="">
                                                    <select name="comments" id="commentsInput" class="form-control">
                                                        <option value="0"><?php echo $text_disabled; ?></option>
                                                        <option value="1" <?php echo ($comments) ? 'selected' : ''; ?>><?php echo $text_enabled; ?></option>

                                                    </select>
                                                </div>
                                            </div>
                                       
                                        <?php endif; ?>
                                        <?php foreach ($tabs['general_details'] as $el => $formfield): ?>
                                            <div class="">
                                                <label for="<?php echo $el; ?>Input" class="control-label <?php echo $formfield['required'] ? 'required' : ''; ?>"><?php echo $formfield['label']; ?></label>
                                                <div class="">
                                                    <?php echo formfield($formfield); ?>
                                                    <?php if ($formfield['error']) { ?>
                                                        <span class="error text-danger"><?php echo $formfield['error']; ?></span>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>

                            </div>






                        </div>
                    </div>
                    <div class="tab-pane" id="tab-meta">
                        <div class="form-group">
                            <label for="metaTitleInput" class="col-sm-2 control-label "><?php echo $entry_meta_title; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="meta_title" value="<?php echo $meta_title; ?>" class="form-control" id="metaTitleInput" />

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="metaKeywordInput" class="col-sm-2 control-label "><?php echo $entry_meta_keywords; ?></label>
                            <div class="col-sm-9">
                                <textarea rows="3" name="meta_keywords"  class="form-control" id="metaKeywordInput" ><?php echo $meta_keywords; ?></textarea>

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="metaDescInput" class="col-sm-2 control-label "><?php echo $entry_meta_description; ?></label>
                            <div class="col-sm-9">
                                <textarea rows="3" name="meta_description"  class="form-control" id="metaDescInput" ><?php echo $meta_description; ?></textarea>
                            </div>
                        </div>
                        <fieldset>
                            <legend><?php echo $legend_facebook; ?></legend>
                            <div class="form-group">
                                <label for="metaogTitleInput" class="col-sm-2 control-label "><?php echo $entry_meta_ogtitle; ?></label>
                                <div class="col-sm-9">
                                    <input type="text" name="meta_og_title" value="<?php echo $meta_og_title; ?>" class="form-control" id="metaogTitleInput" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="metaogDescInput" class="col-sm-2 control-label "><?php echo $entry_meta_ogdescription; ?></label>
                                <div class="col-sm-9">
                                    <textarea rows="3" name="meta_og_description"  class="form-control" id="metaogDescInput" ><?php echo $meta_og_description; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="metaogImgInput" class="col-sm-2 control-label "><?php echo $entry_meta_ogimage; ?></label>
                                <div class="col-sm-9">
                                    <a href="#" id="thumb-fbimage" data-toggle="image" class="img-thumbnail"><img src="<?php echo $src_og_image; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a>
                                    <input type="hidden" name="meta_og_image" value="<?php echo $entry_meta_ogimage; ?>" id="input-facebook_ogimag" />
                                    <span><?php echo $entry_meta_ogimage_help;?></span>

                                </div>
                            </div>
                        </fieldset>

                        <?php foreach ($tabs['meta'] as $el => $formfield): ?>
                            <div class="form-group">
                                <label for="<?php echo $el; ?>Input" class="col-sm-2 control-label <?php echo $formfield['required'] ? 'required' : ''; ?>"><?php echo $formfield['label']; ?></label>
                                <div class="col-sm-9">
                                    <?php echo formfield($formfield); ?>
                                    <?php if ($formfield['error']) { ?>
                                        <span class="error text-danger"><?php echo $formfield['error']; ?></span>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <?php foreach ($tabs as $tabid => $tab): ?>
                        <?php if ($tab != 'permission' && $tabid != 'general' && $tabid != 'meta' && $tabid != 'general_details'): ?>
                            <div class="tab-pane" id="tab-<?php echo slug($tabid); ?>">
                                <?php foreach ($tab as $el => $formfield): ?>
                                    <div class="form-group">
                                        <label for="<?php echo $el; ?>Input" class="col-sm-2 control-label <?php echo $formfield['required'] ? 'required' : ''; ?>"><?php echo $formfield['label']; ?></label>
                                        <div class="col-sm-9">
                                            <?php echo formfield($formfield); ?>
                                            <?php if ($formfield['error']) { ?>
                                                <span class="error text-danger"><?php echo $formfield['error']; ?></span>
                                            <?php } ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>

                    <div class="tab-pane" id="tab-permission">

                        <div class="row">
                            <div class="col-sm-6">
                                <label for="accessInput" class="col-sm-12"><?php echo $entry_allowed_groups; ?></label>
                                <div class="col-sm-12">

                                    <div class="scrollbox">
                                        <ul class="list-group">
                                            <?php $class = 'odd'; ?>
                                            <?php foreach ($customer_groups as $customer_group) : ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <?php if (in_array($customer_group['customer_group_id'], $allowed_groups)) { ?>
                                                        <input type="checkbox" name="allowed_groups[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />

                                                    <?php } else { ?>
                                                        <input type="checkbox" name="allowed_groups[]" value="<?php echo $customer_group['customer_group_id']; ?>" />

                                                    <?php } ?>
                                                    <?php echo $customer_group['name']; ?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <label for="accessInput" class="col-sm-12"><?php echo $entry_denied_groups; ?></label>
                                <div class="col-sm-12">

                                    <div class="scrollbox">
                                        <ul class="list-group">
                                            <?php $class = 'odd'; ?>
                                            <?php foreach ($customer_groups as $customer_group) : ?>
                                                <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                <li class="list-group-item <?php echo $class; ?>">
                                                    <?php if (in_array($customer_group['customer_group_id'], $denied_groups)) { ?>
                                                        <input type="checkbox" name="denied_groups[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />

                                                    <?php } else { ?>
                                                        <input type="checkbox" name="denied_groups[]" value="<?php echo $customer_group['customer_group_id']; ?>" />

                                                    <?php } ?>
                                                    <?php echo $customer_group['name']; ?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <?php foreach ($tabs['permission'] as $el => $formfield): ?>
                            <div class="form-group">
                                <label for="<?php echo $el; ?>Input" class="col-sm-2 control-label <?php echo $formfield['required'] ? 'required' : ''; ?>"><?php echo $formfield['label']; ?></label>
                                <div class="col-sm-9">
                                    <?php echo formfield($formfield); ?>
                                    <?php if ($formfield['error']) { ?>
                                        <span class="error text-danger"><?php echo $formfield['error']; ?></span>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <div class="tab-pane" id="tab-revisions">

                    </div>
                </div>
            </div>
            <div class="box-footer">

            </div>
        </div>
    </form>

</section><!-- /.content -->

<script>
    var slugXHR = null;


    var autosaving_interval;
    var autosaving_timer;
    var timing_interval = <?php echo $autosave_time; ?>; //How many seconds between saves..... defaulting to 2 minutes!!!!
    var timing_start_seconds = 0;
    var timing_current_seconds = 0;


    function start_timing() {
        autosaving_interval = setInterval('autosave_page()', timing_interval * 1000); //*1000 for microsecons which js uses
        autosaving_timer = setInterval('autosave_timing()', 1000);
    }

    function autosave_timing() {
        timing_current_seconds++;
        $('.autosave-timer').html(timing_start_seconds + timing_current_seconds);
    }


    function autosave_page() {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }

        $.ajax({
            type: 'POST',
            url: '<?php echo $autosave; ?>',
            data: $('#form').first().serialize(),
            dataType: 'json',
            beforeSend: function () {
                $('#autosave').prepend('<span  class="wait">&nbsp;<?php echo $text_autosave_in_progress; ?> <img src="view/img/loading.gif" alt="" />&nbsp;&nbsp;</span>');
            },
            complete: function () {
                $('.wait').remove();

            },
            success: function (html) {
                console.log(html);
                if (html.saved >= 1) {
                    timing_current_seconds = 0;
                    $('.autosave-timer').text('0');
                    $('.ajax-error').remove();
                    $('#tab-revisions').load('<?php echo $history; ?>');

                } else {
                    $('#autosave-error').html('<span  class="ajax-error text-red">&nbsp;<?php echo $text_autosave_warning; ?>&nbsp;&nbsp;</span>');

                }

            },
            error: function (xhr, ajaxOptions, thrownError) {
                $('#autosave-error').html('<span  class="ajax-error text-red">&nbsp;<?php echo $text_autosave_warning; ?>&nbsp;&nbsp;</span>');
                alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
            }
        });
    }

    docReady(function () {

        $('#autosave-on').click(function (e) {
            e.preventDefault();
            clearInterval(autosaving_interval);
            clearInterval(autosaving_timer);
            timing_current_seconds = 0;
            $('.autosave-timer').text('0');
            $('#autosave-on').hide();
            $('#autosave-off').show();
        });
        $('#autosave-off').click(function (e) {
            e.preventDefault();
            autosaving_interval = setInterval('autosave_page()', timing_interval * 1000);
            autosaving_timer = setInterval('autosave_timing()', 1000);
            $('#autosave-on').show();
            $('#autosave-off').hide();
        });

<?php if ($autosave_enabled): ?>
            start_timing();
<?php endif; ?>

        $('#tab-revisions').load('<?php echo $history; ?>');
        $(document).on("click", '#tab-revisions .pagination a', function (e) {
            e.preventDefault();
            $('#tab-revisions').load($(this).attr('href'));
        });

<?php if (isset($doslug) && $doslug): ?>





            $('#nameInput').on("keyup", function () {
                var pdata = {name: $(this).val()};
                if (slugXHR != null) {
                    slugXHR.abort();
                    slugXHR = null;
                }
                slugXHR = $.ajax({
                    type: "POST",
                    url: 'index.php?p=<?php echo $namespace; ?>/getSlug&token=<?php echo $this->session->data['token']; ?>',
                    data: pdata,
                    dataType: 'json',
                    success: function (msg) {
                        /* handle the ajax response */
                        $('#slugInput').val(msg.slug);
                        $('#slugInputValue').val(msg.slug);

                    }
                });
            });

<?php endif; ?>
    });
</script>

<?php echo $footer; ?>

