<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-envelope-o"></i> <?php echo $heading_title_contact_details; ?></h3>
            <div class="box-tools pull-right">
                <button type="submit" form="form-reply"  class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_reply; ?>"><i class="fa fa-send-o"></i></button>
                <a onclick="$('#execute').val('delete');
                        $('#form').submit();" class="btn btn-danger" data-toggle="tooltip" title="<?php echo $button_delete; ?>"><i class="fa fa-trash"></i> </a>
                <a href="<?php echo $cancel; ?>" class="btn btn-default" data-toggle="tooltip" title="<?php echo $button_cancel; ?>"><i class="fa fa-reply"></i> </a>
            </div>
        </div>
        <div class="box-body">
            <form action="<?php echo $execute; ?>" method="post" enctype="multipart/form-data" id="form">
                <input type="hidden" name="execute" id="execute" />
            </form>
            <?php if ($single_data) { ?>
                <?php foreach ($single_data as $contact) { ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $contact['firstname']; ?> &lt;<?php echo $contact['email'] ?>&gt;<span class="mailbox-read-time pull-right"><?php echo $contact['date_added'] ?> | <a target="_blank" href="http://whatismyipaddress.com/ip/<?php echo $contact['ipaddress'] ?>"><?php echo $contact['ipaddress'] ?></a></span></h3>

                        </div>
                        <div class="panel-body">

                            <div class="mailbox-read-message">
                                <?php echo nl2br($contact['enquiry']); ?>
                            </div>
                            <?php if ($contact['custom_field']): ?>
                                <div class="well well-sm">
                                    <h4><?php echo $heading_additional_fields; ?></h4>
                                    <?php foreach (unserialize($contact['custom_field']) as $fld => $val): ?>
                                        <p><strong><?php echo $fld; ?> : </strong><?php echo nl2br($val); ?></p>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>

                        </div>
                        <div class="panel-footer">
                            <?php if ($responses): ?>
                                <h4><?php echo $heading_title_replies; ?></h4>
                                <?php foreach ($responses as $response): ?>
                                    <div class="bg-info disabled">
                                        <div class="mailbox-read-info clearfix">
                                            <h5 class="pull-left"><?php echo $response['subject']; ?></h5> <span class="mailbox-read-time pull-right"><?php echo $response['date_created'] ?></span></h5>
                                        </div>
                                        <div class="mailbox-read-message">
                                            <?php echo nl2br($contact['enquiry']); ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>

                            <?php endif; ?>

                        </div>
                    </div>
                </div>
            </div>

            <div class="box box-theme">
                <form action="<?php echo $send; ?>" method="post" class="form-horizontal" enctype="multipart/form-data" id="form-reply">

                    <div class="box-header">
                        <h4 class="box-title"><i class="fa fa-send"></i> <?php echo $heading_title_reply; ?></h4>
                        <div class="box-tools pull-right">
                            <button type="submit" form="form-reply"  class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_reply; ?>"><i class="fa fa-send-o"></i></button>
                            <a href="<?php echo $cancel; ?>" class="btn btn-default" data-toggle="tooltip" title="<?php echo $button_cancel; ?>"><i class="fa fa-reply"></i> </a>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <label class="control-label col-sm-3"><?php echo $label_subject; ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="subject" value="<?php echo $subject; ?>" class="form-control required" placeholder="<?php echo $label_subject; ?>"/>
                                <?php if ($error_subject): ?><span class="text-danger"><?php echo $error_subject; ?></span><?php endif; ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3"><?php echo $label_message; ?></label>
                            <div class="col-sm-9">
                                <textarea class="form-control" name="message_body" rows="15"><?php echo $message_body; ?></textarea>
                                <?php if ($error_message_body): ?><span class="text-danger"><?php echo $error_message_body; ?></span><?php endif; ?>
                            </div>
                        </div>
                    </div>

                </form>
            </div>

        <?php } ?>
    <?php } else { ?>
        <?php echo $text_no_results; ?>
    <?php } ?>


</section>
<?php echo $footer; ?>