<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $heading_title_contact_list; ?></h3>
            <div class="box-tools pull-right">
            <a href="<?php echo $csvfile; ?>" class="btn btn-info" data-toggle="tooltip" title="<?php echo $button_csv; ?>"><i class="fa fa-download"></i> </a>
            <a onclick="$('#execute').val('markasread');
                    $('#form').submit();" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_read; ?>"><i class="fa fa-check"></i> </a>
            <a onclick="confirmDelete('Are you Sure?', '', function () {$('#execute').val('delete');
                $('#form').submit();});" class="btn btn-danger" data-toggle="tooltip" title="<?php echo $button_delete; ?>"><i class="fa fa-trash"></i> </a>

        </div>
        </div>
        <div class="box-body">

            <form action="<?php echo $execute; ?>" method="post" enctype="multipart/form-data" id="form">
                <input type="hidden" name="execute" id="execute" />

                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th width="1" style="text-align: center;"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                            <th class="left"><?php echo $column_name; ?></th>
                            <th class="left"><?php echo $column_email; ?></th>
                            <th class="left"><?php echo $column_ip; ?></th>
                            <th class="text-left"><?php echo $column_description; ?></th>
                            <th class="text-right"><?php echo $column_date_added; ?></th>
                            <th class="text-right"><?php echo $column_action; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($contact_info) { ?>
                            <?php foreach ($contact_info as $contact) { ?>
                                <tr class="<?php echo $contact['is_read'] ? '' : 'active'; ?>">
                                    <td class="left"> <input type="checkbox" name="selected[]" value="<?php echo $contact['contact_id']; ?>" /></td>
                                    <td class="left"> <?php echo $contact['firstname']; ?></td>
                                    <td class="left"> <?php echo $contact['email'] ?></td>
                                    <td class="left"> <?php echo $contact['ipaddress'] ?></td>

                                    <td class="right"><?php echo substr($contact['enquiry'], 0, '80'); ?>...</td>
                                    <td class="text-right"> <?php echo $contact['date_added'] ?></td>
                                    <td class="text-right">  
                                       <a href="<?php echo $contact['view']; ?>" data-toggle="tooltip" title="<?php echo $button_reply; ?>" class="btn btn-primary"><i class="fa fa-reply"></i></a>

                                    </td> 
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="center" colspan="8"><?php echo $text_no_results; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?>