<?php echo $header; ?>

<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <button type="submit" form="form-customer-ban-ip" data-toggle="tooltip" title="<?php echo $button_save; ?>" class="btn btn-app"><i class="fa fa-save text-primary"></i> <?php echo $button_save; ?></button>
            <a href="<?php echo $cancel; ?>" data-toggle="tooltip" title="<?php echo $button_cancel; ?>" class="btn btn-app"><i class="fa fa-reply"></i> <?php echo $button_cancel; ?></a>


        </div>

        <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-customer-ban-ip" class="form-horizontal">
                <div class="form-group required">
                    <label class="col-sm-2 control-label" for="input-ip"><?php echo $entry_ip; ?></label>
                    <div class="col-sm-10">
                        <input type="text" name="ip" value="<?php echo $ip; ?>" id="input-ip" class="form-control" />
                        <?php if ($error_ip) { ?>
                            <div class="text-danger"><?php echo $error_ip; ?></div>
                        <?php } ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<?php echo $footer; ?>