<?php echo $header; ?>
<?php $subheading = $text_form; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $insert; ?>" data-toggle="tooltip" title="<?php echo $button_insert; ?>" class="btn btn-app"><i class="fa fa-plus text-primary"></i> <?php echo $button_insert; ?></a>
            <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-app" onclick="confirm('<?php echo $text_confirm; ?>') ? $('#form-customer-ban-ip').submit() : false;"><i class="fa fa-trash-o text-danger"></i> <?php echo $button_delete; ?></button>

        </div>

        <div class="box-body">

            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-customer-ban-ip">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                                <td class="text-left"><?php if ($sort == 'ip') { ?>
                                        <a href="<?php echo $sort_ip; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_ip; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_ip; ?>"><?php echo $column_ip; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php echo $column_customer; ?></td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($customer_ban_ips) { ?>
                                <?php foreach ($customer_ban_ips as $customer_ban_ip) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($customer_ban_ip['customer_ban_ip_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $customer_ban_ip['customer_ban_ip_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $customer_ban_ip['customer_ban_ip_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $customer_ban_ip['ip']; ?></td>
                                        <td class="text-right"><?php if ($customer_ban_ip['total']) { ?>
                                                <a href="<?php echo $customer_ban_ip['customer']; ?>"><?php echo $customer_ban_ip['total']; ?></a>
                                            <?php } else { ?>
                                                <?php echo $customer_ban_ip['total']; ?>
                                            <?php } ?></td>
                                        <td class="text-right"><a href="<?php echo $customer_ban_ip['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="4"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="4"><?php echo $pagination; ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>
</section>
<?php echo $footer; ?> 