<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">
    <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> <?php echo $text_form; ?></h3>

            <div class="box-tools pull-right">
                <button  type="submit" form="form-customer" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_save; ?>">
                    <i class="fa fa-save"></i>
                </button>

                <a href="<?php echo $cancel; ?>" class="btn btn-default" title="<?php echo $button_cancel; ?>"  data-toggle="tooltip">
                    <i class="fa fa-reply"></i> 
                </a>
            </div>
        </div>


        <div class="box-body">

            <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data" id="form-customer" class="form-horizontal">
                <?php if ($customer_id) { ?>
                    <ul class="nav nav-tabs margin-bottom-15">
                        <li class="active"><a href="#tab-general" data-toggle="tab"><?php echo $tab_general; ?></a></li>

                        <li><a href="#tab-history" data-toggle="tab"><?php echo $tab_history; ?></a></li>
                        <li><a href="#tab-ip" data-toggle="tab"><?php echo $tab_ip; ?></a></li>

                    </ul>
                <?php } ?>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-general">
                        <div class="row">
                            <div class="col-sm-10">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab-customer">

                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label" for="input-firstname"><?php echo $entry_firstname; ?></label>
                                            <div class="col-sm-10">
                                                <input type="text" name="firstname" value="<?php echo $firstname; ?>" placeholder="<?php echo $entry_firstname; ?>" id="input-firstname" class="form-control" />
                                                <?php if ($error_firstname) { ?>
                                                    <div class="text-danger"><?php echo $error_firstname; ?></div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label" for="input-lastname"><?php echo $entry_lastname; ?></label>
                                            <div class="col-sm-10">
                                                <input type="text" name="lastname" value="<?php echo $lastname; ?>" placeholder="<?php echo $entry_lastname; ?>" id="input-lastname" class="form-control" />
                                                <?php if ($error_lastname) { ?>
                                                    <div class="text-danger"><?php echo $error_lastname; ?></div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label" for="input-email"><?php echo $entry_email; ?></label>
                                            <div class="col-sm-10">
                                                <input type="text" name="email" value="<?php echo $email; ?>" placeholder="<?php echo $entry_email; ?>" id="input-email" class="form-control" />
                                                <?php if ($error_email) { ?>
                                                    <div class="text-danger"><?php echo $error_email; ?></div>
                                                <?php } ?>
                                            </div>
                                        </div>


                                        <?php foreach ($custom_fields as $custom_field) { ?>
                                            <?php if ($custom_field['location'] == 'account') { ?>
                                                <?php if ($custom_field['type'] == 'select') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <select name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control">
                                                                <option value=""><?php echo $text_select; ?></option>
                                                                <?php foreach ($custom_field['custom_field_value'] as $custom_field_value) { ?>
                                                                    <?php if (isset($account_custom_field[$custom_field['custom_field_id']]) && $custom_field_value['custom_field_value_id'] == $account_custom_field[$custom_field['custom_field_id']]) { ?>
                                                                        <option value="<?php echo $custom_field_value['custom_field_value_id']; ?>" selected="selected"><?php echo $custom_field_value['name']; ?></option>
                                                                    <?php } else { ?>
                                                                        <option value="<?php echo $custom_field_value['custom_field_value_id']; ?>"><?php echo $custom_field_value['name']; ?></option>
                                                                    <?php } ?>
                                                                <?php } ?>
                                                            </select>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'radio') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <div>
                                                                <?php foreach ($custom_field['custom_field_value'] as $custom_field_value) { ?>
                                                                    <div class="radio">
                                                                        <?php if (isset($account_custom_field[$custom_field['custom_field_id']]) && $custom_field_value['custom_field_value_id'] == $account_custom_field[$custom_field['custom_field_id']]) { ?>
                                                                            <label>
                                                                                <input type="radio" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" checked="checked" />
                                                                                <?php echo $custom_field_value['name']; ?></label>
                                                                        <?php } else { ?>
                                                                            <label>
                                                                                <input type="radio" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" />
                                                                                <?php echo $custom_field_value['name']; ?></label>
                                                                        <?php } ?>
                                                                    </div>
                                                                <?php } ?>
                                                            </div>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'checkbox') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <div>
                                                                <?php foreach ($custom_field['custom_field_value'] as $custom_field_value) { ?>
                                                                    <div class="checkbox">
                                                                        <?php if (isset($account_custom_field[$custom_field['custom_field_id']]) && in_array($custom_field_value['custom_field_value_id'], $account_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                            <label>
                                                                                <input type="checkbox" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>][]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" checked="checked" />
                                                                                <?php echo $custom_field_value['name']; ?></label>
                                                                        <?php } else { ?>
                                                                            <label>
                                                                                <input type="checkbox" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>][]" value="<?php echo $custom_field_value['custom_field_value_id']; ?>" />
                                                                                <?php echo $custom_field_value['name']; ?></label>
                                                                        <?php } ?>
                                                                    </div>
                                                                <?php } ?>
                                                            </div>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'text') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($account_custom_field[$custom_field['custom_field_id']]) ? $account_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'textarea') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <textarea name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" rows="5" placeholder="<?php echo $custom_field['name']; ?>" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control"><?php echo (isset($account_custom_field[$custom_field['custom_field_id']]) ? $account_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?></textarea>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'file') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <button type="button" id="button-custom-field<?php echo $custom_field['custom_field_id']; ?>" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-default btn-upload"><i class="fa fa-upload"></i> <?php echo $button_upload; ?></button>
                                                            <input type="hidden" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($account_custom_field[$custom_field['custom_field_id']]) ? $account_custom_field[$custom_field['custom_field_id']] : ''); ?>" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" />
                                                            <?php if (isset($account_custom_field[$custom_field['custom_field_id']])) : ?>
                                                                <a href="index.php?code=<?php echo $account_custom_field[$custom_field['custom_field_id']]; ?>&p=tool/upload/download&token=<?php echo $token; ?>" class="btn btn-primary"><i class="fa fa-download"></i> <?php echo $button_download; ?></a>
                                                            <?php endif; ?>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'date') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <div class="input-group date">
                                                                <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($account_custom_field[$custom_field['custom_field_id']]) ? $account_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="YYYY-MM-DD" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                                                </span></div>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'time') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <div class="input-group time">
                                                                <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($account_custom_field[$custom_field['custom_field_id']]) ? $account_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="HH:mm" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                                                </span></div>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($custom_field['type'] == 'datetime') { ?>
                                                    <div class="form-group custom-field custom-field<?php echo $custom_field['custom_field_id']; ?>" data-sort="<?php echo $custom_field['sort_order']; ?>">
                                                        <label class="col-sm-2 control-label" for="input-custom-field<?php echo $custom_field['custom_field_id']; ?>"><?php echo $custom_field['name']; ?></label>
                                                        <div class="col-sm-10">
                                                            <div class="input-group datetime">
                                                                <input type="text" name="custom_field[<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo (isset($account_custom_field[$custom_field['custom_field_id']]) ? $account_custom_field[$custom_field['custom_field_id']] : $custom_field['value']); ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="YYYY-MM-DD HH:mm" id="input-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                                                                </span></div>
                                                            <?php if (isset($error_custom_field[$custom_field['custom_field_id']])) { ?>
                                                                <div class="text-danger"><?php echo $error_custom_field[$custom_field['custom_field_id']]; ?></div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            <?php } ?>
                                        <?php } ?>

                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label" for="input-password"><?php echo $entry_password; ?></label>
                                            <div class="col-sm-10">
                                                <input type="password" name="password" value="<?php echo $password; ?>" placeholder="<?php echo $entry_password; ?>" id="input-password" class="form-control" autocomplete="off" />
                                                <?php if ($error_password) { ?>
                                                    <div class="text-danger"><?php echo $error_password; ?></div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label" for="input-confirm"><?php echo $entry_confirm; ?></label>
                                            <div class="col-sm-10">
                                                <input type="password" name="confirm" value="<?php echo $confirm; ?>" placeholder="<?php echo $entry_confirm; ?>" autocomplete="off" id="input-confirm" class="form-control" />
                                                <?php if ($error_confirm) { ?>
                                                    <div class="text-danger"><?php echo $error_confirm; ?></div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="input-customer-group"><?php echo $entry_customer_group; ?></label>
                                            <div class="col-sm-10">
                                                <div class="scrollbox">
                                                    <ul class="list-group">
                                                        <?php $class = 'odd'; ?>
                                                        <?php foreach ($customer_groups as $customer_group) : ?>
                                                            <?php $class = ($class == 'even' ? 'odd' : 'even'); ?>
                                                            <li class="list-group-item <?php echo $class; ?>">
                                                                <?php if (in_array($customer_group['customer_group_id'], $customer_group_id)) { ?>
                                                                    <input type="checkbox" name="customer_group_id[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />

                                                                <?php } else { ?>
                                                                    <input type="checkbox" name="customer_group_id[]" value="<?php echo $customer_group['customer_group_id']; ?>" />

                                                                <?php } ?>
                                                                <?php echo $customer_group['name']; ?>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="input-newsletter"><?php echo $entry_newsletter; ?></label>
                                            <div class="col-sm-10">
                                                <select name="newsletter" id="input-newsletter" class="form-control">
                                                    <?php if ($newsletter) { ?>
                                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                                        <option value="0"><?php echo $text_disabled; ?></option>
                                                    <?php } else { ?>
                                                        <option value="1"><?php echo $text_enabled; ?></option>
                                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="input-country"><?php echo $entry_country; ?></label>
                                            <div class="col-sm-10">
                                                <select name="country_id" id="input-country" class="form-control">
                                                    <option value=""><?php echo $text_select; ?></option>
                                                    <?php foreach ($countries as $country) { ?>
                                                        <?php if ($country['country_id'] == $country_id) { ?>
                                                            <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
                                                        <?php } else { ?>
                                                            <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </select>
                                                <?php if (isset($error_country)) { ?>
                                                    <div class="text-danger"><?php echo $error_country; ?></div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="input-status"><?php echo $entry_status; ?></label>
                                            <div class="col-sm-10">
                                                <select name="status" id="input-status" class="form-control">
                                                    <?php if ($status) { ?>
                                                        <option value="1" selected="selected"><?php echo $text_enabled; ?></option>
                                                        <option value="0"><?php echo $text_disabled; ?></option>
                                                    <?php } else { ?>
                                                        <option value="1"><?php echo $text_enabled; ?></option>
                                                        <option value="0" selected="selected"><?php echo $text_disabled; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="input-approved"><?php echo $entry_approved; ?></label>
                                            <div class="col-sm-10">
                                                <select name="approved" id="input-approved" class="form-control">
                                                    <?php if ($approved) { ?>
                                                        <option value="1" selected="selected"><?php echo $text_yes; ?></option>
                                                        <option value="0"><?php echo $text_no; ?></option>
                                                    <?php } else { ?>
                                                        <option value="1"><?php echo $text_yes; ?></option>
                                                        <option value="0" selected="selected"><?php echo $text_no; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php if ($customer_id) { ?>
                        <div class="tab-pane" id="tab-history">
                            <div id="history"></div>
                            <br />
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="input-comment"><?php echo $entry_comment; ?></label>
                                <div class="col-sm-10">
                                    <textarea name="comment" rows="8" placeholder="<?php echo $entry_comment; ?>" id="input-comment" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="text-right">
                                <button id="button-history" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary"><i class="fa fa-plus-circle"></i> <?php echo $button_history_add; ?></button>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="tab-pane" id="tab-ip">
                        <div id="ip"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script type="text/javascript"><!--
    docReady(function () {



        $('select[name=\'customer_group_id\']').on('change', function () {
            $.ajax({
                url: 'index.php?p=sale/customer/customfield&token=<?php echo $token; ?>&customer_group_id=' + this.value,
                dataType: 'json',
                success: function (json) {
                    $('.custom-field').hide();
                    $('.custom-field').removeClass('required');

                    for (i = 0; i < json.length; i++) {
                        custom_field = json[i];

                        $('.custom-field' + custom_field['custom_field_id']).show();

                        if (custom_field['required']) {
                            $('.custom-field' + custom_field['custom_field_id']).addClass('required');
                        }
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });

        $('select[name=\'customer_group_id\']').trigger('change');

        $('#history').delegate('.pagination a', 'click', function (e) {
            e.preventDefault();

            $('#history').load(this.href);
        });

        $('#history').load('index.php?p=sale/customer/history&token=<?php echo $token; ?>&customer_id=<?php echo $customer_id; ?>');

        $('#button-history').on('click', function (e) {
            e.preventDefault();

            $.ajax({
                url: 'index.php?p=sale/customer/history&token=<?php echo $token; ?>&customer_id=<?php echo $customer_id; ?>',
                type: 'post',
                dataType: 'html',
                data: 'comment=' + encodeURIComponent($('#tab-history textarea[name=\'comment\']').val()),
                beforeSend: function () {
                    $('#button-history').button('loading');
                },
                complete: function () {
                    $('#button-history').button('reset');
                },
                success: function (html) {
                    $('.alert').remove();

                    $('#history').html(html);

                    $('#tab-history textarea[name=\'comment\']').val('');
                }
            });
        });


        $('#ip').delegate('.pagination a', 'click', function (e) {
            e.preventDefault();

            $('#ip').load(this.href);
        });

        $('#ip').load('index.php?p=sale/customer/ip&token=<?php echo $token; ?>&customer_id=<?php echo $customer_id; ?>');

        $('body').delegate('.button-ban-add', 'click', function () {
            var element = this;

            $.ajax({
                url: 'index.php?p=sale/customer/addbanip&token=<?php echo $token; ?>',
                type: 'post',
                dataType: 'json',
                data: 'ip=' + encodeURIComponent(this.value),
                beforeSend: function () {
                    $(element).button('loading');
                },
                complete: function () {
                    $(element).button('reset');
                },
                success: function (json) {
                    $('.alert').remove();

                    if (json['error']) {
                        $('#content > .container-fluid').prepend('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error'] + '</div>');

                        $('.alert').fadeIn('slow');
                    }

                    if (json['success']) {
                        $('#content > .container-fluid').prepend('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + '</div>');

                        $(element).replaceWith('<button type="button" value="' + element.value + '" class="btn btn-danger btn-xs button-ban-remove"><i class="fa fa-minus-circle"></i> <?php echo $text_remove_ban_ip; ?></button>');
                    }
                }
            });
        });

        $('body').delegate('.button-ban-remove', 'click', function () {
            var element = this;

            $.ajax({
                url: 'index.php?p=sale/customer/removebanip&token=<?php echo $token; ?>',
                type: 'post',
                dataType: 'json',
                data: 'ip=' + encodeURIComponent(this.value),
                beforeSend: function () {
                    $(element).button('loading');
                },
                complete: function () {
                    $(element).button('reset');
                },
                success: function (json) {
                    $('.alert').remove();

                    if (json['error']) {
                        $('#content > .container-fluid').prepend('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error'] + '</div>');
                    }

                    if (json['success']) {
                        $('#content > .container-fluid').prepend('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + '</div>');

                        $(element).replaceWith('<button type="button" value="' + element.value + '" class="btn btn-success btn-xs button-ban-add"><i class="fa fa-plus-circle"></i> <?php echo $text_add_ban_ip; ?></button>');
                    }
                }
            });
        });


        $(document).delegate('button[id^=\'button-custom-field\'], button[id^=\'button-address\']', 'click', function () {
            var node = this;

            $('#form-upload').remove();

            $('body').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="file" /></form>');

            $('input[name=\'file\']').trigger('click');

            if (typeof timer != 'undefined') {
                clearInterval(timer);
            }

            timer = setInterval(function () {
                if ($('#form-upload input[name=\'file\']').val() != '') {
                    clearInterval(timer);

                    $.ajax({
                        url: 'index.php?p=tool/upload/upload&token=<?php echo $token; ?>',
                        type: 'post',
                        dataType: 'json',
                        data: new FormData($('#form-upload')[0]),
                        cache: false,
                        contentType: false,
                        processData: false,
                        beforeSend: function () {
                            $(node).button('loading');
                        },
                        complete: function () {
                            $(node).button('reset');
                        },
                        success: function (json) {
                            $(node).parent().find('.text-danger').remove();

                            if (json['error']) {
                                $(node).parent().find('input[type=\'hidden\']').after('<div class="text-danger">' + json['error'] + '</div>');
                            }

                            if (json['success']) {
                                alert(json['success']);
                            }

                            if (json['code']) {
                                $(node).parent().find('input[type=\'hidden\']').attr('value', json['code']);
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                        }
                    });
                }
            }, 500);
        });

        $('.date').datetimepicker({
            pickTime: false
        });

        $('.datetime').datetimepicker({
            pickDate: true,
            pickTime: true
        });

        $('.time').datetimepicker({
            pickDate: false
        });

    });
//--></script>
<?php echo $footer; ?>