<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">
    
        <div class="box box-theme">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list"></i> <?php echo $text_list; ?></h3>
            <div class="box-tools pull-right">
                <a href="<?php echo $insert; ?>" class="btn btn-success" data-toggle="tooltip" title="<?php echo $button_insert; ?>">
                    <i class="fa fa-plus"></i>
                </a>
                <button class="btn btn-danger" onclick="confirmDelete('Are you Sure?', '', function () {
                            $('#form-customer-group').submit();
                        });" data-toggle="tooltip" title="<?php echo $button_delete; ?>">
                    <i class="fa fa-trash"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-customer-group">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                                <td class="text-left"><?php if ($sort == 'cgd.name') { ?>
                                        <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php if ($sort == 'cg.sort_order') { ?>
                                        <a href="<?php echo $sort_sort_order; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_sort_order; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_sort_order; ?>"><?php echo $column_sort_order; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($customer_groups) { ?>
                                <?php foreach ($customer_groups as $customer_group) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($customer_group['customer_group_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $customer_group['customer_group_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $customer_group['name']; ?></td>
                                        <td class="text-right"><?php echo $customer_group['sort_order']; ?></td>
                                        <td class="text-right"><a href="<?php echo $customer_group['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-edit"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="4"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="4"><?php echo $pagination; ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>

</section>
<?php echo $footer; ?> 