<?php echo $header; ?>
<?php include(__DIR__ . '/../common/page-header.phtml'); ?>

<section class="content">

    <div class="box">
        <div class="box-header text-right">
            <a href="<?php echo $insert; ?>" data-toggle="tooltip" title="<?php echo $button_insert; ?>" class="btn btn-app"><i class="fa fa-plus text-primary"></i> <?php echo $button_insert; ?></a>
            <button type="button" data-toggle="tooltip" title="<?php echo $button_delete; ?>" class="btn btn-app" onclick="confirm('<?php echo $text_confirm; ?>') ? $('#form-customer-group').submit() : false;"><i class="fa fa-trash-o text-danger"></i> <?php echo $button_delete; ?></button>

        </div>
        <div class="box-body">
            <form action="<?php echo $delete; ?>" method="post" enctype="multipart/form-data" id="form-customer-group">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" /></td>
                                <td class="text-left"><?php if ($sort == 'cgd.name') { ?>
                                        <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php if ($sort == 'cg.sort_order') { ?>
                                        <a href="<?php echo $sort_sort_order; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_sort_order; ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $sort_sort_order; ?>"><?php echo $column_sort_order; ?></a>
                                    <?php } ?></td>
                                <td class="text-right"><?php echo $column_action; ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($customer_groups) { ?>
                                <?php foreach ($customer_groups as $customer_group) { ?>
                                    <tr>
                                        <td class="text-center"><?php if (in_array($customer_group['customer_group_id'], $selected)) { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $customer_group['customer_group_id']; ?>" checked="checked" />
                                            <?php } else { ?>
                                                <input type="checkbox" name="selected[]" value="<?php echo $customer_group['customer_group_id']; ?>" />
                                            <?php } ?></td>
                                        <td class="text-left"><?php echo $customer_group['name']; ?></td>
                                        <td class="text-right"><?php echo $customer_group['sort_order']; ?></td>
                                        <td class="text-right"><a href="<?php echo $customer_group['edit']; ?>" data-toggle="tooltip" title="<?php echo $button_edit; ?>" class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td class="text-center" colspan="4"><?php echo $text_no_results; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="4"><?php echo $pagination; ?></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </form>

        </div>
    </div>

</section>
<?php echo $footer; ?> 